// What changed on Quran Masterclass – newest first. Add an entry with every release.
// title_ar / items_ar: Arabic version (optional – a missing one falls back to English)
export type Release = { date: string; title_en: string; title_de: string; items_en: string[]; items_de: string[]; title_ar?: string; items_ar?: string[] };
export const CHANGELOG: Release[] = [
  {
    date: "2026-10-06",
    title_en: "Stickers, ranking, community and the art of the mushaf",
    title_de: "Sticker, Ranking, Gemeinschaft und die Kunst des Mushaf",
    title_ar: "أوسمة وترتيب ومجتمع وفنّ المصحف",
    items_en: [
      "Points for steady learning: active time on the site, listening, verses heard, practice, daily sessions, lessons and quizzes – with daily limits, so it is about steadiness.",
      "Eight levels from Beginner to Companion of the Quran, and twelve stickers for your learning time from 1 to 10,000 hours: from a seed to a good tree (14:24), from the lamp (24:35) to the sun.",
      "Seventeen achievements (al-Fatiha, first surah, streaks, Arabic course, wudu, all 114 surahs heard, voice of Fajr …) with a small celebration when you earn one.",
      "Full statistics: listening per day, surah, reciter and hour, points of the last 30 days, where you stand.",
      "Global ranking by week, month and all time, and by country. Names appear only if you allow it.",
      "Community page: the most loved, viewed, shared and discussed verses, the most heard surahs, the latest reflections and your favourite verses. Hearts react at once.",
      "Wudu trainer for Sunni and Ja'fari practice with drawings, a counter and an order quiz, together with Quran 5:6.",
      "Illuminated surah opening like the first page of a mushaf, gold verse stars, gold calligraphy in the margins of wide screens, the skyline of the Emirates in the footer.",
      "Fixes: in long surahs (such as at-Tawbah) the verse cards no longer grow wider than the screen, and every verse change starts exactly at the top of its card.",
      "Search engines can now read the site and the sitemap once the domain is live.",
    ],
    items_de: [
      "Punkte für beständiges Lernen: aktive Zeit auf der Seite, Zuhören, gehörte Verse, Üben, Tagessitzungen, Lektionen und Quizze – mit Tagesgrenzen, damit es um Beständigkeit geht.",
      "Acht Level von Anfänger bis Gefährte des Quran und zwölf Sticker für deine Lernzeit von 1 bis 10.000 Stunden: vom Samenkorn zum guten Baum (14:24), von der Lampe (24:35) bis zur Sonne.",
      "Siebzehn Abzeichen (al-Fatiha, erste Sure, Serien, Arabisch-Kurs, Wudu, alle 114 Suren gehört, Stimme des Fadschr …) mit einer kleinen Feier, wenn du eines erreichst.",
      "Volle Statistik: Hörzeit nach Tag, Sure, Rezitator und Uhrzeit, Punkte der letzten 30 Tage, dein Lernstand.",
      "Globales Ranking nach Woche, Monat und gesamt sowie nach Ländern. Namen erscheinen nur, wenn du es erlaubst.",
      "Gemeinschafts-Seite: die beliebtesten, meistgesehenen, meistgeteilten und meistdiskutierten Verse, die meistgehörten Suren, die neuesten Gedanken und deine Lieblingsverse. Herzen reagieren sofort.",
      "Wudu-Trainer für die sunnitische und dscha'faritische Praxis mit Zeichnungen, Zähler und Reihenfolge-Quiz, dazu Quran 5:6.",
      "Illuminierter Surenanfang wie die erste Seite eines Mushaf, goldene Verssterne, goldene Kalligrafie an den Rändern großer Bildschirme, die Skyline der Emirate im Footer.",
      "Behoben: In langen Suren (etwa at-Tawba) werden die Vers-Karten nicht mehr breiter als der Bildschirm, und jeder Verswechsel beginnt genau am oberen Rand seiner Karte.",
      "Suchmaschinen können die Seite und die Sitemap jetzt lesen, sobald die Domain live ist.",
    ],
    items_ar: [
      "نقاط للتعلّم المنتظم: وقت النشاط في الموقع، والاستماع، والآيات المسموعة، والمراجعة، والجلسات اليومية، والدروس والاختبارات، مع حدود يومية لأن العبرة بالمداومة.",
      "ثمانية مستويات من مبتدئ إلى رفيق القرآن، واثنا عشر وسامًا لوقت تعلّمك من ساعة إلى عشرة آلاف ساعة: من البذرة إلى الشجرة الطيبة (14:24)، ومن المصباح (24:35) إلى الشمس.",
      "سبعة عشر إنجازًا (الفاتحة، أول سورة، السلاسل، دورة العربية، الوضوء، الاستماع إلى السور الـ114، صوت الفجر …) مع احتفال صغير عند تحقيق كل منها.",
      "إحصاءات كاملة: الاستماع حسب اليوم والسورة والقارئ والساعة، ونقاط آخر 30 يومًا، ومستواك في التعلّم.",
      "ترتيب عالمي أسبوعي وشهري وكلي، وترتيب للبلدان. لا يظهر الاسم إلا بإذنك.",
      "صفحة المجتمع: أحبّ الآيات وأكثرها مشاهدةً ومشاركةً ونقاشًا، وأكثر السور استماعًا، وأحدث الخواطر، وآياتك المفضّلة.",
      "مدرّب الوضوء على مذهب أهل السنة والمذهب الجعفري، برسوم وعدّاد واختبار في الترتيب، مع آية المائدة 6.",
      "افتتاحية مزخرفة للسورة كأول صفحة في المصحف، ونجوم ذهبية لأرقام الآيات، وخط ذهبي على جانبي الشاشات الكبيرة، وأفق الإمارات في أسفل الصفحة.",
      "إصلاحات: في السور الطويلة (كالتوبة) لم تعد بطاقات الآيات أعرض من الشاشة، ويبدأ كل انتقال إلى آية جديدة من أعلى بطاقتها تمامًا.",
      "صار بإمكان محركات البحث قراءة الموقع وخريطته بعد تشغيل النطاق.",
    ],
  },
  {
    date: "2026-10-06",
    title_en: "Daily session, Quran secrets, Android app and modern Islamic art",
    title_de: "Tagessitzung, Geheimnisse des Quran, Android-App und moderne islamische Kunst",
    title_ar: "الجلسة اليومية وأسرار القرآن وتطبيق أندرويد والفن الإسلامي الحديث",
    items_en: [
      "Guided daily session: repairs, reviews and new verses across surahs with a progress bar and a closing celebration; onboarding with three questions and a personal path; 12-week activity calendar.",
      "Learning technology: an FSRS memory model for every verse, recite-and-check with speech recognition, record and compare, tap any word to hear it, surahs saved for offline use.",
      "The Shams coach plans every verse on its own (new, repair, refresh, quick check), with a focus mode and a 'connect' step.",
      "Secrets of the Quran: word counts checked in the full Uthmani text, popular claims checked honestly, the surah without basmala and more – in 14 languages.",
      "Arabic course: units 7 and 8 with real Quran words and whole verses, and a placement test.",
      "Android app built from the whole website; app page with install help.",
      "Modern Emirati Islamic art: a slowly turning lattice of light after the Louvre Abu Dhabi, calligraphy that writes itself, a ring of verses after the Museum of the Future, mihrab niches and domed cards.",
      "Assistant open to visitors (a few questions a day), 13 more radio stations including the Juz of the day, Ziina support with QR code, one navigation and one footer for every page.",
    ],
    items_de: [
      "Geführte Tagessitzung: Reparaturen, Wiederholungen und neue Verse über Suren hinweg, mit Fortschrittsleiste und einer kleinen Feier am Ende; Einstieg mit drei Fragen und persönlichem Weg; Aktivitätskalender über 12 Wochen.",
      "Lerntechnik: ein FSRS-Gedächtnismodell für jeden Vers, Rezitation prüfen mit Spracherkennung, aufnehmen und vergleichen, jedes Wort antippen und hören, Suren offline speichern.",
      "Der Shams-Coach plant jeden Vers einzeln (neu, reparieren, auffrischen, kurzer Check), mit Fokus-Modus und dem Schritt „Verbinden“.",
      "Geheimnisse des Quran: Wortzählungen im vollständigen uthmanischen Text geprüft, verbreitete Behauptungen ehrlich geprüft, die Sure ohne Basmala und mehr – in 14 Sprachen.",
      "Arabisch-Kurs: Einheiten 7 und 8 mit echten Quranwörtern und ganzen Versen, dazu ein Einstufungstest.",
      "Android-App aus der gesamten Website; App-Seite mit Installationshilfe.",
      "Moderne emiratische islamische Kunst: ein langsam drehendes Lichtgitter nach dem Louvre Abu Dhabi, Kalligrafie, die sich selbst schreibt, ein Versring nach dem Museum of the Future, Mihrab-Nischen und Kuppelkarten.",
      "Assistent für Besucher geöffnet (einige Fragen pro Tag), 13 weitere Radiosender inklusive Juz des Tages, Unterstützung über Ziina mit QR-Code, eine Navigation und ein Footer für alle Seiten.",
    ],
    items_ar: [
      "جلسة يومية موجّهة: إصلاح ومراجعة وآيات جديدة عبر السور، مع شريط تقدّم واحتفال صغير في الختام؛ بداية بثلاثة أسئلة ومسار شخصي؛ وتقويم نشاط لاثني عشر أسبوعًا.",
      "تقنيات التعلّم: نموذج ذاكرة FSRS لكل آية، وفحص التلاوة بالتعرّف على الصوت، والتسجيل والمقارنة، والاستماع إلى أي كلمة بلمسة، وحفظ السور للاستخدام دون اتصال.",
      "مدرّب شمس يخطّط لكل آية على حدة (جديدة، إصلاح، تنشيط، فحص سريع)، مع وضع التركيز وخطوة «الربط».",
      "أسرار القرآن: أعداد الكلمات مُتحقَّق منها في النص العثماني الكامل، وفحص أمين للأقوال الشائعة، والسورة التي لا بسملة لها وغير ذلك، بـ14 لغة.",
      "دورة العربية: الوحدتان السابعة والثامنة بكلمات قرآنية حقيقية وآيات كاملة، مع اختبار لتحديد المستوى.",
      "تطبيق أندرويد مبنيّ على الموقع كاملًا، وصفحة للتطبيق مع شرح التثبيت.",
      "فن إسلامي إماراتي حديث: شبكة ضوء تدور ببطء على طريقة متحف اللوفر أبوظبي، وخط يكتب نفسه، وحلقة آيات على طريقة متحف المستقبل، ومحاريب وبطاقات بقباب.",
      "المساعد متاح للزوار (بضعة أسئلة يوميًا)، و13 محطة إذاعية جديدة منها جزء اليوم، والدعم عبر Ziina برمز QR، وقائمة واحدة وتذييل واحد لكل الصفحات.",
    ],
  },
  {
    date: "2026-10-06",
    title_en: "Academy, Shams Method and account-first learning",
    title_de: "Academy, Shams-Methode und Lernen über das Konto",
    title_ar: "الأكاديمية ومنهج شمس والتعلّم عبر الحساب",
    items_ar: [
      "منهج شمس: سبع خطوات موجَّهة لكل آية – الاستماع، والبناء من الآخر بحسب توقيت الكلمات، وكلمة بكلمة، والمعنى مع وسائل التذكّر، والتفسير، وتلاشي الحروف الأولى، والتدبّر.",
      "الأكاديمية: مسار تعلّم عبر السور الـ114 كلها، باختبارات موقوتة ومستويات وسلاسل أيام وهدف يومي ينمو معك.",
      "خطط لـ365 يومًا بمقادير يومية متدرّجة، من الخطة الهادئة حتى مسار الحافظ.",
      "دورة تجويد من 14 درسًا، ومدرّب لمفردات القرآن، ومخطط للختمة، و10 أدلة موسّعة.",
      "109 أدعية للنبي ﷺ مع مصادرها، إضافةً إلى أدعية القرآن الكريم.",
      "صفحة الملف الشخصي مع الإحصاءات وتصدير البيانات وحذف الحساب؛ ويتكيّف المنهج مع عمرك.",
      "تستمر الإذاعة وتشغيل الآيات أثناء تصفّحك، مع مشغّل مصغّر دائم.",
      "التعليقات والإعجابات والمشاركة على الآيات – وكل تعليق يُراجَع قبل ظهوره.",
      "أمان أقوى: ترويسات أمان، وكلمات مرور أشد، وحماية من تخمين كلمات المرور.",
    ],
    items_en: [
      "The Shams Method: seven guided steps per verse – listen, build up backwards using word timings, word by word, meaning and memory hooks, tafsir, fading first-letter cues, reflection.",
      "Academy: a learning path through all 114 surahs with timed tests, levels, streaks and a daily goal that grows.",
      "365-day plans with growing daily portions, from gentle to the hafiz track.",
      "Tajweed course with 14 lessons, Quran vocabulary trainer, khatm planner and 10 in-depth guides.",
      "109 duas of the Prophet ﷺ with sources, plus the duas of the Quran.",
      "Profile page with statistics, data export and account deletion; the method adapts to your age.",
      "Radio and verse playback keep playing while you browse; persistent mini player.",
      "Comments, likes and shares on verses – every comment is reviewed before it appears.",
      "Stronger security: security headers, stricter passwords, login throttling.",
    ],
    items_de: [
      "Die Shams-Methode: sieben geführte Schritte pro Vers – hören, rückwärts aufbauen mit Wortzeiten, Wort für Wort, Bedeutung und Eselsbrücken, Tafsir, verblassende Anfangsbuchstaben, Nachdenken.",
      "Academy: ein Lernpfad durch alle 114 Suren mit Tests auf Zeit, Levels, Serien und einem wachsenden Tagesziel.",
      "365-Tage-Pläne mit wachsender Tagesmenge, von Sanft bis zum Hafiz-Track.",
      "Tajweed-Kurs mit 14 Lektionen, Koran-Vokabeltrainer, Khatm-Planer und 10 ausführliche Ratgeber.",
      "109 Bittgebete des Propheten ﷺ mit Quellen, dazu die Duas aus dem Koran.",
      "Profilseite mit Statistiken, Datenexport und Kontolöschung; die Methode passt sich deinem Alter an.",
      "Radio und Vers-Wiedergabe laufen beim Surfen weiter; dauerhafter Mini-Player.",
      "Kommentare, Likes und Teilen bei Versen – jeder Kommentar wird vor dem Erscheinen geprüft.",
      "Mehr Sicherheit: Sicherheits-Header, strengere Passwörter, Schutz gegen Passwort-Raten.",
    ],
  },
  {
    date: "2026-10-05",
    title_en: "Prayer times, Quran radio and 13 languages",
    title_de: "Gebetszeiten, Koran-Radio und 13 Sprachen",
    title_ar: "أوقات الصلاة وإذاعة القرآن و13 لغة",
    items_ar: ["أوقات الصلاة لموقعك وللمدن الكبرى، مع التاريخ الهجري.", "إذاعة القرآن بمحطاتها ومؤقّت النوم والأذان عند دخول وقت الصلاة.", "واجهة بـ13 لغة، منها العربية والتركية والأردية والفارسية والبشتو والبنغالية."],
    items_en: ["Prayer times for your location and major cities, with Hijri date.", "Quran radio with stations, sleep timer and adhan at prayer time.", "Interface in 13 languages including Arabic, Turkish, Urdu, Persian, Pashto and Bengali."],
    items_de: ["Gebetszeiten für deinen Ort und große Städte, mit Hidschri-Datum.", "Koran-Radio mit Sendern, Einschlaf-Timer und Adhan zur Gebetszeit.", "Oberfläche in 13 Sprachen, darunter Arabisch, Türkisch, Urdu, Persisch, Paschtu und Bengalisch."],
  },
];
