// Prayer trainer (/salah): the five daily prayers step by step, in the Sunni form and in the Ja'fari (Shia) form.
// Wording follows the standard texts taught in both traditions; where schools differ, the notes say so.
export type Posture = "stand" | "takbir" | "folded" | "sides" | "qunut" | "ruku" | "sujud" | "sujudTurbah" | "sit" | "tashahhud" | "salamR" | "salamL";
export type L2 = { de: string; en: string; ar?: string };
export type Step = { posture: Posture; title: L2; ar?: string; tr?: string; meaning?: L2; note?: L2; rakah: number; aloud?: boolean };
export type Tradition = "sunni" | "shia";
export const PRAYERS = [
  { id: "fajr", rakat: 2, name: L("Fadschr", "Fajr", "الفجر"), ar: "الفجر", aloudAll: true },
  { id: "dhuhr", rakat: 4, name: L("Dhuhr", "Dhuhr", "الظهر"), ar: "الظهر", aloudAll: false },
  { id: "asr", rakat: 4, name: L("Asr", "Asr", "العصر"), ar: "العصر", aloudAll: false },
  { id: "maghrib", rakat: 3, name: L("Maghrib", "Maghrib", "المغرب"), ar: "المغرب", aloudAll: true },
  { id: "isha", rakat: 4, name: L("Ischa", "Isha", "العشاء"), ar: "العشاء", aloudAll: true },
] as const;
function L(de: string, en: string, ar?: string): L2 { return { de, en, ar }; }
// Arabic wording helpers (number agreement / ordinals for the generated sentences)
const RAKAT_AR: Record<number, string> = { 2: "ركعتين", 3: "ثلاث ركعات", 4: "أربع ركعات" };
const ORD_AR = ["", "الأولى", "الثانية", "الثالثة", "الرابعة"];

const T = {
  takbir: { ar: "اللهُ أَكْبَرُ", tr: "Allāhu akbar", meaning: L("Allah ist größer.", "Allah is the Greatest.", "اللهُ أعظمُ وأجلُّ من كلِّ شيء.") },
  thana: { ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ", tr: "Subḥānaka llāhumma wa biḥamdika, wa tabāraka smuka, wa taʿālā jadduka, wa lā ilāha ghayruk", meaning: L("Gepriesen bist du, o Allah, und dir gebührt das Lob. Gesegnet ist dein Name, erhaben deine Majestät, und es gibt keinen Gott außer dir.", "Glory be to You, O Allah, and praise. Blessed is Your name, exalted Your majesty, and there is no god but You.", "أُنزِّهُك يا الله تنزيهًا مقرونًا بحمدك، وعظُمت بركةُ اسمك، وعلا جلالُك وعظمتُك، ولا معبودَ بحقٍّ سواك.") },
  taawwudh: { ar: "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", tr: "Aʿūdhu billāhi mina sh-shayṭāni r-rajīm", meaning: L("Ich nehme Zuflucht bei Allah vor dem verfluchten Satan.", "I seek refuge in Allah from the accursed Satan.", "ألتجئُ إلى الله وأعتصمُ به من الشيطان المطرود من رحمته.") },
  fatiha: { ar: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ …", tr: "Bismillāhi r-raḥmāni r-raḥīm. Al-ḥamdu lillāhi rabbi l-ʿālamīn …", meaning: L("Die ganze Al-Fatiha – ohne sie ist kein Gebet gültig. Lerne sie Vers für Vers im Player.", "The whole of Al-Fatiha – no prayer is valid without it. Learn it verse by verse in the player.", "سورةُ الفاتحة كاملةً، فـ«لا صلاةَ لمن لم يقرأ بفاتحة الكتاب». تعلَّمها آيةً آيةً في المشغِّل.") },
  ikhlas: { ar: "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ", tr: "Qul huwa llāhu aḥad. Allāhu ṣ-ṣamad. Lam yalid wa lam yūlad. Wa lam yakun lahū kufuwan aḥad.", meaning: L("Zum Beispiel Al-Ikhlas (Sure 112) – jede andere Sure oder einige Verse sind ebenso möglich.", "For example Al-Ikhlas (Surah 112) – any other surah or a few verses are also fine.", "مثلُ سورة الإخلاص (السورة 112)، ويجوز أن تقرأ غيرها من السور أو آياتٍ منها.") },
  rukuSunni: { ar: "سُبْحَانَ رَبِّيَ الْعَظِيمِ", tr: "Subḥāna rabbiya l-ʿaẓīm (3×)", meaning: L("Gepriesen sei mein Herr, der Gewaltige.", "Glory be to my Lord, the Magnificent.", "أُنزِّهُ ربِّيَ العظيمَ عن كلِّ نقص.") },
  rukuShia: { ar: "سُبْحَانَ رَبِّيَ الْعَظِيمِ وَبِحَمْدِهِ", tr: "Subḥāna rabbiya l-ʿaẓīmi wa biḥamdih", meaning: L("Gepriesen sei mein Herr, der Gewaltige, und Lob gebührt ihm.", "Glory be to my Lord, the Magnificent, and praise be to Him.", "أُنزِّهُ ربِّيَ العظيمَ عن كلِّ نقص، وأحمَدُه.") },
  rise: { ar: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ ۝ رَبَّنَا وَلَكَ الْحَمْدُ", tr: "Samiʿa llāhu liman ḥamidah – Rabbanā wa laka l-ḥamd", meaning: L("Allah hört den, der ihn lobt. – Unser Herr, dir gebührt das Lob.", "Allah hears the one who praises Him. – Our Lord, to You belongs the praise.", "يتقبَّلُ اللهُ حمدَ من حمِده ويُجيبه. – يا ربَّنا، لك الحمدُ كلُّه.") },
  sujudSunni: { ar: "سُبْحَانَ رَبِّيَ الْأَعْلَى", tr: "Subḥāna rabbiya l-aʿlā (3×)", meaning: L("Gepriesen sei mein Herr, der Allerhöchste.", "Glory be to my Lord, the Most High.", "أُنزِّهُ ربِّيَ الأعلى فوقَ خلقه عن كلِّ نقص.") },
  sujudShia: { ar: "سُبْحَانَ رَبِّيَ الْأَعْلَى وَبِحَمْدِهِ", tr: "Subḥāna rabbiya l-aʿlā wa biḥamdih", meaning: L("Gepriesen sei mein Herr, der Allerhöchste, und Lob gebührt ihm.", "Glory be to my Lord, the Most High, and praise be to Him.", "أُنزِّهُ ربِّيَ الأعلى عن كلِّ نقص، وأحمَدُه.") },
  sitSunni: { ar: "رَبِّ اغْفِرْ لِي", tr: "Rabbi ghfir lī", meaning: L("Mein Herr, vergib mir.", "My Lord, forgive me.", "يا ربِّ، اغفر لي ذنوبي.") },
  sitShia: { ar: "أَسْتَغْفِرُ اللَّهَ رَبِّي وَأَتُوبُ إِلَيْهِ", tr: "Astaghfiru llāha rabbī wa atūbu ilayh", meaning: L("Ich bitte Allah, meinen Herrn, um Vergebung und wende mich ihm reuig zu.", "I ask Allah, my Lord, for forgiveness and turn to Him in repentance.", "أطلبُ المغفرةَ من الله ربِّي، وأرجعُ إليه تائبًا.") },
  tashSunni: { ar: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", tr: "At-taḥiyyātu lillāhi wa ṣ-ṣalawātu wa ṭ-ṭayyibāt. As-salāmu ʿalayka ayyuha n-nabiyyu wa raḥmatu llāhi wa barakātuh. As-salāmu ʿalaynā wa ʿalā ʿibādi llāhi ṣ-ṣāliḥīn. Ash-hadu an lā ilāha illa llāh, wa ash-hadu anna Muḥammadan ʿabduhū wa rasūluh.", meaning: L("Alle Grüße, Gebete und guten Worte gehören Allah. Friede sei mit dir, o Prophet, und Allahs Barmherzigkeit und Segen. Friede sei mit uns und mit den rechtschaffenen Dienern Allahs. Ich bezeuge, dass es keinen Gott gibt außer Allah, und ich bezeuge, dass Muhammad sein Diener und Gesandter ist.", "All greetings, prayers and good words belong to Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and Messenger.", "كلُّ ألفاظ التعظيم والصلوات والكلمات الطيبة لله وحده. ثم نُسلِّم على النبي ﷺ وندعو له بالرحمة والبركة، ثم على أنفسنا وعلى عباد الله الصالحين، ثم نشهد لله بالوحدانية، ولمحمدٍ ﷺ بالعبودية والرسالة.") },
  salawat: { ar: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ", tr: "Allāhumma ṣalli ʿalā Muḥammadin wa ʿalā āli Muḥammad, kamā ṣallayta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd. Allāhumma bārik ʿalā Muḥammadin wa ʿalā āli Muḥammad, kamā bārakta ʿalā Ibrāhīma wa ʿalā āli Ibrāhīm, innaka ḥamīdun majīd.", meaning: L("O Allah, segne Muhammad und die Familie Muhammads, wie du Ibrahim und die Familie Ibrahims gesegnet hast – du bist der Lobenswerte, der Ruhmreiche. O Allah, gib Muhammad und der Familie Muhammads Segen, wie du Ibrahim und der Familie Ibrahims Segen gegeben hast – du bist der Lobenswerte, der Ruhmreiche.", "O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim – You are Praiseworthy, Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim – You are Praiseworthy, Glorious.", "نسألُ اللهَ أن يُثنيَ على نبيِّه محمدٍ ﷺ وعلى آله ويُباركَ عليهم، كما أثنى على إبراهيم عليه السلام وآله وبارك عليهم؛ إنه سبحانه المحمودُ في ذاته وصفاته، العظيمُ في مجده.") },
  salam: { ar: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", tr: "As-salāmu ʿalaykum wa raḥmatu llāh", meaning: L("Friede sei mit euch und die Barmherzigkeit Allahs.", "Peace be upon you and the mercy of Allah.", "دعاءٌ بالسلامة ورحمة الله لمن حولك.") },
  tashShia: { ar: "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَآلِ مُحَمَّدٍ", tr: "Ash-hadu an lā ilāha illa llāhu waḥdahū lā sharīka lah, wa ash-hadu anna Muḥammadan ʿabduhū wa rasūluh. Allāhumma ṣalli ʿalā Muḥammadin wa āli Muḥammad.", meaning: L("Ich bezeuge, dass es keinen Gott gibt außer Allah, dem Einen ohne Teilhaber, und ich bezeuge, dass Muhammad sein Diener und Gesandter ist. O Allah, segne Muhammad und die Familie Muhammads.", "I bear witness that there is no god but Allah, alone without partner, and that Muhammad is His servant and Messenger. O Allah, send prayers upon Muhammad and the family of Muhammad.", "شهادةٌ لله بالوحدانية وأنه لا شريك له، ولمحمدٍ ﷺ بالعبودية والرسالة، ثم الصلاةُ على محمدٍ وآل محمد.") },
  salamShia: { ar: "السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ", tr: "As-salāmu ʿalayka ayyuha n-nabiyyu wa raḥmatu llāhi wa barakātuh. As-salāmu ʿalaynā wa ʿalā ʿibādi llāhi ṣ-ṣāliḥīn. As-salāmu ʿalaykum wa raḥmatu llāhi wa barakātuh.", meaning: L("Friede sei mit dir, o Prophet, und Allahs Barmherzigkeit und Segen. Friede sei mit uns und mit den rechtschaffenen Dienern Allahs. Friede sei mit euch und Allahs Barmherzigkeit und Segen.", "Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. Peace be upon you all and the mercy of Allah and His blessings.", "السلامُ على النبي ﷺ، ثم على المصلّي نفسه وعلى عباد الله الصالحين، ثم على الحاضرين جميعًا، مع رحمة الله وبركاته.") },
  tasbihat: { ar: "سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ", tr: "Subḥāna llāhi wa l-ḥamdu lillāhi wa lā ilāha illa llāhu wa llāhu akbar (3×)", meaning: L("Gepriesen sei Allah, alles Lob gebührt Allah, es gibt keinen Gott außer Allah, und Allah ist größer.", "Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest.", "تنزيهُ الله، وحمدُه، وتوحيدُه، وتكبيرُه.") },
  qunut: { ar: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", tr: "Rabbanā ātinā fi d-dunyā ḥasanatan wa fi l-ākhirati ḥasanatan wa qinā ʿadhāba n-nār", meaning: L("Unser Herr, gib uns im Diesseits Gutes und im Jenseits Gutes und bewahre uns vor der Strafe des Feuers (2:201) – jedes Bittgebet ist möglich.", "Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire (2:201) – any supplication may be said.", "دعاءٌ جامعٌ لخيرَي الدنيا والآخرة والنجاةِ من النار (البقرة: 201)، ويجوز الدعاءُ بأيِّ دعاءٍ آخر.") },
  bihawl: { ar: "بِحَوْلِ اللَّهِ وَقُوَّتِهِ أَقُومُ وَأَقْعُدُ", tr: "Biḥawli llāhi wa quwwatihī aqūmu wa aqʿud", meaning: L("Mit Allahs Macht und Kraft stehe ich auf und setze mich.", "By the power and strength of Allah I stand and sit.", "أقومُ وأقعدُ بقدرة الله وقوَّته، لا بحولي ولا بقوَّتي.") },
};

const s = (rakah: number, posture: Posture, title: L2, txt?: { ar: string; tr: string; meaning: L2 }, note?: L2, aloud?: boolean): Step => ({ rakah, posture, title, ...(txt ?? {}), note, aloud });

export function buildPrayer(id: (typeof PRAYERS)[number]["id"], tradition: Tradition): Step[] {
  const p = PRAYERS.find((x) => x.id === id)!;
  const sunni = tradition === "sunni";
  const out: Step[] = [];
  const stand: Posture = sunni ? "folded" : "sides";
  out.push(s(1, "stand", L("Absicht (Niyya)", "Intention (niyyah)", "النيّة"), undefined, L(`Stell dich in Richtung Qibla und fasse im Herzen die Absicht, das ${p.name.de}-Gebet mit ${p.rakat} Rakaat zu beten. Die Absicht wird nicht laut ausgesprochen.`, `Face the qibla and make the intention in your heart to pray ${p.name.en} with ${p.rakat} rak'at. The intention is not said out loud.`, `استقبلِ القبلة، وانوِ بقلبك أداءَ صلاة ${p.ar} ${RAKAT_AR[p.rakat]}. ومحلُّ النيّة القلب، فلا يُجهَر بها.`)));
  out.push(s(1, "takbir", L("Eröffnungs-Takbir", "Opening takbir", "تكبيرة الإحرام"), T.takbir, L("Hebe die Hände bis zu den Ohren oder Schultern. Ab jetzt bist du im Gebet.", "Raise your hands to your ears or shoulders. From now on you are in prayer.", "ارفع يديك حذوَ أذنيك أو منكبيك. وبها تدخل في الصلاة.")));
  for (let r = 1; r <= p.rakat; r++) {
    const aloud = p.aloudAll && r <= 2;
    if (r === 1 && sunni) { out.push(s(r, stand, L("Eröffnungsbittgebet", "Opening supplication", "دعاء الاستفتاح"), T.thana, L("Leise. Hanafiten und Hanbaliten halten die Hände unter dem Nabel bzw. auf der Brust, Schafiiten auf der Brust; viele Malikiten lassen sie seitlich hängen – alles ist überliefert.", "Silently. Hands are held below the navel or on the chest depending on the school; many Malikis let them hang – all of this is transmitted.", "يُقال سرًّا. وتوضع اليدان تحت السُّرّة أو على الصدر بحسب المذهب، وكثيرٌ من المالكية يُرسلونهما (السَّدْل) – وكلُّ ذلك مأثور."))); out.push(s(r, stand, L("Zufluchtnahme", "Seeking refuge", "الاستعاذة"), T.taawwudh)); }
    if (r <= 2 || !sunni) out.push(s(r, stand, L("Al-Fatiha", "Al-Fatiha", "سورة الفاتحة"), T.fatiha, sunni ? L(aloud ? "Laut rezitiert (beim Imam/allein), danach „Āmīn“." : "Leise rezitiert, danach „Āmīn“.", aloud ? "Recited aloud (as imam or alone), then “Āmīn”." : "Recited silently, then “Āmīn”.", aloud ? "يُجهَر بها (للإمام والمنفرد)، ثم يُقال: «آمين»." : "تُقرأ سرًّا، ثم يُقال: «آمين».") : r <= 2 ? L(aloud ? "Laut rezitiert. In der Dscha'fari-Schule wird danach kein „Āmīn“ gesagt." : "Leise rezitiert. Danach kein „Āmīn“.", aloud ? "Recited aloud. In the Ja'fari school no “Āmīn” is said afterwards." : "Recited silently. No “Āmīn” afterwards.", aloud ? "يُجهَر بها. وفي المذهب الجعفري لا يُقال بعدها «آمين»." : "تُقرأ سرًّا، ولا يُقال بعدها «آمين».") : L("In der 3. und 4. Raka kannst du statt der Fatiha die „vier Lobpreisungen“ sagen (nächster Schritt).", "In the 3rd and 4th rak'ah you may say the “four glorifications” instead of Al-Fatiha (next step).", "في الركعتين الثالثة والرابعة يجوز لك أن تقول «التسبيحات الأربع» بدلًا من الفاتحة (الخطوة التالية)."), aloud));
    if (!sunni && r >= 3) out.push(s(r, stand, L("Die vier Lobpreisungen", "The four glorifications", "التسبيحات الأربع"), T.tasbihat, L("Leise, dreimal – oder einmal die Fatiha.", "Silently, three times – or Al-Fatiha once.", "تُقال سرًّا ثلاثَ مرات – أو تُقرأ الفاتحة مرةً واحدة.")));
    if (r <= 2) out.push(s(r, stand, L("Eine Sure", "A surah", "قراءة سورة"), T.ikhlas, sunni ? L("Nur in den ersten beiden Rakaat.", "Only in the first two rak'at.", "في الركعتين الأُولَيين فقط.") : L("Nur in den ersten beiden Rakaat; in der Dscha'fari-Schule eine vollständige Sure.", "Only in the first two rak'at; in the Ja'fari school a complete surah.", "في الركعتين الأُولَيين فقط؛ وفي المذهب الجعفري تُقرأ سورةٌ كاملة."), aloud));
    if (!sunni && r === 2) out.push(s(r, "qunut", L("Qunut", "Qunut", "القنوت"), T.qunut, L("Empfohlen: Hebe die Hände mit den Handflächen nach oben vor das Gesicht und sprich ein Bittgebet – vor der Verbeugung der zweiten Raka.", "Recommended: raise your hands, palms up, in front of your face and make a supplication – before the bowing of the second rak'ah.", "مستحبّ: ارفع يديك حِيالَ وجهك وباطنُ كفَّيك إلى السماء، وادعُ بما شئت – وذلك قبل ركوع الركعة الثانية.")));
    out.push(s(r, "ruku", L("Verbeugung (Ruku')", "Bowing (ruku')", "الركوع"), sunni ? T.rukuSunni : T.rukuShia, L("Mit „Allāhu akbar“ verbeugen, Hände auf die Knie, Rücken gerade.", "Bow with “Allāhu akbar”, hands on the knees, back straight.", "اركع قائلًا «الله أكبر»، واضعًا يديك على ركبتيك، مستويَ الظهر.")));
    out.push(s(r, sunni ? "sides" : "sides", L("Aufrichten (I'tidal)", "Rising (i'tidal)", "الاعتدال من الركوع"), T.rise, sunni ? L("Ganz aufrichten und kurz ruhig stehen.", "Stand fully upright and be still for a moment.", "اعتدل قائمًا تمامًا، واطمئنَّ لحظة.") : L("Ganz aufrichten; das Sprechen dieser Worte ist empfohlen.", "Stand fully upright; saying these words is recommended.", "اعتدل قائمًا تمامًا؛ ويُستحبّ قولُ هذا الذكر.")));
    for (const n of [1, 2]) {
      out.push(s(r, sunni ? "sujud" : "sujudTurbah", L(n === 1 ? "Niederwerfung (Sudschud)" : "Zweite Niederwerfung", n === 1 ? "Prostration (sujud)" : "Second prostration", n === 1 ? "السجود" : "السجدة الثانية"), sunni ? T.sujudSunni : T.sujudShia, n === 1 ? (sunni ? L("Mit „Allāhu akbar“ nieder auf sieben Körperteile: Stirn mit Nase, beide Hände, beide Knie, beide Fußspitzen.", "With “Allāhu akbar” down onto seven parts: forehead with nose, both hands, both knees, the toes of both feet.", "اسجد قائلًا «الله أكبر» على الأعضاء السبعة: الجبهة مع الأنف، والكفَّين، والركبتين، وأطراف القدمين.") : L("Auf sieben Körperteile; die Stirn liegt auf Erde oder auf dem, was aus ihr wächst und nicht gegessen oder getragen wird – meist auf einer Turba (Tontafel).", "On seven parts; the forehead rests on earth or on what grows from it and is not eaten or worn – usually on a turbah (clay tablet).", "على الأعضاء السبعة؛ وتوضع الجبهة على الأرض أو على ما أنبتته مما لا يُؤكل ولا يُلبس – وغالبًا على التربة (قرصٌ من الطين).")) : undefined));
      if (n === 1) out.push(s(r, "sit", L("Sitzen zwischen den Niederwerfungen", "Sitting between the prostrations", "الجلسة بين السجدتين"), sunni ? T.sitSunni : T.sitShia, L("Kurz und ruhig sitzen.", "Sit briefly and calmly.", "اجلس جلسةً قصيرةً مطمئنًّا.")));
    }
    const last = r === p.rakat;
    if (r === 2 || last) {
      out.push(s(r, "tashahhud", L(last ? "Letzter Taschahhud" : "Erster Taschahhud", last ? "Final tashahhud" : "First tashahhud", last ? "التشهد الأخير" : "التشهد الأول"), sunni ? T.tashSunni : T.tashShia, sunni ? L("Viele heben beim Glaubenszeugnis den Zeigefinger. Die Schafiiten und Malikiten überliefern eine leicht abweichende Fassung – beide sind gültig.", "Many raise the index finger at the testimony. The Shafi'is and Malikis transmit a slightly different wording – both are valid.", "يرفع كثيرٌ من المصلّين السبّابة عند الشهادة. ويروي الشافعية والمالكية صيغةً مختلفةً قليلًا – وكلتاهما صحيحة.") : undefined));
      if (last) {
        if (sunni) {
          out.push(s(r, "tashahhud", L("Segensgebet über den Propheten ﷺ", "Prayers upon the Prophet ﷺ", "الصلوات الإبراهيمية"), T.salawat, L("Danach darfst du ein eigenes Bittgebet sprechen.", "Afterwards you may make your own supplication.", "ثم لك أن تدعو بما أحببت من الدعاء.")));
          out.push(s(r, "salamR", L("Friedensgruß nach rechts", "Salam to the right", "التسليم عن اليمين"), T.salam));
          out.push(s(r, "salamL", L("Friedensgruß nach links", "Salam to the left", "التسليم عن الشمال"), T.salam, L("Das Gebet ist beendet. Danach: 33× Subḥāna llāh, 33× al-ḥamdu lillāh, 34× Allāhu akbar (Sahih Muslim).", "The prayer is complete. Afterwards: 33× Subḥāna llāh, 33× al-ḥamdu lillāh, 34× Allāhu akbar (Sahih Muslim).", "تمَّت الصلاة. ثم تُسبِّح: «سبحان الله» 33 مرة، و«الحمد لله» 33 مرة، و«الله أكبر» 34 مرة (صحيح مسلم).")));
        } else {
          out.push(s(r, "sit", L("Friedensgruß (Salam)", "Salam", "التسليم"), T.salamShia, L("Der letzte Satz ist der verpflichtende Teil, die ersten beiden sind empfohlen.", "The last sentence is the obligatory part, the first two are recommended.", "الصيغة الأخيرة هي الواجبة، والصيغتان الأُولَيان مستحبّتان.")));
          out.push(s(r, "takbir", L("Drei Takbir zum Abschluss", "Three takbirs to close", "التكبيرات الثلاث في الختام"), T.takbir, L("Empfohlen: dreimal „Allāhu akbar“ mit erhobenen Händen; danach der Tasbih der Fatima (34× Allāhu akbar, 33× al-ḥamdu lillāh, 33× Subḥāna llāh).", "Recommended: “Allāhu akbar” three times raising the hands; then the tasbih of Fatimah (34× Allāhu akbar, 33× al-ḥamdu lillāh, 33× Subḥāna llāh).", "مستحبّ: التكبير ثلاثًا مع رفع اليدين؛ ثم تسبيح فاطمة الزهراء عليها السلام («الله أكبر» 34 مرة، و«الحمد لله» 33 مرة، و«سبحان الله» 33 مرة).")));
        }
        break;
      }
    }
    out.push(s(r + 1, stand, L(`Aufstehen zur ${r + 1}. Raka`, `Stand up for rak'ah ${r + 1}`, `القيام إلى الركعة ${ORD_AR[r + 1]}`), sunni ? T.takbir : T.bihawl, sunni ? L("Mit „Allāhu akbar“ aufstehen.", "Stand up with “Allāhu akbar”.", "انهض قائلًا «الله أكبر».") : L("Beim Aufstehen empfohlen.", "Recommended while standing up.", "يُستحبّ قولُه عند النهوض.")));
  }
  return out;
}
