// Supplications of the Prophet ﷺ from the hadith collections (phase 2) – additional entries to sunnahDuas.ts.
// Arabic texts of the hadith are classical (public domain); transliteration and translations are our own.
// Only narrations graded sahih or hasan; every entry names its source. Pending review by a qualified scholar.
import type { SunnahDua } from "./sunnahDuas";

export const SUNNAH_DUAS_2: SunnahDua[] = [
  // Morning and evening
  {
    id: "afiyah-dunya-akhirah", cat: "morning",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي، اللَّهُمَّ اسْتُرْ عَوْرَاتِي، وَآمِنْ رَوْعَاتِي، اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي",
    tr: "Allāhumma innī asʾaluka l-ʿāfiyata fi d-dunyā wal-ākhirah. Allāhumma innī asʾaluka l-ʿafwa wal-ʿāfiyata fī dīnī wa dunyāya wa ahlī wa mālī. Allāhumma stur ʿawrātī, wa āmin rawʿātī. Allāhumma hfaznī min bayni yadayya, wa min khalfī, wa ʿan yamīnī, wa ʿan shimālī, wa min fawqī, wa aʿūdhu bi-ʿazamatika an ughtāla min tahtī.",
    en: "O Allah, I ask You for well-being in this world and the Hereafter. O Allah, I ask You for pardon and well-being in my religion, my worldly life, my family and my property. O Allah, cover my faults and calm my fears. O Allah, guard me from in front of me and behind me, from my right and my left and from above me, and I seek refuge in Your greatness from being struck down from beneath me. (Morning and evening – the Prophet ﷺ never left it.)",
    de: "O Allah, ich bitte Dich um Wohlergehen im Diesseits und im Jenseits. O Allah, ich bitte Dich um Verzeihung und Wohlergehen in meiner Religion, meinem weltlichen Leben, meiner Familie und meinem Besitz. O Allah, bedecke meine Blößen und beruhige meine Ängste. O Allah, beschütze mich von vorne und von hinten, von rechts und von links und von oben, und ich suche Zuflucht bei Deiner Größe davor, von unten her überwältigt zu werden. (Morgens und abends – der Prophet ﷺ ließ es nie aus.)",
    src: "Sunan Abi Dawud 5074; Sunan Ibn Majah 3871",
  },
  {
    id: "alim-al-ghayb", cat: "morning",
    ar: "اللَّهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ، عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ",
    tr: "Allāhumma fātira s-samāwāti wal-ard, ʿālima l-ghaybi wash-shahādah, rabba kulli shayʾin wa malīkah, ashhadu an lā ilāha illā ant, aʿūdhu bika min sharri nafsī, wa min sharri sh-shaytāni wa shirkih.",
    en: "O Allah, Originator of the heavens and the earth, Knower of the unseen and the seen, Lord and Sovereign of all things, I bear witness that there is no god but You. I seek refuge in You from the evil of my own soul and from the evil of Satan and his call to associate partners (with You). (Morning, evening and on going to bed.)",
    de: "O Allah, Schöpfer der Himmel und der Erde, Kenner des Verborgenen und des Offenbaren, Herr und Herrscher aller Dinge, ich bezeuge, dass es keinen Gott gibt außer Dir. Ich suche Zuflucht bei Dir vor dem Übel meiner eigenen Seele und vor dem Übel Satans und seiner Verleitung zur Beigesellung. (Morgens, abends und beim Schlafengehen.)",
    src: "Sunan Abi Dawud 5067; Jamiʿ at-Tirmidhi 3392",
  },
  {
    id: "tahlil-100", cat: "morning", n: 100,
    ar: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    tr: "Lā ilāha illā llāhu wahdahū lā sharīka lah, lahu l-mulku wa lahu l-hamd, wa huwa ʿalā kulli shayʾin qadīr.",
    en: "There is no god but Allah alone, without partner; His is the dominion and His the praise, and He has power over all things. (100 times a day; said 10 times, it is like freeing four souls from the descendants of Ismaʿil.)",
    de: "Es gibt keinen Gott außer Allah allein, ohne Teilhaber; Sein ist die Herrschaft und Sein das Lob, und Er hat Macht über alle Dinge. (100-mal am Tag; zehnmal gesprochen ist es, als hätte man vier Seelen aus den Nachkommen Ismails befreit.)",
    src: "Sahih al-Bukhari 6403; Sahih Muslim 2691; ten times: Sahih Muslim 2693",
  },
  {
    id: "adada-khalqihi", cat: "morning", n: 3,
    ar: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، عَدَدَ خَلْقِهِ، وَرِضَا نَفْسِهِ، وَزِنَةَ عَرْشِهِ، وَمِدَادَ كَلِمَاتِهِ",
    tr: "Subhāna llāhi wa bi-hamdih, ʿadada khalqih, wa ridā nafsih, wa zinata ʿarshih, wa midāda kalimātih.",
    en: "Glory be to Allah and praise be to Him, as many times as the number of His creation, as much as pleases Him, as much as the weight of His Throne and as much as the ink of His words. (Taught by the Prophet ﷺ to Juwayriyah after the morning prayer.)",
    de: "Gepriesen sei Allah, und Lob sei Ihm – so oft wie die Zahl Seiner Geschöpfe, so viel, wie Ihm gefällt, so schwer wie das Gewicht Seines Throns und so viel wie die Tinte Seiner Worte. (Vom Propheten ﷺ Juwayriyah nach dem Morgengebet gelehrt.)",
    src: "Sahih Muslim 2726",
  },

  // Sleep and waking
  {
    id: "aslamtu-nafsi", cat: "sleep",
    ar: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنْزَلْتَ، وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ",
    tr: "Allāhumma aslamtu nafsī ilayk, wa wajjahtu wajhī ilayk, wa fawwadtu amrī ilayk, wa aljaʾtu zahrī ilayk, raghbatan wa rahbatan ilayk, lā maljaʾa wa lā manjā minka illā ilayk, āmantu bi-kitābika lladhī anzalt, wa bi-nabiyyika lladhī arsalt.",
    en: "O Allah, I have submitted my soul to You, turned my face to You, entrusted my affairs to You and leaned my back on You, in hope and in awe of You. There is no refuge and no escape from You except to You. I believe in Your Book which You revealed and in Your Prophet whom You sent. (The last words before sleep, lying on the right side after wudu.)",
    de: "O Allah, ich habe meine Seele Dir ergeben, mein Gesicht Dir zugewandt, meine Angelegenheit Dir anvertraut und meinen Rücken an Dich gelehnt, in Hoffnung auf Dich und in Ehrfurcht vor Dir. Es gibt keine Zuflucht und keine Rettung vor Dir außer zu Dir. Ich glaube an Dein Buch, das Du herabgesandt hast, und an Deinen Propheten, den Du gesandt hast. (Die letzten Worte vor dem Schlafen, auf der rechten Seite liegend nach der Gebetswaschung.)",
    src: "Sahih al-Bukhari 247, 6313; Sahih Muslim 2710",
  },
  {
    id: "tasbih-fatima", cat: "sleep",
    ar: "سُبْحَانَ اللَّهِ (٣٣)، الْحَمْدُ لِلَّهِ (٣٣)، اللَّهُ أَكْبَرُ (٣٤)",
    tr: "Subhāna llāh (33), al-hamdu lillāh (33), Allāhu akbar (34).",
    en: "Glory be to Allah (33 times), praise be to Allah (33 times), Allah is the Greatest (34 times). (Taught by the Prophet ﷺ to Fatima and ʿAli for bedtime – “better for you than a servant”.)",
    de: "Gepriesen sei Allah (33-mal), Lob sei Allah (33-mal), Allah ist der Größte (34-mal). (Vom Propheten ﷺ Fatima und ʿAli für die Schlafenszeit gelehrt – „besser für euch als ein Diener“.)",
    src: "Sahih al-Bukhari 3705, 6318; Sahih Muslim 2727",
  },
  {
    id: "bismika-rabbi-wadatu", cat: "sleep",
    ar: "بِاسْمِكَ رَبِّ وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
    tr: "Bismika rabbi wadaʿtu janbī, wa bika arfaʿuh, in amsakta nafsī farhamhā, wa in arsaltahā fahfazhā bimā tahfazu bihī ʿibādaka s-sālihīn.",
    en: "In Your name, my Lord, I lay down my side, and by You I raise it. If You take my soul, have mercy on it, and if You release it, protect it as You protect Your righteous servants. (On lying down to sleep.)",
    de: "In Deinem Namen, mein Herr, lege ich mich auf die Seite, und durch Dich erhebe ich mich wieder. Wenn Du meine Seele zurückhältst, so erbarme Dich ihrer, und wenn Du sie freigibst, so beschütze sie, wie Du Deine rechtschaffenen Diener beschützt. (Beim Hinlegen zum Schlafen.)",
    src: "Sahih al-Bukhari 6320; Sahih Muslim 2714",
  },
  {
    id: "atamana-wa-saqana", cat: "sleep",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا، وَكَفَانَا وَآوَانَا، فَكَمْ مِمَّنْ لَا كَافِيَ لَهُ وَلَا مُؤْوِيَ",
    tr: "Al-hamdu lillāhi lladhī atʿamanā wa saqānā, wa kafānā wa āwānā, fa-kam mimman lā kāfiya lahū wa lā muʾwī.",
    en: "Praise be to Allah who has fed us and given us drink, who has sufficed us and given us shelter – for how many have no one to suffice them and no one to shelter them. (On going to bed.)",
    de: "Alles Lob gebührt Allah, der uns zu essen und zu trinken gab, der uns genügte und uns Obdach gewährte – denn wie viele gibt es, die niemanden haben, der ihnen genügt, und niemanden, der ihnen Obdach gibt. (Beim Schlafengehen.)",
    src: "Sahih Muslim 2715",
  },
  {
    id: "khalaqta-nafsi", cat: "sleep",
    ar: "اللَّهُمَّ خَلَقْتَ نَفْسِي وَأَنْتَ تَوَفَّاهَا، لَكَ مَمَاتُهَا وَمَحْيَاهَا، إِنْ أَحْيَيْتَهَا فَاحْفَظْهَا، وَإِنْ أَمَتَّهَا فَاغْفِرْ لَهَا، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ",
    tr: "Allāhumma khalaqta nafsī wa anta tawaffāhā, laka mamātuhā wa mahyāhā, in ahyaytahā fahfazhā, wa in amattahā faghfir lahā. Allāhumma innī asʾaluka l-ʿāfiyah.",
    en: "O Allah, You created my soul and You take it back; its death and its life belong to You. If You keep it alive, protect it, and if You cause it to die, forgive it. O Allah, I ask You for well-being. (On going to bed.)",
    de: "O Allah, Du hast meine Seele erschaffen, und Du nimmst sie zu Dir; Dir gehören ihr Tod und ihr Leben. Wenn Du sie am Leben lässt, so beschütze sie, und wenn Du sie sterben lässt, so vergib ihr. O Allah, ich bitte Dich um Wohlergehen. (Beim Schlafengehen.)",
    src: "Sahih Muslim 2712",
  },
  {
    id: "rabb-as-samawat-sleep", cat: "sleep",
    ar: "اللَّهُمَّ رَبَّ السَّمَاوَاتِ وَرَبَّ الْأَرْضِ وَرَبَّ الْعَرْشِ الْعَظِيمِ، رَبَّنَا وَرَبَّ كُلِّ شَيْءٍ، فَالِقَ الْحَبِّ وَالنَّوَى، وَمُنْزِلَ التَّوْرَاةِ وَالْإِنْجِيلِ وَالْفُرْقَانِ، أَعُوذُ بِكَ مِنْ شَرِّ كُلِّ شَيْءٍ أَنْتَ آخِذٌ بِنَاصِيَتِهِ، اللَّهُمَّ أَنْتَ الْأَوَّلُ فَلَيْسَ قَبْلَكَ شَيْءٌ، وَأَنْتَ الْآخِرُ فَلَيْسَ بَعْدَكَ شَيْءٌ، وَأَنْتَ الظَّاهِرُ فَلَيْسَ فَوْقَكَ شَيْءٌ، وَأَنْتَ الْبَاطِنُ فَلَيْسَ دُونَكَ شَيْءٌ، اقْضِ عَنَّا الدَّيْنَ، وَأَغْنِنَا مِنَ الْفَقْرِ",
    tr: "Allāhumma rabba s-samāwāti wa rabba l-ardi wa rabba l-ʿarshi l-ʿazīm, rabbanā wa rabba kulli shayʾ, fāliqa l-habbi wan-nawā, wa munzila t-tawrāti wal-injīli wal-furqān, aʿūdhu bika min sharri kulli shayʾin anta ākhidhun bi-nāsiyatih. Allāhumma anta l-awwalu fa-laysa qablaka shayʾ, wa anta l-ākhiru fa-laysa baʿdaka shayʾ, wa anta z-zāhiru fa-laysa fawqaka shayʾ, wa anta l-bātinu fa-laysa dūnaka shayʾ, iqdi ʿanna d-dayna wa aghninā mina l-faqr.",
    en: "O Allah, Lord of the heavens, Lord of the earth and Lord of the mighty Throne, our Lord and Lord of all things, Splitter of the grain and the date-stone, Revealer of the Torah, the Gospel and the Criterion: I seek refuge in You from the evil of everything whose forelock You hold. O Allah, You are the First, there is nothing before You; You are the Last, there is nothing after You; You are the Manifest, there is nothing above You; You are the Hidden, there is nothing beyond You. Settle our debt for us and free us from poverty. (On going to bed.)",
    de: "O Allah, Herr der Himmel, Herr der Erde und Herr des gewaltigen Throns, unser Herr und Herr aller Dinge, der Du Korn und Dattelkern spaltest, der Du die Tora, das Evangelium und die Unterscheidung herabgesandt hast: Ich suche Zuflucht bei Dir vor dem Übel jedes Dinges, dessen Stirnlocke Du hältst. O Allah, Du bist der Erste, vor Dir ist nichts; Du bist der Letzte, nach Dir ist nichts; Du bist der Offenbare, über Dir ist nichts; Du bist der Verborgene, jenseits von Dir ist nichts. Begleiche für uns die Schuld und befreie uns von der Armut. (Beim Schlafengehen.)",
    src: "Sahih Muslim 2713",
  },
  {
    id: "waking-at-night", cat: "sleep",
    ar: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، الْحَمْدُ لِلَّهِ، وَسُبْحَانَ اللَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ، اللَّهُمَّ اغْفِرْ لِي",
    tr: "Lā ilāha illā llāhu wahdahū lā sharīka lah, lahu l-mulku wa lahu l-hamd, wa huwa ʿalā kulli shayʾin qadīr. Al-hamdu lillāh, wa subhāna llāh, wa lā ilāha illā llāh, wa llāhu akbar, wa lā hawla wa lā quwwata illā billāh. Allāhumma ghfir lī.",
    en: "There is no god but Allah alone, without partner; His is the dominion and His the praise, and He has power over all things. Praise be to Allah, glory be to Allah, there is no god but Allah, Allah is the Greatest, and there is no might and no power except with Allah. O Allah, forgive me. (On waking up during the night – the supplication is answered, and the prayer that follows is accepted.)",
    de: "Es gibt keinen Gott außer Allah allein, ohne Teilhaber; Sein ist die Herrschaft und Sein das Lob, und Er hat Macht über alle Dinge. Lob sei Allah, gepriesen sei Allah, es gibt keinen Gott außer Allah, Allah ist der Größte, und es gibt keine Macht und keine Kraft außer bei Allah. O Allah, vergib mir. (Beim Aufwachen in der Nacht – das Bittgebet wird erhört, und das anschließende Gebet wird angenommen.)",
    src: "Sahih al-Bukhari 1154",
  },

  // Prayer
  {
    id: "istiftah-baid", cat: "prayer",
    ar: "اللَّهُمَّ بَاعِدْ بَيْنِي وَبَيْنَ خَطَايَايَ كَمَا بَاعَدْتَ بَيْنَ الْمَشْرِقِ وَالْمَغْرِبِ، اللَّهُمَّ نَقِّنِي مِنَ الْخَطَايَا كَمَا يُنَقَّى الثَّوْبُ الْأَبْيَضُ مِنَ الدَّنَسِ، اللَّهُمَّ اغْسِلْ خَطَايَايَ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ",
    tr: "Allāhumma bāʿid baynī wa bayna khatāyāya kamā bāʿadta bayna l-mashriqi wal-maghrib. Allāhumma naqqinī mina l-khatāyā kamā yunaqqa th-thawbu l-abyadu mina d-danas. Allāhumma ghsil khatāyāya bil-māʾi wath-thalji wal-barad.",
    en: "O Allah, set me as far apart from my sins as You have set the east apart from the west. O Allah, cleanse me of sins as a white garment is cleansed of dirt. O Allah, wash away my sins with water, snow and hail. (Opening supplication after the first takbir.)",
    de: "O Allah, entferne mich so weit von meinen Sünden, wie Du den Osten vom Westen entfernt hast. O Allah, reinige mich von den Sünden, wie ein weißes Gewand vom Schmutz gereinigt wird. O Allah, wasche meine Sünden ab mit Wasser, Schnee und Hagel. (Eröffnungsbittgebet nach dem ersten Takbir.)",
    src: "Sahih al-Bukhari 744; Sahih Muslim 598",
  },
  {
    id: "istiftah-subhanaka", cat: "prayer",
    ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ",
    tr: "Subhānaka llāhumma wa bi-hamdik, wa tabāraka smuk, wa taʿālā jadduk, wa lā ilāha ghayruk.",
    en: "Glory be to You, O Allah, and praise be to You. Blessed is Your name, exalted is Your majesty, and there is no god besides You. (Opening supplication of the prayer.)",
    de: "Gepriesen seist Du, o Allah, und Lob sei Dir. Gesegnet ist Dein Name, erhaben ist Deine Majestät, und es gibt keinen Gott außer Dir. (Eröffnungsbittgebet des Gebets.)",
    src: "Sunan Abi Dawud 775; Jamiʿ at-Tirmidhi 243",
  },
  {
    id: "ruku-sujud-tasbih", cat: "prayer",
    ar: "سُبْحَانَ رَبِّيَ الْعَظِيمِ — سُبْحَانَ رَبِّيَ الْأَعْلَى",
    tr: "Subhāna rabbiya l-ʿazīm — Subhāna rabbiya l-aʿlā.",
    en: "Glory be to my Lord, the Magnificent (in bowing). — Glory be to my Lord, the Most High (in prostration).",
    de: "Gepriesen sei mein Herr, der Gewaltige (in der Verbeugung). — Gepriesen sei mein Herr, der Höchste (in der Niederwerfung).",
    src: "Sahih Muslim 772",
  },
  {
    id: "subhanaka-rabbana-ighfir", cat: "prayer",
    ar: "سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ، اللَّهُمَّ اغْفِرْ لِي",
    tr: "Subhānaka llāhumma rabbanā wa bi-hamdik, Allāhumma ghfir lī.",
    en: "Glory be to You, O Allah, our Lord, and praise be to You. O Allah, forgive me. (Often said by the Prophet ﷺ in bowing and prostration.)",
    de: "Gepriesen seist Du, o Allah, unser Herr, und Lob sei Dir. O Allah, vergib mir. (Vom Propheten ﷺ oft in der Verbeugung und Niederwerfung gesprochen.)",
    src: "Sahih al-Bukhari 794; Sahih Muslim 484",
  },
  {
    id: "rabbana-lakal-hamd", cat: "prayer",
    ar: "رَبَّنَا وَلَكَ الْحَمْدُ، حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ",
    tr: "Rabbanā wa laka l-hamd, hamdan kathīran tayyiban mubārakan fīh.",
    en: "Our Lord, and to You belongs all praise – abundant, pure and blessed praise. (On rising from bowing; more than thirty angels hastened to record it.)",
    de: "Unser Herr, und Dir gebührt das Lob – reichliches, reines und gesegnetes Lob. (Beim Aufrichten aus der Verbeugung; mehr als dreißig Engel eilten, es aufzuschreiben.)",
    src: "Sahih al-Bukhari 799",
  },
  {
    id: "sujud-laka-sajadtu", cat: "prayer",
    ar: "اللَّهُمَّ لَكَ سَجَدْتُ، وَبِكَ آمَنْتُ، وَلَكَ أَسْلَمْتُ، سَجَدَ وَجْهِي لِلَّذِي خَلَقَهُ وَصَوَّرَهُ، وَشَقَّ سَمْعَهُ وَبَصَرَهُ، تَبَارَكَ اللَّهُ أَحْسَنُ الْخَالِقِينَ",
    tr: "Allāhumma laka sajadt, wa bika āmant, wa laka aslamt, sajada wajhī lilladhī khalaqahū wa sawwarah, wa shaqqa samʿahū wa basarah, tabāraka llāhu ahsanu l-khāliqīn.",
    en: "O Allah, to You I have prostrated, in You I believe and to You I have submitted. My face prostrates to the One who created it and shaped it and gave it hearing and sight. Blessed is Allah, the best of creators. (In prostration.)",
    de: "O Allah, vor Dir habe ich mich niedergeworfen, an Dich glaube ich, und Dir habe ich mich ergeben. Mein Gesicht wirft sich nieder vor Dem, der es erschaffen und gestaltet und ihm Gehör und Sehkraft gegeben hat. Gesegnet sei Allah, der beste Schöpfer. (In der Niederwerfung.)",
    src: "Sahih Muslim 771",
  },
  {
    id: "sujud-dhanbi-kullahu", cat: "prayer",
    ar: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ",
    tr: "Allāhumma ghfir lī dhanbī kullah, diqqahū wa jillah, wa awwalahū wa ākhirah, wa ʿalāniyatahū wa sirrah.",
    en: "O Allah, forgive me all my sins – the small and the great, the first and the last, the open and the secret. (In prostration.)",
    de: "O Allah, vergib mir alle meine Sünden – die kleinen und die großen, die ersten und die letzten, die offenen und die verborgenen. (In der Niederwerfung.)",
    src: "Sahih Muslim 483",
  },
  {
    id: "sujud-ridaka", cat: "prayer",
    ar: "اللَّهُمَّ أَعُوذُ بِرِضَاكَ مِنْ سَخَطِكَ، وَبِمُعَافَاتِكَ مِنْ عُقُوبَتِكَ، وَأَعُوذُ بِكَ مِنْكَ، لَا أُحْصِي ثَنَاءً عَلَيْكَ، أَنْتَ كَمَا أَثْنَيْتَ عَلَى نَفْسِكَ",
    tr: "Allāhumma aʿūdhu bi-ridāka min sakhatik, wa bi-muʿāfātika min ʿuqūbatik, wa aʿūdhu bika mink, lā uhsī thanāʾan ʿalayk, anta kamā athnayta ʿalā nafsik.",
    en: "O Allah, I seek refuge in Your pleasure from Your anger, in Your forgiveness from Your punishment, and I seek refuge in You from You. I cannot count Your praises; You are as You have praised Yourself. (In prostration.)",
    de: "O Allah, ich suche Zuflucht bei Deinem Wohlgefallen vor Deinem Zorn, bei Deiner Vergebung vor Deiner Strafe, und ich suche Zuflucht bei Dir vor Dir. Ich kann Dein Lob nicht aufzählen; Du bist so, wie Du Dich Selbst gelobt hast. (In der Niederwerfung.)",
    src: "Sahih Muslim 486",
  },
  {
    id: "between-sajdas", cat: "prayer",
    ar: "اللَّهُمَّ اغْفِرْ لِي، وَارْحَمْنِي، وَعَافِنِي، وَاهْدِنِي، وَارْزُقْنِي",
    tr: "Allāhumma ghfir lī, warhamnī, wa ʿāfinī, wahdinī, warzuqnī.",
    en: "O Allah, forgive me, have mercy on me, grant me well-being, guide me and provide for me. (Sitting between the two prostrations.)",
    de: "O Allah, vergib mir, erbarme Dich meiner, schenke mir Wohlergehen, leite mich recht und versorge mich. (Im Sitzen zwischen den beiden Niederwerfungen.)",
    src: "Sunan Abi Dawud 850",
  },
  {
    id: "tashahhud", cat: "prayer",
    ar: "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
    tr: "At-tahiyyātu lillāhi was-salawātu wat-tayyibāt, as-salāmu ʿalayka ayyuha n-nabiyyu wa rahmatu llāhi wa barakātuh, as-salāmu ʿalaynā wa ʿalā ʿibādi llāhi s-sālihīn, ashhadu an lā ilāha illā llāh, wa ashhadu anna Muhammadan ʿabduhū wa rasūluh.",
    en: "All greetings, prayers and good things belong to Allah. Peace be upon you, O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger. (The tashahhud as taught by Ibn Masʿud.)",
    de: "Alle Grüße, Gebete und guten Dinge gebühren Allah. Friede sei mit dir, o Prophet, und die Barmherzigkeit Allahs und Sein Segen. Friede sei mit uns und mit den rechtschaffenen Dienern Allahs. Ich bezeuge, dass es keinen Gott gibt außer Allah, und ich bezeuge, dass Muhammad Sein Diener und Gesandter ist. (Der Taschahhud, wie Ibn Masʿud ihn lehrte.)",
    src: "Sahih al-Bukhari 831; Sahih Muslim 402",
  },
  {
    id: "before-salam-four", cat: "prayer",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ، وَمِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ، وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ",
    tr: "Allāhumma innī aʿūdhu bika min ʿadhābi jahannam, wa min ʿadhābi l-qabr, wa min fitnati l-mahyā wal-mamāt, wa min sharri fitnati l-masīhi d-dajjāl.",
    en: "O Allah, I seek refuge in You from the punishment of Hell, from the punishment of the grave, from the trials of life and death, and from the evil of the trial of the False Messiah. (After the final tashahhud, before the salam.)",
    de: "O Allah, ich suche Zuflucht bei Dir vor der Strafe der Hölle, vor der Strafe des Grabes, vor den Prüfungen des Lebens und des Todes und vor dem Übel der Prüfung durch den falschen Messias. (Nach dem letzten Taschahhud, vor dem Friedensgruß.)",
    src: "Sahih Muslim 588",
  },
  {
    id: "abu-bakr-zalamtu", cat: "prayer",
    ar: "اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ، وَارْحَمْنِي، إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ",
    tr: "Allāhumma innī zalamtu nafsī zulman kathīrā, wa lā yaghfiru dh-dhunūba illā ant, faghfir lī maghfiratan min ʿindik, warhamnī, innaka anta l-ghafūru r-rahīm.",
    en: "O Allah, I have wronged myself greatly, and none forgives sins but You. So forgive me with forgiveness from You and have mercy on me; You are the Forgiving, the Merciful. (Taught to Abu Bakr for his prayer.)",
    de: "O Allah, ich habe mir selbst viel Unrecht getan, und niemand vergibt die Sünden außer Dir. So vergib mir mit Vergebung von Dir und erbarme Dich meiner; Du bist der Vergebende, der Barmherzige. (Abu Bakr für sein Gebet gelehrt.)",
    src: "Sahih al-Bukhari 834; Sahih Muslim 2705",
  },
  {
    id: "ma-qaddamtu", cat: "prayer",
    ar: "اللَّهُمَّ اغْفِرْ لِي مَا قَدَّمْتُ وَمَا أَخَّرْتُ، وَمَا أَسْرَرْتُ وَمَا أَعْلَنْتُ، وَمَا أَسْرَفْتُ، وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي، أَنْتَ الْمُقَدِّمُ وَأَنْتَ الْمُؤَخِّرُ، لَا إِلَهَ إِلَّا أَنْتَ",
    tr: "Allāhumma ghfir lī mā qaddamtu wa mā akhkhart, wa mā asrartu wa mā aʿlant, wa mā asraft, wa mā anta aʿlamu bihī minnī, anta l-muqaddimu wa anta l-muʾakhkhir, lā ilāha illā ant.",
    en: "O Allah, forgive me what I have done before and what I have left for later, what I have hidden and what I have done openly, what I have done in excess, and what You know better than I. You are the One who brings forward and the One who puts back; there is no god but You. (Among the last words between the tashahhud and the salam.)",
    de: "O Allah, vergib mir, was ich früher getan und was ich aufgeschoben habe, was ich verborgen und was ich offen getan habe, worin ich maßlos war und was Du besser weißt als ich. Du bist es, der vorrücken lässt, und Du bist es, der zurückstellt; es gibt keinen Gott außer Dir. (Unter den letzten Worten zwischen Taschahhud und Friedensgruß.)",
    src: "Sahih Muslim 771",
  },
  {
    id: "la-mania", cat: "prayer",
    ar: "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ",
    tr: "Lā ilāha illā llāhu wahdahū lā sharīka lah, lahu l-mulku wa lahu l-hamd, wa huwa ʿalā kulli shayʾin qadīr. Allāhumma lā māniʿa limā aʿtayt, wa lā muʿtiya limā manaʿt, wa lā yanfaʿu dha l-jaddi minka l-jadd.",
    en: "There is no god but Allah alone, without partner; His is the dominion and His the praise, and He has power over all things. O Allah, none can withhold what You give, none can give what You withhold, and the wealth of the wealthy cannot avail him against You. (After every obligatory prayer.)",
    de: "Es gibt keinen Gott außer Allah allein, ohne Teilhaber; Sein ist die Herrschaft und Sein das Lob, und Er hat Macht über alle Dinge. O Allah, niemand kann zurückhalten, was Du gibst, niemand kann geben, was Du zurückhältst, und dem Vermögenden nützt sein Vermögen nichts gegen Dich. (Nach jedem Pflichtgebet.)",
    src: "Sahih al-Bukhari 844; Sahih Muslim 593",
  },
  {
    id: "qunut-witr", cat: "prayer",
    ar: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ، إِنَّكَ تَقْضِي وَلَا يُقْضَى عَلَيْكَ، وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ",
    tr: "Allāhumma hdinī fīman hadayt, wa ʿāfinī fīman ʿāfayt, wa tawallanī fīman tawallayt, wa bārik lī fīmā aʿtayt, wa qinī sharra mā qadayt, innaka taqdī wa lā yuqdā ʿalayk, wa innahū lā yadhillu man wālayt, tabārakta rabbanā wa taʿālayt.",
    en: "O Allah, guide me among those You have guided, grant me well-being among those You have granted well-being, take me into Your care among those You have taken into Your care, bless me in what You have given, and protect me from the evil of what You have decreed. For You decree and none decrees over You, and the one You befriend is never humbled. Blessed are You, our Lord, and exalted. (Qunut in the witr prayer, taught to al-Hasan ibn ʿAli.)",
    de: "O Allah, leite mich recht unter denen, die Du rechtgeleitet hast, schenke mir Wohlergehen unter denen, denen Du Wohlergehen geschenkt hast, nimm mich in Deine Obhut unter denen, die Du in Deine Obhut genommen hast, segne mir, was Du gegeben hast, und bewahre mich vor dem Übel dessen, was Du bestimmt hast. Denn Du bestimmst, und über Dich wird nicht bestimmt, und wen Du zum Freund nimmst, der wird nicht erniedrigt. Gesegnet bist Du, unser Herr, und erhaben. (Qunut im Witr-Gebet, al-Hasan ibn ʿAli gelehrt.)",
    src: "Sunan Abi Dawud 1425; Jamiʿ at-Tirmidhi 464; Sunan an-Nasaʾi 1745",
  },
  {
    id: "istikhara", cat: "prayer",
    ar: "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الْغُيُوبِ، اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي، فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي، ثُمَّ بَارِكْ لِي فِيهِ، وَإِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ شَرٌّ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي، فَاصْرِفْهُ عَنِّي وَاصْرِفْنِي عَنْهُ، وَاقْدُرْ لِيَ الْخَيْرَ حَيْثُ كَانَ، ثُمَّ أَرْضِنِي بِهِ",
    tr: "Allāhumma innī astakhīruka bi-ʿilmik, wa astaqdiruka bi-qudratik, wa asʾaluka min fadlika l-ʿazīm, fa-innaka taqdiru wa lā aqdir, wa taʿlamu wa lā aʿlam, wa anta ʿallāmu l-ghuyūb. Allāhumma in kunta taʿlamu anna hādha l-amra khayrun lī fī dīnī wa maʿāshī wa ʿāqibati amrī, faqdurhu lī wa yassirhu lī, thumma bārik lī fīh. Wa in kunta taʿlamu anna hādha l-amra sharrun lī fī dīnī wa maʿāshī wa ʿāqibati amrī, fasrifhu ʿannī wasrifnī ʿanh, waqdur liya l-khayra haythu kān, thumma ardinī bih.",
    en: "O Allah, I ask You to show me what is best through Your knowledge, I ask You for ability through Your power, and I ask You of Your immense bounty; for You are able and I am not, You know and I do not, and You are the Knower of the unseen. O Allah, if You know that this matter is good for me in my religion, my livelihood and the outcome of my affairs, then decree it for me, make it easy for me and bless me in it. And if You know that this matter is bad for me in my religion, my livelihood and the outcome of my affairs, then turn it away from me and turn me away from it, decree for me the good wherever it may be, and make me content with it. (Istikhara: after two voluntary rakʿas; name your matter at “this matter”. The narrator adds that he may have said “in my present and future affairs” instead of “the outcome of my affairs”.)",
    de: "O Allah, ich bitte Dich durch Dein Wissen, mir das Beste zu zeigen, ich bitte Dich durch Deine Macht um Befähigung, und ich bitte Dich um Deine gewaltige Huld; denn Du vermagst es, und ich vermag es nicht, Du weißt, und ich weiß nicht, und Du bist der Kenner des Verborgenen. O Allah, wenn Du weißt, dass diese Angelegenheit gut für mich ist in meiner Religion, meinem Lebensunterhalt und dem Ausgang meiner Angelegenheiten, so bestimme sie für mich, mache sie mir leicht und segne sie mir. Und wenn Du weißt, dass diese Angelegenheit schlecht für mich ist in meiner Religion, meinem Lebensunterhalt und dem Ausgang meiner Angelegenheiten, so wende sie von mir ab und wende mich von ihr ab, bestimme für mich das Gute, wo immer es ist, und lass mich damit zufrieden sein. (Istichara: nach zwei freiwilligen Gebetseinheiten; bei „diese Angelegenheit“ das Anliegen nennen. Der Überlieferer fügt hinzu, dass vielleicht „in meinen gegenwärtigen und künftigen Angelegenheiten“ statt „dem Ausgang meiner Angelegenheiten“ gesagt wurde.)",
    src: "Sahih al-Bukhari 1162, 6382",
  },
  {
    id: "adhan-shahada", cat: "prayer",
    ar: "وَأَنَا أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، رَضِيتُ بِاللَّهِ رَبًّا، وَبِمُحَمَّدٍ رَسُولًا، وَبِالْإِسْلَامِ دِينًا",
    tr: "Wa ana ashhadu an lā ilāha illā llāhu wahdahū lā sharīka lah, wa anna Muhammadan ʿabduhū wa rasūluh, radītu billāhi rabbā, wa bi-Muhammadin rasūlā, wa bil-islāmi dīnā.",
    en: "And I too bear witness that there is no god but Allah alone, without partner, and that Muhammad is His servant and messenger. I am pleased with Allah as Lord, with Muhammad as messenger and with Islam as religion. (On hearing the muezzin's testimony – his sins are forgiven.)",
    de: "Und auch ich bezeuge, dass es keinen Gott gibt außer Allah allein, ohne Teilhaber, und dass Muhammad Sein Diener und Gesandter ist. Ich bin zufrieden mit Allah als Herrn, mit Muhammad als Gesandtem und mit dem Islam als Religion. (Beim Hören des Glaubenszeugnisses im Gebetsruf – seine Sünden werden vergeben.)",
    src: "Sahih Muslim 386",
  },
  {
    id: "janazah-ighfir-lahu", cat: "prayer",
    ar: "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ، وَعَافِهِ وَاعْفُ عَنْهُ، وَأَكْرِمْ نُزُلَهُ، وَوَسِّعْ مُدْخَلَهُ، وَاغْسِلْهُ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ، وَنَقِّهِ مِنَ الْخَطَايَا كَمَا نَقَّيْتَ الثَّوْبَ الْأَبْيَضَ مِنَ الدَّنَسِ، وَأَبْدِلْهُ دَارًا خَيْرًا مِنْ دَارِهِ، وَأَهْلًا خَيْرًا مِنْ أَهْلِهِ، وَزَوْجًا خَيْرًا مِنْ زَوْجِهِ، وَأَدْخِلْهُ الْجَنَّةَ، وَأَعِذْهُ مِنْ عَذَابِ الْقَبْرِ، أَوْ مِنْ عَذَابِ النَّارِ",
    tr: "Allāhumma ghfir lahū warhamh, wa ʿāfihī waʿfu ʿanh, wa akrim nuzulah, wa wassiʿ mudkhalah, waghsilhu bil-māʾi wath-thalji wal-barad, wa naqqihī mina l-khatāyā kamā naqqayta th-thawba l-abyada mina d-danas, wa abdilhu dāran khayran min dārih, wa ahlan khayran min ahlih, wa zawjan khayran min zawjih, wa adkhilhu l-jannah, wa aʿidhhu min ʿadhābi l-qabr, aw min ʿadhābi n-nār.",
    en: "O Allah, forgive him and have mercy on him, keep him safe and pardon him, honour his reception and widen his resting place. Wash him with water, snow and hail, and cleanse him of sins as You cleanse a white garment of dirt. Give him a home better than his home, a family better than his family and a spouse better than his spouse. Admit him to Paradise and protect him from the punishment of the grave – or: from the punishment of the Fire. (Funeral prayer; the narrator was unsure which of the last two was said. For a woman use the feminine forms: lahā, warhamhā …)",
    de: "O Allah, vergib ihm und erbarme Dich seiner, bewahre ihn und verzeih ihm, bereite ihm eine ehrenvolle Aufnahme und mache seine Ruhestätte weit. Wasche ihn mit Wasser, Schnee und Hagel und reinige ihn von den Sünden, wie Du ein weißes Gewand vom Schmutz reinigst. Gib ihm eine Wohnstätte, die besser ist als seine Wohnstätte, eine Familie, die besser ist als seine Familie, und einen Ehepartner, der besser ist als sein Ehepartner. Lass ihn ins Paradies eintreten und bewahre ihn vor der Strafe des Grabes – oder: vor der Strafe des Feuers. (Totengebet; der Überlieferer war unsicher, welches der beiden zuletzt gesagt wurde. Für eine Frau die weiblichen Formen: lahā, warhamhā …)",
    src: "Sahih Muslim 963",
  },

  // Home and family
  {
    id: "enter-home", cat: "home",
    ar: "بِسْمِ اللَّهِ",
    tr: "Bismi llāh.",
    en: "In the name of Allah. (Mentioning Allah on entering the home and at mealtimes – then Satan says to his companions: “No place to spend the night and no supper for you.”)",
    de: "Im Namen Allahs. (Allahs gedenken beim Betreten des Hauses und beim Essen – dann sagt der Satan zu seinen Gefährten: „Für euch gibt es hier weder Nachtlager noch Abendessen.“)",
    src: "Sahih Muslim 2018",
  },
  {
    id: "leave-home-adilla", cat: "home",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ، أَوْ أَزِلَّ أَوْ أُزَلَّ، أَوْ أَظْلِمَ أَوْ أُظْلَمَ، أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَيَّ",
    tr: "Allāhumma innī aʿūdhu bika an adilla aw udall, aw azilla aw uzall, aw azlima aw uzlam, aw ajhala aw yujhala ʿalayy.",
    en: "O Allah, I seek refuge in You from going astray or being led astray, from slipping or being made to slip, from doing wrong or being wronged, and from acting foolishly or being treated foolishly. (Leaving the house.)",
    de: "O Allah, ich suche Zuflucht bei Dir davor, in die Irre zu gehen oder in die Irre geführt zu werden, zu straucheln oder zum Straucheln gebracht zu werden, Unrecht zu tun oder Unrecht zu erleiden, töricht zu handeln oder töricht behandelt zu werden. (Beim Verlassen des Hauses.)",
    src: "Sunan Abi Dawud 5094; Jamiʿ at-Tirmidhi 3427",
  },
  {
    id: "new-clothes", cat: "home",
    ar: "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ، أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ",
    tr: "Allāhumma laka l-hamdu anta kasawtanīh, asʾaluka min khayrihī wa khayri mā suniʿa lah, wa aʿūdhu bika min sharrihī wa sharri mā suniʿa lah.",
    en: "O Allah, praise be to You; You have clothed me with it. I ask You for its good and the good of what it was made for, and I seek refuge in You from its evil and the evil of what it was made for. (Wearing a new garment.)",
    de: "O Allah, Dir gebührt das Lob; Du hast mich damit bekleidet. Ich bitte Dich um sein Gutes und das Gute dessen, wofür es gemacht wurde, und ich suche Zuflucht bei Dir vor seinem Übel und dem Übel dessen, wofür es gemacht wurde. (Beim Anziehen eines neuen Kleidungsstücks.)",
    src: "Sunan Abi Dawud 4020; Jamiʿ at-Tirmidhi 1767",
  },
  {
    id: "protect-children", cat: "home",
    ar: "أُعِيذُكُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ، مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    tr: "Uʿīdhukumā bi-kalimāti llāhi t-tāmmah, min kulli shaytānin wa hāmmah, wa min kulli ʿaynin lāmmah.",
    en: "I commend you two to the protection of the perfect words of Allah from every devil and every harmful creature, and from every evil eye. (The Prophet ﷺ said this over al-Hasan and al-Husayn; for one child: uʿīdhuka / uʿīdhuki.)",
    de: "Ich stelle euch beide unter den Schutz der vollkommenen Worte Allahs vor jedem Teufel und jedem schädlichen Wesen und vor jedem bösen Blick. (Der Prophet ﷺ sprach dies über al-Hasan und al-Husayn; für ein Kind: uʿīdhuka / uʿīdhuki.)",
    src: "Sahih al-Bukhari 3371",
  },

  // Food and fasting
  {
    id: "after-eating-kathiran", cat: "food",
    ar: "الْحَمْدُ لِلَّهِ كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ، غَيْرَ مَكْفِيٍّ وَلَا مُوَدَّعٍ وَلَا مُسْتَغْنًى عَنْهُ رَبَّنَا",
    tr: "Al-hamdu lillāhi kathīran tayyiban mubārakan fīh, ghayra makfiyyin wa lā muwaddaʿin wa lā mustaghnan ʿanhu rabbanā.",
    en: "Praise be to Allah – abundant, pure and blessed praise; praise that is never sufficient, never abandoned and never dispensed with, our Lord. (When the meal was cleared away.)",
    de: "Alles Lob gebührt Allah – reichliches, reines und gesegnetes Lob; ein Lob, das nie genügt, nie aufgegeben wird und auf das man nie verzichten kann, unser Herr. (Wenn das Essen abgetragen wurde.)",
    src: "Sahih al-Bukhari 5458",
  },
  {
    id: "for-host", cat: "food",
    ar: "اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ، وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ",
    tr: "Allāhumma bārik lahum fīmā razaqtahum, waghfir lahum warhamhum.",
    en: "O Allah, bless them in what You have provided for them, forgive them and have mercy on them. (For the host after a meal.)",
    de: "O Allah, segne ihnen, womit Du sie versorgt hast, vergib ihnen und erbarme Dich ihrer. (Für den Gastgeber nach dem Essen.)",
    src: "Sahih Muslim 2042",
  },
  {
    id: "atim-man-atamani", cat: "food",
    ar: "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي، وَأَسْقِ مَنْ أَسْقَانِي",
    tr: "Allāhumma atʿim man atʿamanī, wa asqi man asqānī.",
    en: "O Allah, feed the one who fed me and give drink to the one who gave me drink.",
    de: "O Allah, gib dem zu essen, der mir zu essen gab, und gib dem zu trinken, der mir zu trinken gab.",
    src: "Sahih Muslim 2055",
  },
  {
    id: "aftara-indakum", cat: "food",
    ar: "أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ، وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ، وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ",
    tr: "Aftara ʿindakumu s-sāʾimūn, wa akala taʿāmakumu l-abrār, wa sallat ʿalaykumu l-malāʾikah.",
    en: "May fasting people break their fast with you, may the righteous eat your food, and may the angels pray for you. (For those who invite you to break the fast.)",
    de: "Mögen Fastende bei euch ihr Fasten brechen, mögen die Rechtschaffenen eure Speise essen, und mögen die Engel für euch beten. (Für die Gastgeber beim Fastenbrechen.)",
    src: "Sunan Abi Dawud 3854",
  },

  // Travel
  {
    id: "travel-return", cat: "travel",
    ar: "آيِبُونَ، تَائِبُونَ، عَابِدُونَ، لِرَبِّنَا حَامِدُونَ",
    tr: "Āyibūna, tāʾibūna, ʿābidūna, li-rabbinā hāmidūn.",
    en: "We return, repenting, worshipping and praising our Lord. (Added to the travel supplication on the way home.)",
    de: "Wir kehren zurück, bereuend, anbetend und unseren Herrn lobend. (Auf dem Heimweg zusätzlich zum Reisebittgebet.)",
    src: "Sahih Muslim 1342; Sahih al-Bukhari 1797",
  },
  {
    id: "farewell-traveller", cat: "travel",
    ar: "أَسْتَوْدِعُ اللَّهَ دِينَكَ، وَأَمَانَتَكَ، وَخَوَاتِيمَ عَمَلِكَ",
    tr: "Astawdiʿu llāha dīnak, wa amānatak, wa khawātīma ʿamalik.",
    en: "I entrust to Allah your religion, your trustworthiness and the final outcomes of your deeds. (When bidding farewell to a traveller.)",
    de: "Ich vertraue Allah deine Religion, deine Treue und den Abschluss deiner Taten an. (Beim Abschied von einem Reisenden.)",
    src: "Sunan Abi Dawud 2600; Jamiʿ at-Tirmidhi 3443",
  },
  {
    id: "talbiyah", cat: "travel",
    ar: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ",
    tr: "Labbayka llāhumma labbayk, labbayka lā sharīka laka labbayk, inna l-hamda wan-niʿmata laka wal-mulk, lā sharīka lak.",
    en: "Here I am, O Allah, here I am. Here I am, You have no partner, here I am. Praise, blessings and dominion belong to You; You have no partner. (Talbiyah during Hajj and ʿUmrah.)",
    de: "Hier bin ich, o Allah, hier bin ich. Hier bin ich, Du hast keinen Teilhaber, hier bin ich. Das Lob, die Gnade und die Herrschaft gehören Dir; Du hast keinen Teilhaber. (Talbiya während Hadsch und ʿUmra.)",
    src: "Sahih al-Bukhari 1549; Sahih Muslim 1184",
  },

  // Forgiveness
  {
    id: "astaghfirullah-wa-atubu", cat: "forgiveness", n: 100,
    ar: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
    tr: "Astaghfiru llāha wa atūbu ilayh.",
    en: "I ask Allah for forgiveness and turn to Him in repentance. (The Prophet ﷺ did so more than seventy times a day; in Muslim's narration: “I repent to Him a hundred times a day.”)",
    de: "Ich bitte Allah um Vergebung und wende mich Ihm reuevoll zu. (Der Prophet ﷺ tat dies mehr als siebzigmal am Tag; in der Überlieferung bei Muslim: „Ich wende mich Ihm hundertmal am Tag reuevoll zu.“)",
    src: "Sahih al-Bukhari 6307; Sahih Muslim 2702",
  },
  {
    id: "astaghfirullah-al-hayy", cat: "forgiveness",
    ar: "أَسْتَغْفِرُ اللَّهَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيَّ الْقَيُّومَ وَأَتُوبُ إِلَيْهِ",
    tr: "Astaghfiru llāha lladhī lā ilāha illā huwa l-hayya l-qayyūma wa atūbu ilayh.",
    en: "I ask forgiveness of Allah, besides whom there is no god, the Ever-Living, the Sustainer of all, and I turn to Him in repentance. (Whoever says it is forgiven, even if he had fled from the battlefield.)",
    de: "Ich bitte Allah um Vergebung, außer dem es keinen Gott gibt, den Lebendigen, den Beständigen, und ich wende mich Ihm reuevoll zu. (Wer dies sagt, dem wird vergeben, selbst wenn er vom Schlachtfeld geflohen ist.)",
    src: "Sunan Abi Dawud 1517; Jamiʿ at-Tirmidhi 3577",
  },
  {
    id: "khatiati-wa-jahli", cat: "forgiveness",
    ar: "اللَّهُمَّ اغْفِرْ لِي خَطِيئَتِي وَجَهْلِي، وَإِسْرَافِي فِي أَمْرِي، وَمَا أَنْتَ أَعْلَمُ بِهِ مِنِّي، اللَّهُمَّ اغْفِرْ لِي جِدِّي وَهَزْلِي، وَخَطَئِي وَعَمْدِي، وَكُلُّ ذَلِكَ عِنْدِي",
    tr: "Allāhumma ghfir lī khatīʾatī wa jahlī, wa isrāfī fī amrī, wa mā anta aʿlamu bihī minnī. Allāhumma ghfir lī jiddī wa hazlī, wa khataʾī wa ʿamdī, wa kullu dhālika ʿindī.",
    en: "O Allah, forgive me my sins and my ignorance, my excess in my affairs, and what You know better than I. O Allah, forgive me what I did in earnest and in jest, by mistake and on purpose – all of that is in me. (Part of a longer supplication of the Prophet ﷺ.)",
    de: "O Allah, vergib mir meine Verfehlungen und meine Unwissenheit, mein Maßlossein in meinen Angelegenheiten und das, was Du besser weißt als ich. O Allah, vergib mir, was ich im Ernst und im Scherz, aus Versehen und mit Absicht getan habe – all das ist bei mir. (Teil eines längeren Bittgebets des Propheten ﷺ.)",
    src: "Sahih Muslim 2719; Sahih al-Bukhari 6398",
  },
  {
    id: "sharri-ma-amiltu", cat: "forgiveness",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ مَا عَمِلْتُ، وَمِنْ شَرِّ مَا لَمْ أَعْمَلْ",
    tr: "Allāhumma innī aʿūdhu bika min sharri mā ʿamilt, wa min sharri mā lam aʿmal.",
    en: "O Allah, I seek refuge in You from the evil of what I have done and from the evil of what I have not done.",
    de: "O Allah, ich suche Zuflucht bei Dir vor dem Übel dessen, was ich getan habe, und vor dem Übel dessen, was ich nicht getan habe.",
    src: "Sahih Muslim 2716",
  },

  // Hardship, illness and loss
  {
    id: "condolence", cat: "hardship",
    ar: "إِنَّ لِلَّهِ مَا أَخَذَ، وَلَهُ مَا أَعْطَى، وَكُلٌّ عِنْدَهُ بِأَجَلٍ مُسَمًّى، فَلْتَصْبِرْ وَلْتَحْتَسِبْ",
    tr: "Inna lillāhi mā akhadh, wa lahū mā aʿtā, wa kullun ʿindahū bi-ajalin musammā, fal-tasbir wal-tahtasib.",
    en: "To Allah belongs what He has taken and to Him belongs what He has given, and everything with Him has an appointed term; so be patient and hope for the reward. (Condolence – the Prophet's ﷺ message to his grieving daughter.)",
    de: "Allah gehört, was Er genommen hat, und Ihm gehört, was Er gegeben hat, und alles hat bei Ihm eine festgesetzte Frist; so sei geduldig und erhoffe den Lohn. (Beileid – die Botschaft des Propheten ﷺ an seine trauernde Tochter.)",
    src: "Sahih al-Bukhari 1284; Sahih Muslim 923",
  },
  {
    id: "ruqya-adhhib-al-bas", cat: "hardship",
    ar: "أَذْهِبِ الْبَاسَ رَبَّ النَّاسِ، اشْفِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    tr: "Adhhibi l-bāsa rabba n-nās, ishfi wa anta sh-shāfī, lā shifāʾa illā shifāʾuk, shifāʾan lā yughādiru saqamā.",
    en: "Remove the harm, Lord of mankind, and heal – You are the Healer. There is no healing but Your healing, a healing that leaves no illness behind. (For someone who is ill.)",
    de: "Nimm das Leiden hinweg, Herr der Menschen, und heile – Du bist der Heilende. Es gibt keine Heilung außer Deiner Heilung, eine Heilung, die keine Krankheit zurücklässt. (Für einen Kranken.)",
    src: "Sahih al-Bukhari 5675; Sahih Muslim 2191",
  },
  {
    id: "asalullah-al-azim", cat: "hardship", n: 7,
    ar: "أَسْأَلُ اللَّهَ الْعَظِيمَ، رَبَّ الْعَرْشِ الْعَظِيمِ، أَنْ يَشْفِيَكَ",
    tr: "Asʾalu llāha l-ʿazīm, rabba l-ʿarshi l-ʿazīm, an yashfiyak.",
    en: "I ask Allah the Mighty, Lord of the mighty Throne, to heal you. (Seven times when visiting a sick person whose time has not yet come.)",
    de: "Ich bitte Allah, den Gewaltigen, den Herrn des gewaltigen Throns, dich zu heilen. (Siebenmal beim Besuch eines Kranken, dessen Frist noch nicht gekommen ist.)",
    src: "Sunan Abi Dawud 3106; Jamiʿ at-Tirmidhi 2083",
  },
  {
    id: "pain", cat: "hardship", n: 7,
    ar: "بِسْمِ اللَّهِ (٣)، أَعُوذُ بِاللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ (٧)",
    tr: "Bismi llāh (3). Aʿūdhu billāhi wa qudratihī min sharri mā ajidu wa uhādhir (7).",
    en: "In the name of Allah (three times). I seek refuge in Allah and His power from the evil of what I feel and what I fear (seven times). (Placing the hand where the body hurts.)",
    de: "Im Namen Allahs (dreimal). Ich suche Zuflucht bei Allah und Seiner Macht vor dem Übel dessen, was ich empfinde und was ich befürchte (siebenmal). (Die Hand auf die schmerzende Stelle legen.)",
    src: "Sahih Muslim 2202",
  },
  {
    id: "ikfini-bihalalik", cat: "hardship",
    ar: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
    tr: "Allāhumma kfinī bi-halālika ʿan harāmik, wa aghninī bi-fadlika ʿamman siwāk.",
    en: "O Allah, suffice me with what You have made lawful against what You have forbidden, and by Your bounty make me independent of all besides You. (For debt – “even if it were like a mountain”.)",
    de: "O Allah, lass mir das von Dir Erlaubte genügen, sodass ich das von Dir Verbotene nicht brauche, und mache mich durch Deine Huld unabhängig von allen außer Dir. (Bei Schulden – „selbst wenn sie so groß wären wie ein Berg“.)",
    src: "Jamiʿ at-Tirmidhi 3563",
  },
  {
    id: "zawal-nimatik", cat: "hardship",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ، وَتَحَوُّلِ عَافِيَتِكَ، وَفُجَاءَةِ نِقْمَتِكَ، وَجَمِيعِ سَخَطِكَ",
    tr: "Allāhumma innī aʿūdhu bika min zawāli niʿmatik, wa tahawwuli ʿāfiyatik, wa fujāʾati niqmatik, wa jamīʿi sakhatik.",
    en: "O Allah, I seek refuge in You from the loss of Your blessings, from the change of the well-being You have granted, from Your sudden punishment and from all that displeases You.",
    de: "O Allah, ich suche Zuflucht bei Dir vor dem Schwinden Deiner Gaben, vor dem Wandel des Wohlergehens, das Du gewährt hast, vor Deiner plötzlichen Strafe und vor allem, was Deinen Unmut erregt.",
    src: "Sahih Muslim 2739",
  },
  {
    id: "qadarullah", cat: "hardship",
    ar: "قَدَرُ اللَّهِ، وَمَا شَاءَ فَعَلَ",
    tr: "Qadaru llāh, wa mā shāʾa faʿal.",
    en: "It is the decree of Allah, and He does what He wills. (When something unwanted happens – instead of saying “if only I had …”.)",
    de: "Es ist Allahs Bestimmung, und Er tut, was Er will. (Wenn etwas Unerwünschtes geschieht – statt zu sagen „hätte ich doch nur …“.)",
    src: "Sahih Muslim 2664",
  },

  // Knowledge, guidance and character
  {
    id: "ati-nafsi-taqwaha", cat: "knowledge",
    ar: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَالْجُبْنِ وَالْبُخْلِ، وَالْهَرَمِ وَعَذَابِ الْقَبْرِ، اللَّهُمَّ آتِ نَفْسِي تَقْوَاهَا، وَزَكِّهَا أَنْتَ خَيْرُ مَنْ زَكَّاهَا، أَنْتَ وَلِيُّهَا وَمَوْلَاهَا، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لَا يَنْفَعُ، وَمِنْ قَلْبٍ لَا يَخْشَعُ، وَمِنْ نَفْسٍ لَا تَشْبَعُ، وَمِنْ دَعْوَةٍ لَا يُسْتَجَابُ لَهَا",
    tr: "Allāhumma innī aʿūdhu bika mina l-ʿajzi wal-kasal, wal-jubni wal-bukhl, wal-harami wa ʿadhābi l-qabr. Allāhumma āti nafsī taqwāhā, wa zakkihā anta khayru man zakkāhā, anta waliyyuhā wa mawlāhā. Allāhumma innī aʿūdhu bika min ʿilmin lā yanfaʿ, wa min qalbin lā yakhshaʿ, wa min nafsin lā tashbaʿ, wa min daʿwatin lā yustajābu lahā.",
    en: "O Allah, I seek refuge in You from incapacity and laziness, from cowardice and miserliness, from decrepit old age and the punishment of the grave. O Allah, give my soul its piety and purify it – You are the best to purify it; You are its Guardian and its Master. O Allah, I seek refuge in You from knowledge that does not benefit, from a heart that is not humble, from a soul that is never satisfied and from a supplication that is not answered.",
    de: "O Allah, ich suche Zuflucht bei Dir vor Unvermögen und Trägheit, vor Feigheit und Geiz, vor hinfälligem Alter und der Strafe des Grabes. O Allah, gib meiner Seele ihre Gottesfurcht und läutere sie – Du bist der Beste, der sie läutert; Du bist ihr Beschützer und ihr Herr. O Allah, ich suche Zuflucht bei Dir vor Wissen, das nicht nützt, vor einem Herzen, das nicht demütig ist, vor einer Seele, die nie satt wird, und vor einem Bittgebet, das nicht erhört wird.",
    src: "Sahih Muslim 2722",
  },
  {
    id: "aslih-li-dini", cat: "knowledge",
    ar: "اللَّهُمَّ أَصْلِحْ لِي دِينِيَ الَّذِي هُوَ عِصْمَةُ أَمْرِي، وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي، وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي، وَاجْعَلِ الْحَيَاةَ زِيَادَةً لِي فِي كُلِّ خَيْرٍ، وَاجْعَلِ الْمَوْتَ رَاحَةً لِي مِنْ كُلِّ شَرٍّ",
    tr: "Allāhumma aslih lī dīniya lladhī huwa ʿismatu amrī, wa aslih lī dunyāya llatī fīhā maʿāshī, wa aslih lī ākhiratī llatī fīhā maʿādī, wajʿali l-hayāta ziyādatan lī fī kulli khayr, wajʿali l-mawta rāhatan lī min kulli sharr.",
    en: "O Allah, set right for me my religion, which is the safeguard of my affairs; set right for me my worldly life, in which is my livelihood; set right for me my Hereafter, to which is my return. Make life an increase for me in every good, and make death a relief for me from every evil.",
    de: "O Allah, bringe mir meine Religion in Ordnung, die der Schutz meiner Angelegenheiten ist; bringe mir mein weltliches Leben in Ordnung, in dem mein Lebensunterhalt liegt; bringe mir mein Jenseits in Ordnung, zu dem meine Rückkehr ist. Mache das Leben für mich zu einer Mehrung in allem Guten und den Tod zu einer Erlösung von allem Übel.",
    src: "Sahih Muslim 2720",
  },
  {
    id: "musarrif-al-qulub", cat: "knowledge",
    ar: "اللَّهُمَّ مُصَرِّفَ الْقُلُوبِ صَرِّفْ قُلُوبَنَا عَلَى طَاعَتِكَ",
    tr: "Allāhumma musarrifa l-qulūbi sarrif qulūbanā ʿalā tāʿatik.",
    en: "O Allah, Director of hearts, direct our hearts to Your obedience.",
    de: "O Allah, der Du die Herzen lenkst, lenke unsere Herzen zum Gehorsam Dir gegenüber.",
    src: "Sahih Muslim 2654",
  },
  {
    id: "ilman-nafia", cat: "knowledge",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا",
    tr: "Allāhumma innī asʾaluka ʿilman nāfiʿā, wa rizqan tayyibā, wa ʿamalan mutaqabbalā.",
    en: "O Allah, I ask You for beneficial knowledge, wholesome provision and accepted deeds. (After the salam of the morning prayer.)",
    de: "O Allah, ich bitte Dich um nützliches Wissen, gute Versorgung und angenommene Taten. (Nach dem Friedensgruß des Morgengebets.)",
    src: "Sunan Ibn Majah 925",
  },
  {
    id: "laka-aslamtu", cat: "knowledge",
    ar: "اللَّهُمَّ لَكَ أَسْلَمْتُ، وَبِكَ آمَنْتُ، وَعَلَيْكَ تَوَكَّلْتُ، وَإِلَيْكَ أَنَبْتُ، وَبِكَ خَاصَمْتُ، اللَّهُمَّ إِنِّي أَعُوذُ بِعِزَّتِكَ، لَا إِلَهَ إِلَّا أَنْتَ، أَنْ تُضِلَّنِي، أَنْتَ الْحَيُّ الَّذِي لَا يَمُوتُ، وَالْجِنُّ وَالْإِنْسُ يَمُوتُونَ",
    tr: "Allāhumma laka aslamt, wa bika āmant, wa ʿalayka tawakkalt, wa ilayka anabt, wa bika khāsamt. Allāhumma innī aʿūdhu bi-ʿizzatik, lā ilāha illā ant, an tudillanī, anta l-hayyu lladhī lā yamūt, wal-jinnu wal-insu yamūtūn.",
    en: "O Allah, to You I have submitted, in You I believe, in You I trust, to You I turn, and for Your sake I contend. O Allah, I seek refuge in Your might – there is no god but You – from Your letting me go astray. You are the Ever-Living who does not die, while jinn and humans die.",
    de: "O Allah, Dir habe ich mich ergeben, an Dich glaube ich, auf Dich vertraue ich, Dir wende ich mich zu, und um Deinetwillen streite ich. O Allah, ich suche Zuflucht bei Deiner Macht – es gibt keinen Gott außer Dir – davor, dass Du mich in die Irre gehen lässt. Du bist der Lebendige, der nicht stirbt, während Dschinn und Menschen sterben.",
    src: "Sahih Muslim 2717",
  },

  // Daily life
  {
    id: "subhanallah-al-azim", cat: "daily",
    ar: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    tr: "Subhāna llāhi wa bi-hamdih, subhāna llāhi l-ʿazīm.",
    en: "Glory be to Allah and praise be to Him; glory be to Allah, the Magnificent. (Two phrases light on the tongue, heavy on the scale and beloved to the Most Merciful.)",
    de: "Gepriesen sei Allah, und Lob sei Ihm; gepriesen sei Allah, der Gewaltige. (Zwei Worte, leicht auf der Zunge, schwer auf der Waage und dem Allerbarmer lieb.)",
    src: "Sahih al-Bukhari 6406; Sahih Muslim 2694",
  },
  {
    id: "four-words", cat: "daily",
    ar: "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ",
    tr: "Subhāna llāh, wal-hamdu lillāh, wa lā ilāha illā llāh, wa llāhu akbar.",
    en: "Glory be to Allah, praise be to Allah, there is no god but Allah, and Allah is the Greatest. (The four words most beloved to Allah.)",
    de: "Gepriesen sei Allah, Lob sei Allah, es gibt keinen Gott außer Allah, und Allah ist der Größte. (Die vier Worte, die Allah am liebsten sind.)",
    src: "Sahih Muslim 2137",
  },
  {
    id: "kaffarat-al-majlis", cat: "daily",
    ar: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
    tr: "Subhānaka llāhumma wa bi-hamdik, ashhadu an lā ilāha illā ant, astaghfiruka wa atūbu ilayk.",
    en: "Glory be to You, O Allah, and praise be to You. I bear witness that there is no god but You; I ask Your forgiveness and turn to You in repentance. (At the end of a gathering – an expiation for what was said in it.)",
    de: "Gepriesen seist Du, o Allah, und Lob sei Dir. Ich bezeuge, dass es keinen Gott gibt außer Dir; ich bitte Dich um Vergebung und wende mich Dir reuevoll zu. (Am Ende einer Zusammenkunft – eine Sühne für das dort Gesagte.)",
    src: "Jamiʿ at-Tirmidhi 3433; Sunan Abi Dawud 4858",
  },
  {
    id: "strong-wind", cat: "daily",
    ar: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا، وَخَيْرَ مَا فِيهَا، وَخَيْرَ مَا أُرْسِلَتْ بِهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا، وَشَرِّ مَا فِيهَا، وَشَرِّ مَا أُرْسِلَتْ بِهِ",
    tr: "Allāhumma innī asʾaluka khayrahā, wa khayra mā fīhā, wa khayra mā ursilat bih, wa aʿūdhu bika min sharrihā, wa sharri mā fīhā, wa sharri mā ursilat bih.",
    en: "O Allah, I ask You for its good, the good within it and the good it was sent with, and I seek refuge in You from its evil, the evil within it and the evil it was sent with. (When a strong wind blows.)",
    de: "O Allah, ich bitte Dich um sein Gutes, das Gute in ihm und das Gute, mit dem er gesandt wurde, und ich suche Zuflucht bei Dir vor seinem Übel, dem Übel in ihm und dem Übel, mit dem er gesandt wurde. (Bei starkem Wind.)",
    src: "Sahih Muslim 899",
  },
  {
    id: "after-rain", cat: "daily",
    ar: "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ",
    tr: "Mutirnā bi-fadli llāhi wa rahmatih.",
    en: "We have been given rain by the bounty of Allah and His mercy. (After rainfall.)",
    de: "Uns wurde Regen gegeben durch die Huld Allahs und Seine Barmherzigkeit. (Nach dem Regen.)",
    src: "Sahih al-Bukhari 846; Sahih Muslim 71",
  },
  {
    id: "hawalayna", cat: "daily",
    ar: "اللَّهُمَّ حَوَالَيْنَا وَلَا عَلَيْنَا، اللَّهُمَّ عَلَى الْآكَامِ وَالظِّرَابِ، وَبُطُونِ الْأَوْدِيَةِ، وَمَنَابِتِ الشَّجَرِ",
    tr: "Allāhumma hawālaynā wa lā ʿalaynā. Allāhumma ʿala l-ākāmi waz-zirāb, wa butūni l-awdiyah, wa manābiti sh-shajar.",
    en: "O Allah, around us and not upon us. O Allah, upon the hills and the high ground, the valley floors and the places where trees grow. (When too much rain causes harm.)",
    de: "O Allah, rings um uns und nicht auf uns. O Allah, auf die Hügel und Anhöhen, in die Täler und auf die Orte, wo Bäume wachsen. (Wenn zu viel Regen Schaden anrichtet.)",
    src: "Sahih al-Bukhari 1014; Sahih Muslim 897",
  },
  {
    id: "visiting-graves", cat: "daily",
    ar: "السَّلَامُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ، وَإِنَّا إِنْ شَاءَ اللَّهُ لَلَاحِقُونَ، أَسْأَلُ اللَّهَ لَنَا وَلَكُمُ الْعَافِيَةَ",
    tr: "As-salāmu ʿalaykum ahla d-diyāri mina l-muʾminīna wal-muslimīn, wa innā in shāʾa llāhu la-lāhiqūn, asʾalu llāha lanā wa lakumu l-ʿāfiyah.",
    en: "Peace be upon you, people of these dwellings, believers and Muslims. We shall, if Allah wills, join you. I ask Allah for well-being for us and for you. (Visiting the graves.)",
    de: "Friede sei mit euch, ihr Bewohner dieser Stätten, Gläubige und Muslime. Wir werden, so Allah will, zu euch stoßen. Ich bitte Allah um Wohlergehen für uns und für euch. (Beim Besuch der Gräber.)",
    src: "Sahih Muslim 975",
  },
  {
    id: "newlywed", cat: "daily",
    ar: "بَارَكَ اللَّهُ لَكَ، وَبَارَكَ عَلَيْكَ، وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ",
    tr: "Bāraka llāhu lak, wa bāraka ʿalayk, wa jamaʿa baynakumā fī khayr.",
    en: "May Allah bless you, shower His blessing upon you and join you both together in goodness. (Congratulating someone on their marriage.)",
    de: "Möge Allah dich segnen, Seinen Segen über dich bringen und euch beide im Guten zusammenführen. (Glückwunsch zur Heirat.)",
    src: "Sunan Abi Dawud 2130; Jamiʿ at-Tirmidhi 1091",
  },
  {
    id: "jazakallah", cat: "daily",
    ar: "جَزَاكَ اللَّهُ خَيْرًا",
    tr: "Jazāka llāhu khayrā.",
    en: "May Allah reward you with good. (When someone does you a favour – whoever says this has praised them fully.)",
    de: "Möge Allah dich mit Gutem belohnen. (Wenn dir jemand einen Gefallen tut – wer dies sagt, hat ihn vollkommen gelobt.)",
    src: "Jamiʿ at-Tirmidhi 2035",
  },
  {
    id: "seeing-afflicted", cat: "daily",
    ar: "الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي مِمَّا ابْتَلَاكَ بِهِ، وَفَضَّلَنِي عَلَى كَثِيرٍ مِمَّنْ خَلَقَ تَفْضِيلًا",
    tr: "Al-hamdu lillāhi lladhī ʿāfānī mimma btalāka bih, wa faddalanī ʿalā kathīrin mimman khalaqa tafdīlā.",
    en: "Praise be to Allah who has spared me what He has tried you with and has greatly favoured me over many of those He created. (On seeing someone in trial – said quietly, so as not to hurt them; he will not be struck by that trial.)",
    de: "Alles Lob gebührt Allah, der mich vor dem bewahrt hat, womit Er dich geprüft hat, und mich vor vielen Seiner Geschöpfe sehr bevorzugt hat. (Beim Anblick eines Geprüften – leise gesprochen, um ihn nicht zu kränken; man wird von dieser Prüfung nicht getroffen.)",
    src: "Jamiʿ at-Tirmidhi 3432",
  },
  {
    id: "akthir-malahu", cat: "daily",
    ar: "اللَّهُمَّ أَكْثِرْ مَالَهُ وَوَلَدَهُ، وَبَارِكْ لَهُ فِيمَا أَعْطَيْتَهُ",
    tr: "Allāhumma akthir mālahū wa waladah, wa bārik lahū fīmā aʿtaytah.",
    en: "O Allah, increase his wealth and his children, and bless him in what You have given him. (The Prophet's ﷺ supplication for Anas at his mother's request – a dua for a child or family member.)",
    de: "O Allah, mehre seinen Besitz und seine Kinder und segne ihm, was Du ihm gegeben hast. (Das Bittgebet des Propheten ﷺ für Anas auf Bitten seiner Mutter – ein Bittgebet für ein Kind oder Familienmitglied.)",
    src: "Sahih al-Bukhari 6334; Sahih Muslim 2480",
  },

  // Blessings on the Prophet ﷺ
  {
    id: "salawat-azwaj", cat: "salawat",
    ar: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَأَزْوَاجِهِ وَذُرِّيَّتِهِ، كَمَا صَلَّيْتَ عَلَى آلِ إِبْرَاهِيمَ، وَبَارِكْ عَلَى مُحَمَّدٍ وَأَزْوَاجِهِ وَذُرِّيَّتِهِ، كَمَا بَارَكْتَ عَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
    tr: "Allāhumma salli ʿalā Muhammadin wa azwājihī wa dhurriyyatih, kamā sallayta ʿalā āli Ibrāhīm, wa bārik ʿalā Muhammadin wa azwājihī wa dhurriyyatih, kamā bārakta ʿalā āli Ibrāhīm, innaka hamīdun majīd.",
    en: "O Allah, send prayers upon Muhammad, his wives and his descendants, as You sent prayers upon the family of Ibrahim, and bless Muhammad, his wives and his descendants, as You blessed the family of Ibrahim; You are Praiseworthy, Glorious.",
    de: "O Allah, segne Muhammad, seine Ehefrauen und seine Nachkommen, wie Du die Familie Ibrahims gesegnet hast, und gib Muhammad, seinen Ehefrauen und seinen Nachkommen Segen, wie Du der Familie Ibrahims Segen gegeben hast; Du bist der Lobenswerte, der Ruhmreiche.",
    src: "Sahih al-Bukhari 3369; Sahih Muslim 407",
  },
  {
    id: "salawat-fil-alamin", cat: "salawat",
    ar: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى آلِ إِبْرَاهِيمَ، وَبَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى آلِ إِبْرَاهِيمَ فِي الْعَالَمِينَ، إِنَّكَ حَمِيدٌ مَجِيدٌ",
    tr: "Allāhumma salli ʿalā Muhammadin wa ʿalā āli Muhammad, kamā sallayta ʿalā āli Ibrāhīm, wa bārik ʿalā Muhammadin wa ʿalā āli Muhammad, kamā bārakta ʿalā āli Ibrāhīma fi l-ʿālamīn, innaka hamīdun majīd.",
    en: "O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon the family of Ibrahim, and bless Muhammad and the family of Muhammad, as You blessed the family of Ibrahim among all the worlds; You are Praiseworthy, Glorious.",
    de: "O Allah, segne Muhammad und die Familie Muhammads, wie Du die Familie Ibrahims gesegnet hast, und gib Muhammad und der Familie Muhammads Segen, wie Du der Familie Ibrahims in allen Welten Segen gegeben hast; Du bist der Lobenswerte, der Ruhmreiche.",
    src: "Sahih Muslim 405",
  },
];
