// Core Quran vocabulary: the most common words, grouped into themed decks.
// Content only; the flashcard UI lives elsewhere.

export type Word = {
  id: string;
  ar: string;
  tr: string;
  root?: string;
  en: string;
  de: string;
  type: "noun" | "verb" | "particle" | "name" | "pronoun" | "adjective";
  ex?: { key: string; ar: string };
};

export type Deck = {
  id: string;
  title_en: string;
  title_de: string;
  desc_en: string;
  desc_de: string;
  words: Word[];
};

type T = Word["type"];

function w(id: string, ar: string, tr: string, root: string | null, en: string, de: string, type: T, ex?: [string, string]): Word {
  const word: Word = { id, ar, tr, en, de, type };
  if (root) word.root = root;
  if (ex) word.ex = { key: ex[0], ar: ex[1] };
  return word;
}

export const VOCAB_DECKS: Deck[] = [
  {
    id: "allah",
    title_en: "Allah and His Names",
    title_de: "Allah und Seine Namen",
    desc_en: "The names and attributes of Allah that appear again and again.",
    desc_de: "Die Namen und Eigenschaften Allahs, die immer wieder vorkommen.",
    words: [
      w("allah-allah", "ٱللَّه", "Allāh", null, "Allah, God", "Allah, Gott", "name", ["112:1", "قُلْ هُوَ اللَّهُ أَحَدٌ"]),
      w("allah-rabb", "رَبّ", "rabb", "ر ب ب", "Lord", "Herr", "noun", ["1:2", "رَبِّ الْعَالَمِينَ"]),
      w("allah-rahman", "رَحْمَٰن", "raḥmān", "ر ح م", "Most Merciful", "Allerbarmer", "name", ["1:3", "الرَّحْمَٰنِ الرَّحِيمِ"]),
      w("allah-rahim", "رَحِيم", "raḥīm", "ر ح م", "Merciful", "Barmherziger", "adjective", ["1:3", "الرَّحْمَٰنِ الرَّحِيمِ"]),
      w("allah-ilah", "إِلَٰه", "ilāh", "أ ل ه", "god, deity", "Gott, Gottheit", "noun", ["2:163", "وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ"]),
      w("allah-alim", "عَلِيم", "ʿalīm", "ع ل م", "All-Knowing", "Allwissender", "adjective", ["2:32", "أَنتَ الْعَلِيمُ الْحَكِيمُ"]),
      w("allah-hakim", "حَكِيم", "ḥakīm", "ح ك م", "All-Wise", "Allweiser", "adjective", ["2:32", "أَنتَ الْعَلِيمُ الْحَكِيمُ"]),
      w("allah-ghafur", "غَفُور", "ghafūr", "غ ف ر", "Forgiving", "Allvergebender", "adjective", ["2:173", "إِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ"]),
      w("allah-azim", "عَظِيم", "ʿaẓīm", "ع ظ م", "Magnificent", "Gewaltiger", "adjective", ["2:255", "وَهُوَ الْعَلِيُّ الْعَظِيمُ"]),
      w("allah-ali", "عَلِيّ", "ʿalī", "ع ل و", "Most High", "Erhabener", "adjective", ["2:255", "وَهُوَ الْعَلِيُّ الْعَظِيمُ"]),
      w("allah-samii", "سَمِيع", "samīʿ", "س م ع", "All-Hearing", "Allhörender", "adjective", ["2:127", "أَنتَ السَّمِيعُ الْعَلِيمُ"]),
      w("allah-basir", "بَصِير", "baṣīr", "ب ص ر", "All-Seeing", "Allsehender", "adjective", ["4:58", "كَانَ سَمِيعًا بَصِيرًا"]),
      w("allah-qadir", "قَدِير", "qadīr", "ق د ر", "All-Powerful", "Allmächtiger", "adjective", ["2:20", "عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ"]),
      w("allah-aziz", "عَزِيز", "ʿazīz", "ع ز ز", "Almighty", "Allmächtiger, Mächtiger", "adjective"),
      w("allah-khabir", "خَبِير", "khabīr", "خ ب ر", "All-Aware", "Allkundiger", "adjective", ["49:13", "إِنَّ اللَّهَ عَلِيمٌ خَبِيرٌ"]),
      w("allah-hayy", "حَيّ", "ḥayy", "ح ي ي", "Ever-Living", "Lebendiger", "adjective", ["2:255", "الْحَيُّ الْقَيُّومُ"]),
      w("allah-qayyum", "قَيُّوم", "qayyūm", "ق و م", "Self-Sustaining", "Beständiger", "adjective", ["2:255", "الْحَيُّ الْقَيُّومُ"]),
      w("allah-malik", "مَلِك", "malik", "م ل ك", "King", "König", "noun", ["114:2", "مَلِكِ النَّاسِ"]),
      w("allah-malik-owner", "مَالِك", "mālik", "م ل ك", "Owner, Master", "Herrscher, Besitzer", "noun", ["1:4", "مَالِكِ يَوْمِ الدِّينِ"]),
      w("allah-ahad", "أَحَد", "aḥad", "أ ح د", "One, anyone", "Einer, jemand", "adjective", ["112:1", "اللَّهُ أَحَدٌ"]),
      w("allah-wahid", "وَاحِد", "wāḥid", "و ح د", "one, single", "einer, einzig", "adjective", ["2:163", "إِلَٰهٌ وَاحِدٌ"]),
      w("allah-samad", "صَمَد", "ṣamad", "ص م د", "Eternal Refuge", "Der Unabhängige", "name", ["112:2", "اللَّهُ الصَّمَدُ"]),
      w("allah-quddus", "قُدُّوس", "quddūs", "ق د س", "Most Holy", "Heiliger", "adjective", ["59:23", "الْمَلِكُ الْقُدُّوسُ"]),
      w("allah-ghani", "غَنِيّ", "ghanī", "غ ن ي", "Self-Sufficient, rich", "Unbedürftiger, reich", "adjective", ["27:40", "فَإِنَّ رَبِّي غَنِيٌّ كَرِيمٌ"]),
      w("allah-wakil", "وَكِيل", "wakīl", "و ك ل", "Trustee, Guardian", "Sachwalter", "noun", ["3:173", "وَنِعْمَ الْوَكِيلُ"]),
    ],
  },
  {
    id: "particles",
    title_en: "Particles in Every Verse",
    title_de: "Partikeln in jedem Vers",
    desc_en: "Small connecting words you meet in almost every verse.",
    desc_de: "Kleine Verbindungswörter, die in fast jedem Vers vorkommen.",
    words: [
      w("particles-wa", "وَ", "wa", null, "and", "und", "particle"),
      w("particles-fa", "فَ", "fa", null, "so, then", "so, dann", "particle"),
      w("particles-min", "مِنْ", "min", null, "from, of", "von, aus", "particle", ["96:2", "مِنْ عَلَقٍ"]),
      w("particles-fi", "فِي", "fī", null, "in", "in", "particle", ["97:1", "فِي لَيْلَةِ الْقَدْرِ"]),
      w("particles-ala", "عَلَىٰ", "ʿalā", null, "on, upon", "auf, über", "particle", ["2:5", "أُولَٰئِكَ عَلَىٰ هُدًى"]),
      w("particles-ila", "إِلَىٰ", "ilā", null, "to, towards", "zu, nach", "particle"),
      w("particles-bi", "بِ", "bi", null, "with, by, in", "mit, durch", "particle"),
      w("particles-li", "لِ", "li", null, "for, to", "für, zu", "particle"),
      w("particles-an-from", "عَنْ", "ʿan", null, "about, from", "über, von", "particle"),
      w("particles-ma", "مَا", "mā", null, "what; not", "was; nicht", "particle", ["96:5", "مَا لَمْ يَعْلَمْ"]),
      w("particles-la", "لَا", "lā", null, "no, not", "nein, nicht", "particle", ["2:2", "لَا رَيْبَ فِيهِ"]),
      w("particles-illa", "إِلَّا", "illā", null, "except", "außer", "particle", ["51:56", "إِلَّا لِيَعْبُدُونِ"]),
      w("particles-inna", "إِنَّ", "inna", null, "indeed, truly", "wahrlich", "particle", ["103:2", "إِنَّ الْإِنسَانَ لَفِي خُسْرٍ"]),
      w("particles-anna", "أَنَّ", "anna", null, "that", "dass", "particle"),
      w("particles-an", "أَنْ", "an", null, "to, that", "dass, zu", "particle"),
      w("particles-in", "إِنْ", "in", null, "if", "wenn, falls", "particle", ["3:31", "قُلْ إِن كُنتُمْ"]),
      w("particles-alladhi", "ٱلَّذِي", "alladhī", null, "who, which (sg.)", "der, welcher", "pronoun", ["96:1", "رَبِّكَ الَّذِي خَلَقَ"]),
      w("particles-alladhina", "ٱلَّذِينَ", "alladhīna", null, "those who", "diejenigen, die", "pronoun", ["2:3", "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ"]),
      w("particles-thumma", "ثُمَّ", "thumma", null, "then, afterwards", "dann, danach", "particle"),
      w("particles-qad", "قَدْ", "qad", null, "indeed, already", "gewiss, bereits", "particle", ["23:1", "قَدْ أَفْلَحَ الْمُؤْمِنُونَ"]),
      w("particles-lam", "لَمْ", "lam", null, "did not", "nicht (Vergangenheit)", "particle", ["112:3", "لَمْ يَلِدْ وَلَمْ يُولَدْ"]),
      w("particles-lan", "لَنْ", "lan", null, "will never", "niemals (Zukunft)", "particle"),
      w("particles-idh", "إِذْ", "idh", null, "when (past)", "als", "particle", ["2:30", "وَإِذْ قَالَ رَبُّكَ"]),
      w("particles-idha", "إِذَا", "idhā", null, "when, if", "wenn", "particle", ["110:1", "إِذَا جَاءَ نَصْرُ اللَّهِ"]),
      w("particles-man", "مَنْ", "man", null, "who, whoever", "wer, wer auch immer", "pronoun", ["99:7", "فَمَن يَعْمَلْ"]),
      w("particles-kull", "كُلّ", "kull", "ك ل ل", "every, all", "jeder, alle", "noun", ["3:185", "كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ"]),
      w("particles-qul", "قُلْ", "qul", "ق و ل", "say! (command)", "sprich!", "verb", ["112:1", "قُلْ هُوَ اللَّهُ أَحَدٌ"]),
    ],
  },
  {
    id: "pronouns",
    title_en: "Pronouns and Pointing Words",
    title_de: "Pronomen und Hinweiswörter",
    desc_en: "He, they, you, we, this, that: the words that tell you who is meant.",
    desc_de: "Er, sie, du, wir, dies, jenes: Wörter, die zeigen, wer gemeint ist.",
    words: [
      w("pronouns-huwa", "هُوَ", "huwa", null, "he, it", "er, es", "pronoun", ["112:1", "قُلْ هُوَ اللَّهُ"]),
      w("pronouns-hiya", "هِيَ", "hiya", null, "she, it", "sie, es", "pronoun"),
      w("pronouns-hum", "هُمْ", "hum", null, "they (m.)", "sie (Plural)", "pronoun", ["2:4", "وَبِالْآخِرَةِ هُمْ يُوقِنُونَ"]),
      w("pronouns-hunna", "هُنَّ", "hunna", null, "they (f.)", "sie (weibl. Plural)", "pronoun"),
      w("pronouns-anta", "أَنتَ", "anta", null, "you (m. sg.)", "du", "pronoun", ["2:32", "إِنَّكَ أَنتَ الْعَلِيمُ"]),
      w("pronouns-anti", "أَنتِ", "anti", null, "you (f. sg.)", "du (weibl.)", "pronoun"),
      w("pronouns-antum", "أَنتُمْ", "antum", null, "you (pl.)", "ihr", "pronoun"),
      w("pronouns-ana", "أَنَا", "anā", null, "I", "ich", "pronoun", ["20:14", "إِنَّنِي أَنَا اللَّهُ"]),
      w("pronouns-nahnu", "نَحْنُ", "naḥnu", null, "we", "wir", "pronoun", ["15:9", "إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ"]),
      w("pronouns-iyyaka", "إِيَّاكَ", "iyyāka", null, "You alone", "Dir allein", "pronoun", ["1:5", "إِيَّاكَ نَعْبُدُ"]),
      w("pronouns-hadha", "هَٰذَا", "hādhā", null, "this (m.)", "dies, dieser", "pronoun"),
      w("pronouns-hadhihi", "هَٰذِهِ", "hādhihī", null, "this (f.)", "diese", "pronoun"),
      w("pronouns-haulai", "هَٰؤُلَاءِ", "hāʾulāʾi", null, "these", "diese (Plural)", "pronoun"),
      w("pronouns-dhalika", "ذَٰلِكَ", "dhālika", null, "that (m.)", "jenes, das", "pronoun", ["2:2", "ذَٰلِكَ الْكِتَابُ"]),
      w("pronouns-tilka", "تِلْكَ", "tilka", null, "that (f.)", "jene", "pronoun", ["12:1", "تِلْكَ آيَاتُ الْكِتَابِ"]),
      w("pronouns-ulaika", "أُولَٰئِكَ", "ulāʾika", null, "those", "jene, diese", "pronoun", ["2:5", "أُولَٰئِكَ عَلَىٰ هُدًى"]),
      w("pronouns-allati", "ٱلَّتِي", "allatī", null, "who, which (f.)", "die, welche", "pronoun", ["2:24", "النَّارَ الَّتِي وَقُودُهَا النَّاسُ"]),
      w("pronouns-ka", "ـكَ", "-ka", null, "you, your (m.)", "dich, dein", "pronoun"),
      w("pronouns-kum", "ـكُمْ", "-kum", null, "you, your (pl.)", "euch, euer", "pronoun", ["109:6", "لَكُمْ دِينُكُمْ"]),
      w("pronouns-hu", "ـهُ", "-hu", null, "him, his", "ihn, sein", "pronoun"),
      w("pronouns-ha", "ـهَا", "-hā", null, "her, its", "sie, ihr", "pronoun"),
      w("pronouns-hum-suffix", "ـهُمْ", "-hum", null, "them, their", "sie, ihr (Plural)", "pronoun"),
      w("pronouns-na", "ـنَا", "-nā", null, "us, our", "uns, unser", "pronoun", ["1:6", "اهْدِنَا الصِّرَاطَ"]),
      w("pronouns-i", "ـي", "-ī", null, "me, my", "mich, mein", "pronoun", ["109:6", "وَلِيَ دِينِ"]),
      w("pronouns-dhu", "ذُو", "dhū", null, "possessor of", "Besitzer von", "noun", ["55:27", "ذُو الْجَلَالِ وَالْإِكْرَامِ"]),
    ],
  },
  {
    id: "faith",
    title_en: "Belief and Faith",
    title_de: "Glaube",
    desc_en: "Faith, disbelief, guidance and the core concepts of religion.",
    desc_de: "Glaube, Unglaube, Rechtleitung und die Grundbegriffe der Religion.",
    words: [
      w("faith-iman", "إِيمَان", "īmān", "أ م ن", "faith, belief", "Glaube", "noun"),
      w("faith-amana", "آمَنَ", "āmana", "أ م ن", "he believed", "glaubte", "verb", ["2:285", "آمَنَ الرَّسُولُ"]),
      w("faith-mumin", "مُؤْمِن", "muʾmin", "أ م ن", "believer", "Gläubiger", "noun", ["23:1", "قَدْ أَفْلَحَ الْمُؤْمِنُونَ"]),
      w("faith-kafara", "كَفَرَ", "kafara", "ك ف ر", "he disbelieved", "war ungläubig", "verb", ["2:6", "إِنَّ الَّذِينَ كَفَرُوا"]),
      w("faith-kufr", "كُفْر", "kufr", "ك ف ر", "disbelief", "Unglaube", "noun"),
      w("faith-kafir", "كَافِر", "kāfir", "ك ف ر", "disbeliever", "Ungläubiger", "noun", ["109:1", "يَا أَيُّهَا الْكَافِرُونَ"]),
      w("faith-islam", "إِسْلَام", "islām", "س ل م", "Islam, submission", "Islam, Hingabe", "noun", ["3:19", "عِندَ اللَّهِ الْإِسْلَامُ"]),
      w("faith-muslim", "مُسْلِم", "muslim", "س ل م", "Muslim, one who submits", "Muslim, Gottergebener", "noun"),
      w("faith-din", "دِين", "dīn", "د ي ن", "religion; judgement", "Religion; Gericht", "noun", ["109:6", "لَكُمْ دِينُكُمْ وَلِيَ دِينِ"]),
      w("faith-taqwa", "تَقْوَىٰ", "taqwā", "و ق ي", "God-consciousness", "Gottesfurcht", "noun", ["2:197", "فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ"]),
      w("faith-muttaqi", "مُتَّقِي", "muttaqī", "و ق ي", "God-fearing person", "Gottesfürchtiger", "noun", ["2:2", "هُدًى لِّلْمُتَّقِينَ"]),
      w("faith-ittaqa", "ٱتَّقَىٰ", "ittaqā", "و ق ي", "he feared (God)", "fürchtete (Gott)", "verb", ["4:1", "اتَّقُوا رَبَّكُمُ"]),
      w("faith-shirk", "شِرْك", "shirk", "ش ر ك", "associating partners", "Beigesellung", "noun", ["31:13", "إِنَّ الشِّرْكَ لَظُلْمٌ عَظِيمٌ"]),
      w("faith-mushrik", "مُشْرِك", "mushrik", "ش ر ك", "idolater", "Götzendiener", "noun"),
      w("faith-huda", "هُدًى", "hudā", "ه د ي", "guidance", "Rechtleitung", "noun", ["2:2", "هُدًى لِّلْمُتَّقِينَ"]),
      w("faith-hada", "هَدَىٰ", "hadā", "ه د ي", "he guided", "leitete recht", "verb", ["1:6", "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ"]),
      w("faith-dalal", "ضَلَال", "ḍalāl", "ض ل ل", "going astray", "Irregehen", "noun"),
      w("faith-ghayb", "غَيْب", "ghayb", "غ ي ب", "the unseen", "das Verborgene", "noun", ["2:3", "يُؤْمِنُونَ بِالْغَيْبِ"]),
      w("faith-kitab", "كِتَاب", "kitāb", "ك ت ب", "book, scripture", "Buch, Schrift", "noun", ["2:2", "ذَٰلِكَ الْكِتَابُ"]),
      w("faith-quran", "قُرْآن", "qurʾān", "ق ر أ", "Quran, recitation", "Koran, Lesung", "noun", ["12:2", "أَنزَلْنَاهُ قُرْآنًا عَرَبِيًّا"]),
      w("faith-aya", "آيَة", "āya", "أ ي ي", "sign, verse", "Zeichen, Vers", "noun", ["12:1", "تِلْكَ آيَاتُ الْكِتَابِ"]),
      w("faith-zulm", "ظُلْم", "ẓulm", "ظ ل م", "wrongdoing, injustice", "Unrecht", "noun", ["31:13", "لَظُلْمٌ عَظِيمٌ"]),
      w("faith-zalim", "ظَالِم", "ẓālim", "ظ ل م", "wrongdoer", "Ungerechter", "noun"),
      w("faith-sirat", "صِرَاط", "ṣirāṭ", "ص ر ط", "path, way", "Weg", "noun", ["1:6", "اهْدِنَا الصِّرَاطَ"]),
      w("faith-sabil", "سَبِيل", "sabīl", "س ب ل", "way, path", "Weg", "noun"),
    ],
  },
  {
    id: "people",
    title_en: "People and Creation",
    title_de: "Menschen und Geschöpfe",
    desc_en: "Humans, prophets, angels, jinn and family.",
    desc_de: "Menschen, Propheten, Engel, Dschinn und Familie.",
    words: [
      w("people-nas", "نَاس", "nās", "ن و س", "people, mankind", "Menschen", "noun", ["114:1", "بِرَبِّ النَّاسِ"]),
      w("people-insan", "إِنسَان", "insān", "أ ن س", "human being", "Mensch", "noun", ["103:2", "إِنَّ الْإِنسَانَ لَفِي خُسْرٍ"]),
      w("people-qawm", "قَوْم", "qawm", "ق و م", "people, nation", "Volk, Leute", "noun"),
      w("people-rasul", "رَسُول", "rasūl", "ر س ل", "messenger", "Gesandter", "noun", ["48:29", "مُّحَمَّدٌ رَّسُولُ اللَّهِ"]),
      w("people-nabi", "نَبِيّ", "nabī", "ن ب أ", "prophet", "Prophet", "noun", ["33:40", "وَخَاتَمَ النَّبِيِّينَ"]),
      w("people-malak", "مَلَك", "malak", "م ل ك", "angel", "Engel", "noun", ["97:4", "تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ"]),
      w("people-jinn", "جِنّ", "jinn", "ج ن ن", "jinn", "Dschinn", "noun", ["51:56", "وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ"]),
      w("people-abd", "عَبْد", "ʿabd", "ع ب د", "servant, slave", "Diener", "noun", ["18:1", "أَنزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ"]),
      w("people-nafs", "نَفْس", "nafs", "ن ف س", "soul, self", "Seele, Selbst", "noun", ["3:185", "كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ"]),
      w("people-qalb", "قَلْب", "qalb", "ق ل ب", "heart", "Herz", "noun", ["13:28", "تَطْمَئِنُّ الْقُلُوبُ"]),
      w("people-ab", "أَب", "ab", "أ ب و", "father", "Vater", "noun", ["33:40", "أَبَا أَحَدٍ"]),
      w("people-umm", "أُمّ", "umm", "أ م م", "mother", "Mutter", "noun"),
      w("people-ibn", "ٱبْن", "ibn", "ب ن ي", "son", "Sohn", "noun"),
      w("people-akh", "أَخ", "akh", "أ خ و", "brother", "Bruder", "noun", ["80:34", "يَفِرُّ الْمَرْءُ مِنْ أَخِيهِ"]),
      w("people-zawj", "زَوْج", "zawj", "ز و ج", "spouse, pair", "Ehepartner, Paar", "noun", ["2:35", "أَنتَ وَزَوْجُكَ الْجَنَّةَ"]),
      w("people-imraa", "ٱمْرَأَة", "imraʾa", "م ر أ", "woman, wife", "Frau, Ehefrau", "noun"),
      w("people-rajul", "رَجُل", "rajul", "ر ج ل", "man", "Mann", "noun"),
      w("people-nisa", "نِسَاء", "nisāʾ", "ن س و", "women", "Frauen", "noun"),
      w("people-shaytan", "شَيْطَان", "shayṭān", "ش ط ن", "Satan, devil", "Satan, Teufel", "noun"),
      w("people-adam", "آدَم", "Ādam", null, "Adam", "Adam", "name", ["2:31", "وَعَلَّمَ آدَمَ الْأَسْمَاءَ"]),
      w("people-musa", "مُوسَىٰ", "Mūsā", null, "Moses", "Moses", "name"),
      w("people-ibrahim", "إِبْرَاهِيم", "Ibrāhīm", null, "Abraham", "Abraham", "name"),
      w("people-isa", "عِيسَىٰ", "ʿĪsā", null, "Jesus", "Jesus", "name"),
      w("people-muhammad", "مُحَمَّد", "Muḥammad", "ح م د", "Muhammad", "Muhammad", "name", ["48:29", "مُّحَمَّدٌ رَّسُولُ اللَّهِ"]),
      w("people-ahl", "أَهْل", "ahl", "أ ه ل", "family, people of", "Familie, Leute", "noun"),
    ],
  },
  {
    id: "nature",
    title_en: "The World and Nature",
    title_de: "Welt und Natur",
    desc_en: "Earth, sky, sun, moon, water and the signs in creation.",
    desc_de: "Erde, Himmel, Sonne, Mond, Wasser und die Zeichen der Schöpfung.",
    words: [
      w("nature-ard", "أَرْض", "arḍ", "أ ر ض", "earth, land", "Erde, Land", "noun", ["91:6", "وَالْأَرْضِ وَمَا طَحَاهَا"]),
      w("nature-sama", "سَمَاء", "samāʾ", "س م و", "sky, heaven", "Himmel", "noun", ["91:5", "وَالسَّمَاءِ وَمَا بَنَاهَا"]),
      w("nature-samawat", "سَمَاوَات", "samāwāt", "س م و", "heavens", "Himmel (Plural)", "noun", ["6:1", "خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ"]),
      w("nature-shams", "شَمْس", "shams", "ش م س", "sun", "Sonne", "noun", ["91:1", "وَالشَّمْسِ وَضُحَاهَا"]),
      w("nature-qamar", "قَمَر", "qamar", "ق م ر", "moon", "Mond", "noun", ["91:2", "وَالْقَمَرِ إِذَا تَلَاهَا"]),
      w("nature-ma", "مَاء", "māʾ", "م و ه", "water", "Wasser", "noun", ["21:30", "مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ"]),
      w("nature-layl", "لَيْل", "layl", "ل ي ل", "night", "Nacht", "noun", ["92:1", "وَاللَّيْلِ إِذَا يَغْشَىٰ"]),
      w("nature-nahar", "نَهَار", "nahār", "ن ه ر", "day(time)", "Tag", "noun", ["91:3", "وَالنَّهَارِ إِذَا جَلَّاهَا"]),
      w("nature-bahr", "بَحْر", "baḥr", "ب ح ر", "sea", "Meer", "noun"),
      w("nature-jabal", "جَبَل", "jabal", "ج ب ل", "mountain", "Berg", "noun", ["78:7", "وَالْجِبَالَ أَوْتَادًا"]),
      w("nature-nahr", "نَهْر", "nahr", "ن ه ر", "river", "Fluss", "noun", ["2:25", "تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ"]),
      w("nature-nur", "نُور", "nūr", "ن و ر", "light", "Licht", "noun", ["24:35", "اللَّهُ نُورُ السَّمَاوَاتِ"]),
      w("nature-zulumat", "ظُلُمَات", "ẓulumāt", "ظ ل م", "darkness(es)", "Finsternisse", "noun"),
      w("nature-rih", "رِيح", "rīḥ", "ر و ح", "wind", "Wind", "noun"),
      w("nature-matar", "مَطَر", "maṭar", "م ط ر", "rain", "Regen", "noun"),
      w("nature-shajara", "شَجَرَة", "shajara", "ش ج ر", "tree", "Baum", "noun"),
      w("nature-thamarat", "ثَمَرَات", "thamarāt", "ث م ر", "fruits", "Früchte", "noun"),
      w("nature-hijara", "حِجَارَة", "ḥijāra", "ح ج ر", "stones", "Steine", "noun", ["2:24", "وَقُودُهَا النَّاسُ وَالْحِجَارَةُ"]),
      w("nature-dabba", "دَابَّة", "dābba", "د ب ب", "living creature", "Lebewesen, Tier", "noun"),
      w("nature-anam", "أَنْعَام", "anʿām", "ن ع م", "livestock", "Vieh", "noun"),
      w("nature-fulk", "فُلْك", "fulk", null, "ship(s)", "Schiff(e)", "noun", ["2:164", "وَالْفُلْكِ الَّتِي تَجْرِي فِي الْبَحْرِ"]),
      w("nature-shay", "شَيْء", "shayʾ", "ش ي أ", "thing", "Ding, Sache", "noun", ["2:20", "عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ"]),
      w("nature-alamin", "عَالَمِين", "ʿālamīn", "ع ل م", "the worlds", "die Welten", "noun", ["1:2", "رَبِّ الْعَالَمِينَ"]),
      w("nature-dunya", "دُنْيَا", "dunyā", "د ن و", "this world", "Diesseits", "noun", ["2:201", "آتِنَا فِي الدُّنْيَا حَسَنَةً"]),
      w("nature-hayat", "حَيَاة", "ḥayāh", "ح ي ي", "life", "Leben", "noun", ["67:2", "خَلَقَ الْمَوْتَ وَالْحَيَاةَ"]),
    ],
  },
  {
    id: "hereafter",
    title_en: "The Hereafter",
    title_de: "Das Jenseits",
    desc_en: "The Day of Judgement, Paradise, Hell, reward and reckoning.",
    desc_de: "Der Tag des Gerichts, Paradies, Hölle, Lohn und Abrechnung.",
    words: [
      w("hereafter-yawm", "يَوْم", "yawm", "ي و م", "day", "Tag", "noun", ["1:4", "مَالِكِ يَوْمِ الدِّينِ"]),
      w("hereafter-akhira", "آخِرَة", "ākhira", "أ خ ر", "the Hereafter", "das Jenseits", "noun", ["2:4", "وَبِالْآخِرَةِ هُمْ يُوقِنُونَ"]),
      w("hereafter-janna", "جَنَّة", "janna", "ج ن ن", "garden, Paradise", "Garten, Paradies", "noun", ["2:82", "أُولَٰئِكَ أَصْحَابُ الْجَنَّةِ"]),
      w("hereafter-nar", "نَار", "nār", "ن و ر", "fire, Hellfire", "Feuer, Höllenfeuer", "noun", ["2:201", "وَقِنَا عَذَابَ النَّارِ"]),
      w("hereafter-jahannam", "جَهَنَّم", "jahannam", null, "Hell", "Hölle", "name"),
      w("hereafter-adhab", "عَذَاب", "ʿadhāb", "ع ذ ب", "punishment", "Strafe, Pein", "noun", ["2:7", "وَلَهُمْ عَذَابٌ عَظِيمٌ"]),
      w("hereafter-ajr", "أَجْر", "ajr", "أ ج ر", "reward", "Lohn", "noun", ["2:62", "فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ"]),
      w("hereafter-hisab", "حِسَاب", "ḥisāb", "ح س ب", "reckoning", "Abrechnung", "noun", ["2:202", "وَاللَّهُ سَرِيعُ الْحِسَابِ"]),
      w("hereafter-qiyama", "قِيَامَة", "qiyāma", "ق و م", "resurrection", "Auferstehung", "noun", ["75:1", "لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ"]),
      w("hereafter-sa-a", "سَاعَة", "sāʿa", "س و ع", "the Hour; hour", "die Stunde", "noun"),
      w("hereafter-mawt", "مَوْت", "mawt", "م و ت", "death", "Tod", "noun", ["3:185", "ذَائِقَةُ الْمَوْتِ"]),
      w("hereafter-khalid", "خَالِد", "khālid", "خ ل د", "abiding forever", "ewig verweilend", "adjective", ["2:82", "هُمْ فِيهَا خَالِدُونَ"]),
      w("hereafter-ashab", "أَصْحَاب", "aṣḥāb", "ص ح ب", "companions, people of", "Gefährten, Bewohner", "noun", ["2:39", "أُولَٰئِكَ أَصْحَابُ النَّارِ"]),
      w("hereafter-jaza", "جَزَاء", "jazāʾ", "ج ز ي", "recompense", "Vergeltung", "noun"),
      w("hereafter-thawab", "ثَوَاب", "thawāb", "ث و ب", "reward", "Belohnung", "noun"),
      w("hereafter-maghfira", "مَغْفِرَة", "maghfira", "غ ف ر", "forgiveness", "Vergebung", "noun"),
      w("hereafter-rahma", "رَحْمَة", "raḥma", "ر ح م", "mercy", "Barmherzigkeit", "noun"),
      w("hereafter-wayl", "وَيْل", "wayl", null, "woe", "Wehe", "noun", ["104:1", "وَيْلٌ لِّكُلِّ هُمَزَةٍ"]),
      w("hereafter-khusr", "خُسْر", "khusr", "خ س ر", "loss", "Verlust", "noun", ["103:2", "لَفِي خُسْرٍ"]),
      w("hereafter-falaha", "أَفْلَحَ", "aflaḥa", "ف ل ح", "he succeeded", "erlangte Erfolg", "verb", ["23:1", "قَدْ أَفْلَحَ الْمُؤْمِنُونَ"]),
      w("hereafter-wad", "وَعْد", "waʿd", "و ع د", "promise", "Versprechen", "noun", ["19:54", "كَانَ صَادِقَ الْوَعْدِ"]),
      w("hereafter-raji", "رَاجِع", "rājiʿ", "ر ج ع", "returning", "zurückkehrend", "adjective", ["2:156", "وَإِنَّا إِلَيْهِ رَاجِعُونَ"]),
      w("hereafter-maqam", "مَقَام", "maqām", "ق و م", "station, standing", "Stellung, Standort", "noun"),
      w("hereafter-ruh", "رُوح", "rūḥ", "ر و ح", "spirit, soul", "Geist", "noun", ["97:4", "الْمَلَائِكَةُ وَالرُّوحُ"]),
      w("hereafter-salam", "سَلَام", "salām", "س ل م", "peace", "Frieden", "noun", ["36:58", "سَلَامٌ قَوْلًا"]),
    ],
  },
  {
    id: "verbs",
    title_en: "Common Verbs",
    title_de: "Häufige Verben",
    desc_en: "Say, be, make, know, do, see, come: the verbs that drive the story.",
    desc_de: "Sagen, sein, machen, wissen, tun, sehen, kommen: die tragenden Verben.",
    words: [
      w("verbs-qala", "قَالَ", "qāla", "ق و ل", "he said", "sagte", "verb", ["2:30", "وَإِذْ قَالَ رَبُّكَ"]),
      w("verbs-kana", "كَانَ", "kāna", "ك و ن", "he was", "war", "verb", ["4:58", "كَانَ سَمِيعًا بَصِيرًا"]),
      w("verbs-jaala", "جَعَلَ", "jaʿala", "ج ع ل", "he made, placed", "machte, setzte", "verb", ["21:30", "وَجَعَلْنَا مِنَ الْمَاءِ"]),
      w("verbs-alima", "عَلِمَ", "ʿalima", "ع ل م", "he knew", "wusste", "verb", ["96:5", "مَا لَمْ يَعْلَمْ"]),
      w("verbs-allama", "عَلَّمَ", "ʿallama", "ع ل م", "he taught", "lehrte", "verb", ["96:5", "عَلَّمَ الْإِنسَانَ"]),
      w("verbs-amila", "عَمِلَ", "ʿamila", "ع م ل", "he did, worked", "tat, wirkte", "verb", ["103:3", "وَعَمِلُوا الصَّالِحَاتِ"]),
      w("verbs-raa", "رَأَىٰ", "raʾā", "ر أ ي", "he saw", "sah", "verb", ["99:7", "خَيْرًا يَرَهُ"]),
      w("verbs-jaa", "جَاءَ", "jāʾa", "ج ي أ", "he came", "kam", "verb", ["110:1", "إِذَا جَاءَ نَصْرُ اللَّهِ"]),
      w("verbs-ata", "أَتَىٰ", "atā", "أ ت ي", "he came", "kam", "verb"),
      w("verbs-ata-give", "آتَىٰ", "ātā", "أ ت ي", "he gave", "gab", "verb", ["2:201", "رَبَّنَا آتِنَا"]),
      w("verbs-khalaqa", "خَلَقَ", "khalaqa", "خ ل ق", "he created", "erschuf", "verb", ["96:1", "رَبِّكَ الَّذِي خَلَقَ"]),
      w("verbs-shaa", "شَاءَ", "shāʾa", "ش ي أ", "he willed", "wollte", "verb"),
      w("verbs-arada", "أَرَادَ", "arāda", "ر و د", "he wanted", "wollte, beabsichtigte", "verb", ["36:82", "إِذَا أَرَادَ شَيْئًا"]),
      w("verbs-anzala", "أَنزَلَ", "anzala", "ن ز ل", "he sent down", "sandte herab", "verb", ["97:1", "إِنَّا أَنزَلْنَاهُ"]),
      w("verbs-arsala", "أَرْسَلَ", "arsala", "ر س ل", "he sent", "sandte", "verb"),
      w("verbs-dhakara", "ذَكَرَ", "dhakara", "ذ ك ر", "he remembered", "gedachte", "verb", ["2:152", "فَاذْكُرُونِي أَذْكُرْكُمْ"]),
      w("verbs-ittabaa", "ٱتَّبَعَ", "ittabaʿa", "ت ب ع", "he followed", "folgte", "verb", ["3:31", "فَاتَّبِعُونِي"]),
      w("verbs-ahabba", "أَحَبَّ", "aḥabba", "ح ب ب", "he loved", "liebte", "verb", ["2:222", "إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ"]),
      w("verbs-ghafara", "غَفَرَ", "ghafara", "غ ف ر", "he forgave", "vergab", "verb", ["4:48", "إِنَّ اللَّهَ لَا يَغْفِرُ"]),
      w("verbs-dakhala", "دَخَلَ", "dakhala", "د خ ل", "he entered", "trat ein", "verb"),
      w("verbs-kharaja", "خَرَجَ", "kharaja", "خ ر ج", "he went out", "ging hinaus", "verb"),
      w("verbs-sami-a", "سَمِعَ", "samiʿa", "س م ع", "he heard", "hörte", "verb"),
      w("verbs-kataba", "كَتَبَ", "kataba", "ك ت ب", "he wrote, prescribed", "schrieb, schrieb vor", "verb", ["2:183", "كُتِبَ عَلَيْكُمُ الصِّيَامُ"]),
      w("verbs-qaraa", "قَرَأَ", "qaraʾa", "ق ر أ", "he read, recited", "las, rezitierte", "verb", ["96:1", "اقْرَأْ بِاسْمِ رَبِّكَ"]),
      w("verbs-zalama", "ظَلَمَ", "ẓalama", "ظ ل م", "he wronged", "tat Unrecht", "verb", ["7:23", "رَبَّنَا ظَلَمْنَا أَنفُسَنَا"]),
      w("verbs-kun", "كُنْ", "kun", "ك و ن", "be! (command)", "sei!", "verb", ["36:82", "كُن فَيَكُونُ"]),
    ],
  },
  {
    id: "worship",
    title_en: "Worship and Deeds",
    title_de: "Gottesdienst und Taten",
    desc_en: "Prayer, charity, patience, remembrance and good and bad deeds.",
    desc_de: "Gebet, Almosen, Geduld, Gedenken sowie gute und schlechte Taten.",
    words: [
      w("worship-salah", "صَلَاة", "ṣalāh", "ص ل و", "prayer", "Gebet", "noun", ["2:43", "وَأَقِيمُوا الصَّلَاةَ"]),
      w("worship-zakah", "زَكَاة", "zakāh", "ز ك و", "obligatory charity", "Pflichtabgabe", "noun", ["2:43", "وَآتُوا الزَّكَاةَ"]),
      w("worship-sabr", "صَبْر", "ṣabr", "ص ب ر", "patience", "Geduld", "noun", ["103:3", "وَتَوَاصَوْا بِالصَّبْرِ"]),
      w("worship-sabir", "صَابِر", "ṣābir", "ص ب ر", "patient one", "Geduldiger", "noun", ["2:153", "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ"]),
      w("worship-shukr", "شُكْر", "shukr", "ش ك ر", "gratitude", "Dankbarkeit", "noun"),
      w("worship-shakara", "شَكَرَ", "shakara", "ش ك ر", "he thanked", "dankte", "verb", ["14:7", "لَئِن شَكَرْتُمْ"]),
      w("worship-dhikr", "ذِكْر", "dhikr", "ذ ك ر", "remembrance", "Gedenken", "noun", ["13:28", "أَلَا بِذِكْرِ اللَّهِ"]),
      w("worship-dua", "دُعَاء", "duʿāʾ", "د ع و", "supplication", "Bittgebet", "noun"),
      w("worship-daa", "دَعَا", "daʿā", "د ع و", "he called, prayed", "rief, bat", "verb", ["40:60", "ادْعُونِي أَسْتَجِبْ لَكُمْ"]),
      w("worship-sawm", "صَوْم", "ṣawm", "ص و م", "fasting", "Fasten", "noun"),
      w("worship-siyam", "صِيَام", "ṣiyām", "ص و م", "fasting", "Fasten", "noun", ["2:183", "كُتِبَ عَلَيْكُمُ الصِّيَامُ"]),
      w("worship-hajj", "حَجّ", "ḥajj", "ح ج ج", "pilgrimage", "Pilgerfahrt", "noun", ["2:197", "الْحَجُّ أَشْهُرٌ مَّعْلُومَاتٌ"]),
      w("worship-khayr", "خَيْر", "khayr", "خ ي ر", "good; better", "Gutes; besser", "noun", ["99:7", "مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ"]),
      w("worship-sharr", "شَرّ", "sharr", "ش ر ر", "evil, harm", "Böses, Übel", "noun", ["99:8", "مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ"]),
      w("worship-abada", "عَبَدَ", "ʿabada", "ع ب د", "he worshipped", "diente, betete an", "verb", ["1:5", "إِيَّاكَ نَعْبُدُ"]),
      w("worship-ibada", "عِبَادَة", "ʿibāda", "ع ب د", "worship", "Anbetung, Gottesdienst", "noun"),
      w("worship-hamd", "حَمْد", "ḥamd", "ح م د", "praise", "Lob", "noun", ["1:2", "الْحَمْدُ لِلَّهِ"]),
      w("worship-subhan", "سُبْحَان", "subḥān", "س ب ح", "glory be to", "gepriesen sei", "noun", ["17:1", "سُبْحَانَ الَّذِي أَسْرَىٰ"]),
      w("worship-sabbaha", "سَبَّحَ", "sabbaḥa", "س ب ح", "he glorified", "pries", "verb", ["87:1", "سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى"]),
      w("worship-tawba", "تَوْبَة", "tawba", "ت و ب", "repentance", "Reue, Umkehr", "noun"),
      w("worship-sadaqa", "صَدَقَة", "ṣadaqa", "ص د ق", "charity", "Almosen", "noun"),
      w("worship-anfaqa", "أَنفَقَ", "anfaqa", "ن ف ق", "he spent (in charity)", "gab aus", "verb"),
      w("worship-salihat", "صَالِحَات", "ṣāliḥāt", "ص ل ح", "righteous deeds", "gute Werke", "noun", ["103:3", "وَعَمِلُوا الصَّالِحَاتِ"]),
      w("worship-amal", "عَمَل", "ʿamal", "ع م ل", "deed, work", "Tat, Werk", "noun"),
      w("worship-masjid", "مَسْجِد", "masjid", "س ج د", "mosque", "Moschee", "noun"),
      w("worship-sajada", "سَجَدَ", "sajada", "س ج د", "he prostrated", "warf sich nieder", "verb"),
    ],
  },
  {
    id: "qualities",
    title_en: "Describing Words and Qualities",
    title_de: "Eigenschaften und Beschreibungen",
    desc_en: "Great, true, clear, noble, many, few: words that describe.",
    desc_de: "Groß, wahr, deutlich, edel, viel, wenig: beschreibende Wörter.",
    words: [
      w("qualities-kabir", "كَبِير", "kabīr", "ك ب ر", "great, big", "groß", "adjective", ["22:62", "هُوَ الْعَلِيُّ الْكَبِيرُ"]),
      w("qualities-akbar", "أَكْبَر", "akbar", "ك ب ر", "greater, greatest", "größer, am größten", "adjective"),
      w("qualities-saghir", "صَغِير", "ṣaghīr", "ص غ ر", "small", "klein", "adjective"),
      w("qualities-haqq", "حَقّ", "ḥaqq", "ح ق ق", "truth; true", "Wahrheit; wahr", "noun", ["17:81", "جَاءَ الْحَقُّ وَزَهَقَ الْبَاطِلُ"]),
      w("qualities-batil", "بَاطِل", "bāṭil", "ب ط ل", "falsehood", "Falschheit", "noun", ["17:81", "وَزَهَقَ الْبَاطِلُ"]),
      w("qualities-sadiq", "صَادِق", "ṣādiq", "ص د ق", "truthful", "wahrhaftig", "adjective", ["19:54", "كَانَ صَادِقَ الْوَعْدِ"]),
      w("qualities-mubin", "مُبِين", "mubīn", "ب ي ن", "clear", "deutlich, klar", "adjective", ["12:1", "آيَاتُ الْكِتَابِ الْمُبِينِ"]),
      w("qualities-karim", "كَرِيم", "karīm", "ك ر م", "noble, generous", "edel, großzügig", "adjective", ["82:6", "بِرَبِّكَ الْكَرِيمِ"]),
      w("qualities-akram", "أَكْرَم", "akram", "ك ر م", "most generous, noblest", "edelster, großzügigster", "adjective", ["96:3", "وَرَبُّكَ الْأَكْرَمُ"]),
      w("qualities-mustaqim", "مُسْتَقِيم", "mustaqīm", "ق و م", "straight", "gerade", "adjective", ["1:6", "الصِّرَاطَ الْمُسْتَقِيمَ"]),
      w("qualities-kathir", "كَثِير", "kathīr", "ك ث ر", "many, much", "viel", "adjective", ["33:41", "ذِكْرًا كَثِيرًا"]),
      w("qualities-qalil", "قَلِيل", "qalīl", "ق ل ل", "few, little", "wenig", "adjective", ["2:249", "مِّن فِئَةٍ قَلِيلَةٍ"]),
      w("qualities-alim-pain", "أَلِيم", "alīm", "أ ل م", "painful", "schmerzhaft", "adjective"),
      w("qualities-hasan", "حَسَن", "ḥasan", "ح س ن", "good, beautiful", "gut, schön", "adjective"),
      w("qualities-ahsan", "أَحْسَن", "aḥsan", "ح س ن", "best, most beautiful", "beste, schönste", "adjective", ["95:4", "فِي أَحْسَنِ تَقْوِيمٍ"]),
      w("qualities-hasana", "حَسَنَة", "ḥasana", "ح س ن", "good deed, good", "gute Tat, Gutes", "noun", ["2:201", "فِي الدُّنْيَا حَسَنَةً"]),
      w("qualities-sayyia", "سَيِّئَة", "sayyiʾa", "س و أ", "bad deed", "schlechte Tat", "noun"),
      w("qualities-qarib", "قَرِيب", "qarīb", "ق ر ب", "near", "nahe", "adjective", ["2:186", "فَإِنِّي قَرِيبٌ"]),
      w("qualities-aqrab", "أَقْرَب", "aqrab", "ق ر ب", "nearer, closest", "näher", "adjective", ["50:16", "وَنَحْنُ أَقْرَبُ إِلَيْهِ"]),
      w("qualities-baid", "بَعِيد", "baʿīd", "ب ع د", "far", "fern, weit", "adjective"),
      w("qualities-awwal", "أَوَّل", "awwal", "أ و ل", "first", "Erster", "adjective", ["57:3", "هُوَ الْأَوَّلُ وَالْآخِرُ"]),
      w("qualities-akhir", "آخِر", "ākhir", "أ خ ر", "last", "Letzter", "adjective", ["57:3", "هُوَ الْأَوَّلُ وَالْآخِرُ"]),
      w("qualities-aala", "أَعْلَىٰ", "aʿlā", "ع ل و", "most high", "höchster", "adjective", ["87:1", "اسْمَ رَبِّكَ الْأَعْلَى"]),
      w("qualities-daif", "ضَعِيف", "ḍaʿīf", "ض ع ف", "weak", "schwach", "adjective", ["4:28", "وَخُلِقَ الْإِنسَانُ ضَعِيفًا"]),
      w("qualities-shadid", "شَدِيد", "shadīd", "ش د د", "severe, strong", "streng, heftig", "adjective"),
      w("qualities-khalis", "خَالِص", "khāliṣ", "خ ل ص", "pure, sincere", "rein, aufrichtig", "adjective"),
    ],
  },
];
