// "Secrets of the Quran" (/secrets): verified counts, popular claims checked, facts with sources, what is promised to
// those who read the Quran, and places of peace. German, English and Arabic; other languages fall back to English.
// Counts come from lib/secrets/counts.ts (computed from the full Uthmani text, method stated on the page).
export type Verdict = "true" | "false" | "method";
export type SecretsContent = {
  kicker: string; title: string; lead: string;
  counterTitle: string; counterLead: string; method: string; times: string; spots: string; open: string; allahNote: string;
  words: { key: string; ar: string; label: string }[];
  claimsTitle: string; claimsLead: string; verdicts: Record<Verdict, string>;
  claims: { q: string; v: Verdict; a: string; key?: string }[];
  factsTitle: string; facts: { ar: string; title: string; body: string; src: string }[];
  readTitle: string; readLead: string; hadith: { text: string; src: string }[];
  wealthTitle: string; wealthLead: string; promises: { ref: string; title: string; text: string }[]; wealthNote: string; wealthHadith: { text: string; src: string };
  placesTitle: string; placesLead: string; places: { ar: string; title: string; body: string; src: string; href?: string }[];
  note: string; ctaTitle: string; ctaBody: string; cta: string;
};

const de: SecretsContent = {
  kicker: "Geprüft, nicht geraten",
  title: "Die Geheimnisse des Quran",
  lead: "Über den Quran kursieren viele Zahlen und „Wunder“ – manche stimmen, manche nicht. Hier zählen wir selbst nach, im vollständigen Uthmani-Text, und sagen offen, was belegt ist. Dazu: was dem verheißen ist, der den Quran liest, und wo das Herz am leichtesten Frieden findet.",
  counterTitle: "Wie oft steht das im Quran?",
  counterLead: "Tippe auf ein Wort. Du siehst, wie oft es vorkommt – und jede einzelne Stelle, direkt zum Nachlesen.",
  method: "Gezählt im Uthmani-Text des König-Fahd-Komplexes in Madinah (6.236 Verse, Zählung nach Hafs). Gezählt werden Wortformen mit Artikel und vorangestellten Partikeln (wa-, fa-, bi-, li-, ka-), ohne angehängte Pronomen; bei Namen auch mit dem Ruf „yā“. Andere Zählweisen können zu etwas anderen Zahlen kommen – deshalb nennen wir die Methode.",
  times: "mal", spots: "Stellen", open: "Öffnen", allahNote: "Bei „Allah“ zeigen wir nur die Zahl – die Stellen wären zu viele für eine Liste.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "„Hab keine Angst“" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "„Keine Furcht über ihnen“" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "Der Allerbarmer" },
    { key: "yawm", ar: "يَوْم", label: "Tag" },
    { key: "shahr", ar: "شَهْر", label: "Monat" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "Diesseits" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "Jenseits" },
    { key: "musa", ar: "مُوسَىٰ", label: "Musa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nuh" },
    { key: "yusuf", ar: "يُوسُف", label: "Yusuf" },
    { key: "isa", ar: "عِيسَىٰ", label: "Isa" },
    { key: "adam", ar: "ءَادَم", label: "Adam" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Verbreitete Behauptungen – nachgezählt",
  claimsLead: "Was in sozialen Medien geteilt wird, ist oft gut gemeint. Aber der Quran braucht keine erfundenen Zahlen. Wir haben jede Aussage selbst geprüft.",
  verdicts: { true: "Stimmt", false: "Stimmt so nicht", method: "Stimmt – mit dieser Zählweise" },
  claims: [
    { q: "„Hab keine Angst“ steht 365-mal im Quran – für jeden Tag des Jahres einmal.", v: "false", key: "fearNot", a: "Als direkte Aufforderung – „lā takhaf“, „lā takhāfī“, „lā takhāfū“, „lā takhāfā“ – kommt es 13-mal vor: gesprochen zu Ibrahim, zu Musa und Harun, zur Mutter von Musa, zu Lut, zu Dawud und zu den Gläubigen. Dazu kommt 13-mal die Zusage „keine Furcht soll über ihnen sein, und sie werden nicht traurig sein“. Zusammen 26 Stellen – weniger als behauptet, aber jede einzelne ein Trost." },
    { q: "Das Wort „Tag“ steht 365-mal im Quran.", v: "method", key: "yawm", a: "Zählt man die Einzahl „yaum“ und „yauman“ – mit Artikel und Partikeln, aber ohne angehängte Pronomen und ohne „yaumaʾidhin“ (an jenem Tag) –, sind es genau 365 Stellen. Mit anderen Zählweisen kommt man auf andere Zahlen. Bemerkenswert bleibt es." },
    { q: "Das Wort „Monat“ steht 12-mal im Quran.", v: "true", key: "shahr", a: "In der Einzahl („shahr“, „ash-shahr“, „shahran“) sind es 12 Stellen. Und der Quran sagt selbst: „Die Zahl der Monate bei Allah ist zwölf“ (9:36)." },
    { q: "„Diesseits“ und „Jenseits“ stehen gleich oft – je 115-mal.", v: "method", key: "dunya", a: "Mit Artikel und Partikeln gezählt: ad-dunyā 115-mal, al-ākhira 115-mal. Nicht mitgezählt ist 3:72, wo „ākhirahu“ „sein Ende“ (des Tages) bedeutet und nicht das Jenseits." },
    { q: "Der Name „Allah“ steht 2.699-mal im Quran.", v: "true", key: "allah", a: "Mit allen Vorsilben wie wallāhi, billāhi, lillāhi gezählt sind es 2.699 Stellen (ohne „Allāhumma“). Das deckt sich mit den bekannten Zählungen." },
    { q: "Musa ist der am häufigsten genannte Prophet.", v: "true", key: "musa", a: "Musa wird 136-mal mit Namen genannt – häufiger als jeder andere Prophet. Es folgen Ibrahim (69), Nuh (43), Yusuf (27), Isa und Adam (je 25)." },
    { q: "Maryam ist die einzige Frau, die im Quran mit Namen genannt wird.", v: "true", key: "maryam", a: "Ja. Ihr Name steht 34-mal im Quran, und eine ganze Sure trägt ihren Namen: Sure 19, Maryam." },
    { q: "Der Prophet Muhammad ﷺ wird nur viermal mit Namen genannt.", v: "true", key: "muhammad", a: "Viermal als „Muhammad“ (3:144, 33:40, 47:2, 48:29) und einmal als „Ahmad“ (61:6) – an vielen anderen Stellen spricht Allah ihn an als „O Prophet“ und „O Gesandter“." },
  ],
  factsTitle: "Was wirklich erstaunt – mit Quelle",
  facts: [
    { ar: "الفاتحة", title: "Die größte Sure", body: "Der Prophet ﷺ nannte Al-Fātiḥa die größte Sure des Quran und „die sieben oft Wiederholten“ – sie wird in jeder Gebetseinheit rezitiert.", src: "Sahih al-Bukhari 4474" },
    { ar: "آية الكرسي", title: "Der größte Vers", body: "Āyat al-Kursī (2:255) ist der gewaltigste Vers im Buch Allahs – so lehrte es der Prophet ﷺ seinen Gefährten Ubayy ibn Kaʿb.", src: "Sahih Muslim 810" },
    { ar: "الإخلاص", title: "Ein Drittel des Quran", body: "Sure Al-Ikhlāṣ (112) kommt einem Drittel des Quran gleich – vier kurze Verse über die Einheit Allahs.", src: "Sahih al-Bukhari 5013" },
    { ar: "اقرأ", title: "Das erste Wort", body: "Die erste Offenbarung in der Höhle Ḥirāʾ beginnt mit „Lies!“ (96:1–5). Der Quran beginnt seine Herabsendung mit Wissen.", src: "Sahih al-Bukhari 3" },
    { ar: "البسملة", title: "114 Basmalas", body: "„Bismillāh ar-Raḥmān ar-Raḥīm“ steht am Anfang von 113 Suren – alle außer At-Tauba – und einmal mitten in einer Sure: im Brief Sulaimans an die Königin von Saba (27:30). Zusammen 114, so viele wie Suren.", src: "Quran 27:30" },
    { ar: "الدَّين", title: "Der längste Vers", body: "Der längste Vers ist der „Vers der Schuld“ (2:282): Er regelt, wie man Schulden schriftlich festhält – ein Zeichen, wie ernst der Quran Gerechtigkeit im Alltag nimmt.", src: "Quran 2:282" },
    { ar: "الكوثر", title: "Die kürzeste Sure", body: "Al-Kauthar (108) hat drei Verse und zehn Wörter. Die längste Sure, Al-Baqara, hat 286 Verse.", src: "Quran 108, 2" },
    { ar: "١١٤", title: "114 Suren, 6.236 Verse", body: "Der Quran hat 114 Suren und 6.236 Verse (Zählung nach Hafs), aufgeteilt in 30 Teile. In unserem Text sind es 77.429 Wörter – je nach Zählweise nennen andere leicht abweichende Zahlen.", src: "Uthmani-Text, König-Fahd-Komplex" },
  ],
  readTitle: "Wer den Quran liest – was ihm verheißen ist",
  readLead: "Der Quran ist kein Buch, das man einmal liest und weglegt. Diese Worte des Propheten ﷺ sind authentisch überliefert:",
  hadith: [
    { text: "„Wer einen Buchstaben aus dem Buch Allahs liest, dem wird eine gute Tat angerechnet, und die gute Tat zählt zehnfach. Ich sage nicht, Alif-Lām-Mīm ist ein Buchstabe – sondern Alif ist ein Buchstabe, Lām ist ein Buchstabe und Mīm ist ein Buchstabe.“", src: "at-Tirmidhi 2910" },
    { text: "„Lest den Quran, denn er wird am Tag der Auferstehung als Fürsprecher für die kommen, die ihn gelesen haben.“", src: "Sahih Muslim 804" },
    { text: "„Der Beste unter euch ist, wer den Quran lernt und ihn lehrt.“", src: "Sahih al-Bukhari 5027" },
    { text: "„Wer den Quran gut beherrscht, ist bei den edlen, gehorsamen Schreibern. Und wer ihn liest und dabei stockt, weil es ihm schwerfällt, bekommt doppelten Lohn.“", src: "Sahih al-Bukhari 4937, Sahih Muslim 798" },
    { text: "„Zu dem, der mit dem Quran lebte, wird gesagt: Lies und steige empor, und trage vor, wie du in der Welt vorgetragen hast – dein Rang ist beim letzten Vers, den du liest.“", src: "Abu Dawud 1464, at-Tirmidhi 2914" },
  ],
  wealthTitle: "Segen, Versorgung, Wohlstand",
  wealthLead: "Der Quran verspricht keine Formel für schnelles Geld. Er verspricht etwas Größeres: Barakah – Segen, der in wenig viel sein lässt –, ein gutes Leben und Versorgung von dort, wo man sie nicht erwartet. Das sind seine eigenen Worte (sinngemäß):",
  promises: [
    { ref: "71:10-12", title: "Um Vergebung bitten", text: "„Bittet euren Herrn um Vergebung – Er ist allvergebend. Dann schickt Er euch reichlich Regen, stärkt euch mit Besitz und Kindern und gibt euch Gärten und Flüsse.“" },
    { ref: "14:7", title: "Dankbarkeit", text: "„Wenn ihr dankbar seid, werde Ich euch ganz gewiss noch mehr geben.“" },
    { ref: "65:2-3", title: "Gottesfurcht und Vertrauen", text: "„Wer Allah fürchtet, dem schafft Er einen Ausweg und versorgt ihn, von wo er es nicht erwartet. Und wer auf Allah vertraut, dem genügt Er.“" },
    { ref: "7:96", title: "Segen für ganze Städte", text: "„Hätten die Bewohner der Städte geglaubt und wären sie gottesfürchtig gewesen, hätten Wir ihnen Segnungen vom Himmel und von der Erde eröffnet.“" },
    { ref: "16:97", title: "Ein gutes Leben", text: "„Wer Gutes tut, ob Mann oder Frau, und dabei gläubig ist, dem werden Wir ein gutes Leben geben.“" },
    { ref: "35:29-30", title: "Ein Handel, der nicht verliert", text: "„Diejenigen, die das Buch Allahs verlesen, das Gebet verrichten und von dem ausgeben, womit Wir sie versorgt haben, hoffen auf einen Handel, der niemals zugrunde geht.“" },
    { ref: "13:28", title: "Ruhe für das Herz", text: "„Gewiss, im Gedenken Allahs finden die Herzen Ruhe.“" },
    { ref: "17:82", title: "Heilung", text: "„Wir senden vom Quran herab, was Heilung und Barmherzigkeit ist für die Gläubigen.“" },
  ],
  wealthNote: "Wer viel Quran liest, wird also nicht „automatisch“ reich – aber er wird reich an dem, was bleibt: Ruhe, Dankbarkeit, Vertrauen und Lohn, der nicht aufhört. Und wer seine Arbeit ehrlich tut, Dank sagt und um Vergebung bittet, darf auf Allahs Versorgung hoffen.",
  wealthHadith: { text: "„Reichtum ist nicht die Menge des Besitzes, sondern Reichtum ist der Reichtum der Seele.“", src: "Sahih al-Bukhari 6446, Sahih Muslim 1051" },
  placesTitle: "Orte, an denen das Herz Frieden findet",
  placesLead: "Frieden mit Allah kann man überall finden – Er ist nahe. Aber es gibt Orte und Zeiten, die Er besonders gesegnet hat.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masdschid al-Harām, Mekka", body: "Das Haus Allahs, die Kaaba, die Richtung jedes Gebets. Ein Gebet dort zählt mehr als hunderttausend Gebete an anderen Orten.", src: "Ibn Madscha 1406 (von Gelehrten als authentisch eingestuft)" },
    { ar: "المسجد النبوي", title: "Die Moschee des Propheten, Medina", body: "Ein Gebet dort ist besser als tausend an anderen Orten – außer der Heiligen Moschee. Und zwischen seinem Haus und seiner Kanzel liegt „ein Garten von den Gärten des Paradieses“.", src: "Sahih al-Bukhari 1190, 1196; Sahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masdschid al-Aqsā, Jerusalem", body: "Die erste Gebetsrichtung, deren Umgebung Allah gesegnet hat (17:1) – eine der drei Moscheen, zu denen man eigens reist.", src: "Sahih al-Bukhari 1189, Sahih Muslim 1397" },
    { ar: "بيوت الله", title: "Jede Moschee", body: "Die liebsten Orte bei Allah sind die Moscheen. Und wo Menschen sich dort versammeln, den Quran lesen und miteinander lernen, kommt Ruhe (Sakīna) auf sie herab, Barmherzigkeit umhüllt sie und Engel umgeben sie.", src: "Sahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Dein Zuhause", body: "„Macht eure Häuser nicht zu Friedhöfen. Der Satan flieht aus dem Haus, in dem Sure Al-Baqara gelesen wird.“ Ein fester Platz für dein tägliches Lesen macht dein Zuhause zu einem Ort des Friedens.", src: "Sahih Muslim 780" },
    { ar: "الثلث الأخير", title: "Das letzte Drittel der Nacht", body: "Ein Ort in der Zeit: Allah ruft im letzten Drittel jeder Nacht: „Wer ruft Mich an, dass Ich ihm antworte? Wer bittet Mich, dass Ich ihm gebe?“", src: "Sahih al-Bukhari 1145, Sahih Muslim 758" },
    { ar: "آيات الكون", title: "In der Schöpfung", body: "„In der Schöpfung der Himmel und der Erde und im Wechsel von Nacht und Tag sind Zeichen für die Verständigen“ – die Allah gedenken, im Stehen, Sitzen und Liegen (3:190–191).", src: "Quran 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "In den Emiraten", body: "Die Scheich-Zayed-Moschee in Abu Dhabi, die Jumeirah-Moschee in Dubai und die großen Moscheen in Sharjah heißen Besucher willkommen – Orte der Stille mitten im Leben.", src: "", href: "/islam/mosques" },
  ],
  note: "Die Hadithe sind mit Sammlung und Nummer angegeben. Die Verse sind sinngemäß wiedergegeben; den arabischen Wortlaut und eine anerkannte Übersetzung findest du mit einem Tipp auf die Stellenangabe. Bei Fragen zu Urteilen wende dich an einen Gelehrten.",
  ctaTitle: "Lass es nicht beim Staunen",
  ctaBody: "Jeder Buchstabe zählt zehnfach. Beginne heute mit einem Vers – die Shams-Methode führt dich Schritt für Schritt.",
  cta: "Ersten Vers lernen",
};

const en: SecretsContent = {
  kicker: "Checked, not guessed",
  title: "The Secrets of the Quran",
  lead: "Many numbers and “miracles” about the Quran are shared – some are true, some are not. Here we count for ourselves, in the complete Uthmani text, and say openly what is established. Plus: what is promised to those who read the Quran, and where the heart most easily finds peace.",
  counterTitle: "How often does it appear in the Quran?",
  counterLead: "Tap a word. You see how often it occurs – and every single place, ready to read.",
  method: "Counted in the Uthmani text of the King Fahd Complex in Madinah (6,236 verses, Hafs count). Word forms are counted with the article and prefixed particles (wa-, fa-, bi-, li-, ka-), without attached pronouns; names also with the vocative “yā”. Other ways of counting can give slightly different numbers – that is why we state the method.",
  times: "times", spots: "places", open: "Open", allahNote: "For “Allah” we only show the number – the places would be too many for a list.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "“Do not fear”" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "“No fear upon them”" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "The Most Merciful" },
    { key: "yawm", ar: "يَوْم", label: "Day" },
    { key: "shahr", ar: "شَهْر", label: "Month" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "This world" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "The Hereafter" },
    { key: "musa", ar: "مُوسَىٰ", label: "Musa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nuh" },
    { key: "yusuf", ar: "يُوسُف", label: "Yusuf" },
    { key: "isa", ar: "عِيسَىٰ", label: "Isa" },
    { key: "adam", ar: "ءَادَم", label: "Adam" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Popular claims – counted again",
  claimsLead: "What is shared on social media is often well meant. But the Quran needs no invented numbers. We checked every statement ourselves.",
  verdicts: { true: "True", false: "Not quite", method: "True – with this way of counting" },
  claims: [
    { q: "“Do not fear” appears 365 times in the Quran – once for every day of the year.", v: "false", key: "fearNot", a: "As a direct command – “lā takhaf”, “lā takhāfī”, “lā takhāfū”, “lā takhāfā” – it occurs 13 times: said to Ibrahim, to Musa and Harun, to the mother of Musa, to Lut, to Dawud and to the believers. In addition, 13 times comes the promise “no fear shall be upon them, nor shall they grieve”. 26 places together – fewer than claimed, but every one of them a comfort." },
    { q: "The word “day” appears 365 times in the Quran.", v: "method", key: "yawm", a: "Counting the singular “yawm” and “yawman” – with article and particles, but without attached pronouns and without “yawma’idhin” (on that day) – gives exactly 365 places. Other ways of counting give other numbers. It remains remarkable." },
    { q: "The word “month” appears 12 times in the Quran.", v: "true", key: "shahr", a: "In the singular (“shahr”, “ash-shahr”, “shahran”) there are 12 places. And the Quran itself says: “The number of months with Allah is twelve” (9:36)." },
    { q: "“This world” and “the Hereafter” appear equally often – 115 times each.", v: "method", key: "dunya", a: "Counted with article and particles: ad-dunyā 115 times, al-ākhira 115 times. Not counted is 3:72, where “ākhirahu” means “its end” (of the day), not the Hereafter." },
    { q: "The name “Allah” appears 2,699 times in the Quran.", v: "true", key: "allah", a: "Counted with all prefixes such as wallāhi, billāhi, lillāhi, there are 2,699 places (without “Allāhumma”). This matches the well-known counts." },
    { q: "Musa is the most mentioned prophet.", v: "true", key: "musa", a: "Musa is named 136 times – more than any other prophet. Then come Ibrahim (69), Nuh (43), Yusuf (27), Isa and Adam (25 each)." },
    { q: "Maryam is the only woman mentioned by name in the Quran.", v: "true", key: "maryam", a: "Yes. Her name appears 34 times, and a whole surah bears her name: surah 19, Maryam." },
    { q: "The Prophet Muhammad ﷺ is mentioned by name only four times.", v: "true", key: "muhammad", a: "Four times as “Muhammad” (3:144, 33:40, 47:2, 48:29) and once as “Ahmad” (61:6) – in many other places Allah addresses him as “O Prophet” and “O Messenger”." },
  ],
  factsTitle: "What truly amazes – with sources",
  facts: [
    { ar: "الفاتحة", title: "The greatest surah", body: "The Prophet ﷺ called Al-Fātiḥa the greatest surah of the Quran and “the seven oft-repeated” – it is recited in every unit of prayer.", src: "Sahih al-Bukhari 4474" },
    { ar: "آية الكرسي", title: "The greatest verse", body: "Āyat al-Kursī (2:255) is the greatest verse in the Book of Allah – so the Prophet ﷺ taught his companion Ubayy ibn Ka‘b.", src: "Sahih Muslim 810" },
    { ar: "الإخلاص", title: "A third of the Quran", body: "Surah Al-Ikhlāṣ (112) equals a third of the Quran – four short verses on the oneness of Allah.", src: "Sahih al-Bukhari 5013" },
    { ar: "اقرأ", title: "The first word", body: "The first revelation in the cave of Ḥirā’ begins with “Read!” (96:1–5). The Quran begins its descent with knowledge.", src: "Sahih al-Bukhari 3" },
    { ar: "البسملة", title: "114 basmalas", body: "“Bismillāh ar-Raḥmān ar-Raḥīm” stands at the beginning of 113 surahs – all except At-Tawbah – and once inside a surah: in Sulayman’s letter to the Queen of Sheba (27:30). 114 together, as many as there are surahs.", src: "Quran 27:30" },
    { ar: "الدَّين", title: "The longest verse", body: "The longest verse is the “verse of debt” (2:282): it sets out how to record debts in writing – a sign of how seriously the Quran takes justice in daily life.", src: "Quran 2:282" },
    { ar: "الكوثر", title: "The shortest surah", body: "Al-Kawthar (108) has three verses and ten words. The longest surah, Al-Baqarah, has 286 verses.", src: "Quran 108, 2" },
    { ar: "١١٤", title: "114 surahs, 6,236 verses", body: "The Quran has 114 surahs and 6,236 verses (Hafs count), divided into 30 parts. Our text has 77,429 words – depending on the way of counting, others give slightly different numbers.", src: "Uthmani text, King Fahd Complex" },
  ],
  readTitle: "Whoever reads the Quran – what is promised",
  readLead: "The Quran is not a book to read once and put away. These words of the Prophet ﷺ are authentically reported:",
  hadith: [
    { text: "“Whoever reads a letter from the Book of Allah receives a good deed, and a good deed is multiplied by ten. I do not say that Alif-Lām-Mīm is a letter – rather Alif is a letter, Lām is a letter and Mīm is a letter.”", src: "at-Tirmidhi 2910" },
    { text: "“Read the Quran, for on the Day of Resurrection it will come as an intercessor for those who read it.”", src: "Sahih Muslim 804" },
    { text: "“The best of you are those who learn the Quran and teach it.”", src: "Sahih al-Bukhari 5027" },
    { text: "“The one who is skilled in the Quran is with the noble, obedient scribes. And the one who reads it and stumbles, finding it hard, has a double reward.”", src: "Sahih al-Bukhari 4937, Sahih Muslim 798" },
    { text: "“It will be said to the companion of the Quran: Read and rise, and recite as you used to recite in the world – your rank is at the last verse you read.”", src: "Abu Dawud 1464, at-Tirmidhi 2914" },
  ],
  wealthTitle: "Blessing, provision, prosperity",
  wealthLead: "The Quran promises no formula for quick money. It promises something greater: barakah – blessing that makes little go far –, a good life and provision from where one does not expect it. These are its own words (in meaning):",
  promises: [
    { ref: "71:10-12", title: "Asking forgiveness", text: "“Ask forgiveness of your Lord – He is ever Forgiving. He will send rain upon you in abundance, give you increase in wealth and children, and provide you with gardens and rivers.”" },
    { ref: "14:7", title: "Gratitude", text: "“If you are grateful, I will surely give you more.”" },
    { ref: "65:2-3", title: "God-consciousness and trust", text: "“Whoever is mindful of Allah, He will make a way out for him and provide for him from where he does not expect. And whoever relies upon Allah – He is sufficient for him.”" },
    { ref: "7:96", title: "Blessing for whole towns", text: "“Had the people of the towns believed and been mindful of Allah, We would have opened upon them blessings from the heaven and the earth.”" },
    { ref: "16:97", title: "A good life", text: "“Whoever does righteousness, whether male or female, while being a believer – We will surely give them a good life.”" },
    { ref: "35:29-30", title: "A trade that never fails", text: "“Those who recite the Book of Allah, establish prayer and spend from what We have provided them hope for a trade that will never perish.”" },
    { ref: "13:28", title: "Rest for the heart", text: "“Surely, in the remembrance of Allah do hearts find rest.”" },
    { ref: "17:82", title: "Healing", text: "“We send down of the Quran that which is healing and mercy for the believers.”" },
  ],
  wealthNote: "Reading a lot of Quran does not make anyone rich “automatically” – but it makes you rich in what lasts: calm, gratitude, trust and a reward that never ends. And whoever works honestly, gives thanks and asks forgiveness may hope for Allah’s provision.",
  wealthHadith: { text: "“Richness is not having many possessions; richness is the richness of the soul.”", src: "Sahih al-Bukhari 6446, Sahih Muslim 1051" },
  placesTitle: "Places where the heart finds peace",
  placesLead: "Peace with Allah can be found anywhere – He is near. But there are places and times He has especially blessed.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masjid al-Haram, Makkah", body: "The House of Allah, the Kaaba, the direction of every prayer. A prayer there counts for more than a hundred thousand prayers elsewhere.", src: "Ibn Majah 1406 (graded authentic by scholars)" },
    { ar: "المسجد النبوي", title: "The Prophet’s Mosque, Madinah", body: "A prayer there is better than a thousand elsewhere – except the Sacred Mosque. And between his house and his pulpit lies “a garden of the gardens of Paradise”.", src: "Sahih al-Bukhari 1190, 1196; Sahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masjid al-Aqsa, Jerusalem", body: "The first qibla, whose surroundings Allah has blessed (17:1) – one of the three mosques to which one sets out especially.", src: "Sahih al-Bukhari 1189, Sahih Muslim 1397" },
    { ar: "بيوت الله", title: "Every mosque", body: "The most beloved places to Allah are the mosques. And where people gather there, read the Quran and study it together, tranquillity (sakīnah) descends upon them, mercy covers them and angels surround them.", src: "Sahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Your home", body: "“Do not make your houses graveyards. Satan flees from the house in which Surah Al-Baqarah is recited.” A fixed place for your daily reading makes your home a place of peace.", src: "Sahih Muslim 780" },
    { ar: "الثلث الأخير", title: "The last third of the night", body: "A place in time: in the last third of every night Allah calls: “Who is calling upon Me, that I may answer him? Who is asking Me, that I may give him?”", src: "Sahih al-Bukhari 1145, Sahih Muslim 758" },
    { ar: "آيات الكون", title: "In creation", body: "“In the creation of the heavens and the earth and the alternation of night and day are signs for people of understanding” – who remember Allah standing, sitting and lying on their sides (3:190–191).", src: "Quran 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "In the Emirates", body: "The Sheikh Zayed Grand Mosque in Abu Dhabi, the Jumeirah Mosque in Dubai and the great mosques of Sharjah welcome visitors – places of stillness in the middle of life.", src: "", href: "/islam/mosques" },
  ],
  note: "Hadith are given with collection and number. The verses are rendered in meaning; tap a reference to read the Arabic wording and a recognised translation. For questions about rulings, please ask a scholar.",
  ctaTitle: "Don’t stop at amazement",
  ctaBody: "Every letter counts tenfold. Start today with one verse – the Shams Method guides you step by step.",
  cta: "Learn your first verse",
};

const ar: SecretsContent = {
  kicker: "عدٌّ موثَّق لا تخمين",
  title: "أسرار القرآن",
  lead: "تنتشر عن القرآن أرقامٌ و«معجزات» كثيرة، بعضها صحيح وبعضها لا يصح. هنا نعدّ بأنفسنا في النص العثماني الكامل، ونبيّن بصراحة ما ثبت. ومعها: ما وُعد به قارئ القرآن، وأين يجد القلب السكينة أيسر ما تكون.",
  counterTitle: "كم مرة وردت في القرآن؟",
  counterLead: "اضغط على كلمة لترى عدد مرات ورودها، وكل موضع منها لتقرأه مباشرة.",
  method: "العدّ في النص العثماني لمجمع الملك فهد بالمدينة المنورة (6236 آية بعدّ حفص). تُعدّ صيغ الكلمة مع «أل» والحروف السابقة (و، ف، ب، ل، ك) دون الضمائر المتصلة، وفي الأعلام مع حرف النداء «يا» أيضًا. قد تختلف الأعداد قليلًا باختلاف طريقة العدّ، ولذلك نذكر الطريقة.",
  times: "مرة", spots: "موضعًا", open: "افتح", allahNote: "في لفظ الجلالة نذكر العدد فقط، لكثرة المواضع.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "«لا تخف»" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "«لا خوف عليهم»" },
    { key: "allah", ar: "ٱللَّه", label: "لفظ الجلالة" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "الرحمن" },
    { key: "yawm", ar: "يَوْم", label: "يوم" },
    { key: "shahr", ar: "شَهْر", label: "شهر" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "الدنيا" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "الآخرة" },
    { key: "musa", ar: "مُوسَىٰ", label: "موسى" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "إبراهيم" },
    { key: "nuh", ar: "نُوح", label: "نوح" },
    { key: "yusuf", ar: "يُوسُف", label: "يوسف" },
    { key: "isa", ar: "عِيسَىٰ", label: "عيسى" },
    { key: "adam", ar: "ءَادَم", label: "آدم" },
    { key: "maryam", ar: "مَرْيَم", label: "مريم" },
    { key: "muhammad", ar: "مُحَمَّد", label: "محمد ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "أحمد ﷺ" },
  ],
  claimsTitle: "أقوال منتشرة، أعدنا عدّها",
  claimsLead: "كثيرٌ مما يُتداول في وسائل التواصل حسن النية، لكن القرآن لا يحتاج إلى أرقام مخترعة. لقد تحققنا من كل قول بأنفسنا.",
  verdicts: { true: "صحيح", false: "لا يصح بهذه الصيغة", method: "صحيح بهذه الطريقة في العدّ" },
  claims: [
    { q: "«لا تخف» وردت 365 مرة في القرآن، مرةً لكل يوم من أيام السنة.", v: "false", key: "fearNot", a: "وردت بصيغة النهي المباشر «لا تخف، لا تخافي، لا تخافوا، لا تخافا» 13 مرة: خطابًا لإبراهيم، ولموسى وهارون، ولأم موسى، وللوط، ولداود، وللمؤمنين. ووردت بشارة «لا خوف عليهم ولا هم يحزنون» 13 مرة أخرى. فالمجموع 26 موضعًا، أقل مما يقال، وفي كل موضع منها طمأنينة." },
    { q: "كلمة «يوم» وردت 365 مرة في القرآن.", v: "method", key: "yawm", a: "إذا عُدّ المفرد «يوم» و«يومًا» مع «أل» والحروف السابقة، دون الضمائر المتصلة ودون «يومئذ»، كان العدد 365 موضعًا تمامًا. وبطرق عدٍّ أخرى تختلف الأعداد، ويبقى الأمر لافتًا." },
    { q: "كلمة «شهر» وردت 12 مرة في القرآن.", v: "true", key: "shahr", a: "بصيغة المفرد «شهر، الشهر، شهرًا» وردت 12 مرة. والقرآن نفسه يقول: ﴿إِنَّ عِدَّةَ الشُّهُورِ عِندَ اللَّهِ اثْنَا عَشَرَ شَهْرًا﴾ (التوبة: 36)." },
    { q: "«الدنيا» و«الآخرة» وردتا بعدد متساوٍ، 115 مرة لكلٍّ منهما.", v: "method", key: "dunya", a: "بالعدّ مع «أل» والحروف السابقة: الدنيا 115 مرة، والآخرة 115 مرة. ولا يُعدّ موضع آل عمران 72 لأن «آخِرَه» فيه بمعنى آخر النهار لا الدار الآخرة." },
    { q: "لفظ الجلالة «الله» ورد 2699 مرة.", v: "true", key: "allah", a: "مع كل السوابق مثل «والله، بالله، لله» يبلغ العدد 2699 موضعًا دون «اللهم»، وهو موافق للإحصاءات المعروفة." },
    { q: "موسى عليه السلام أكثر الأنبياء ذكرًا في القرآن.", v: "true", key: "musa", a: "ذُكر موسى باسمه 136 مرة، أكثر من أي نبي آخر، ثم إبراهيم (69)، ثم نوح (43)، ثم يوسف (27)، ثم عيسى وآدم (25 لكلٍّ منهما)." },
    { q: "مريم عليها السلام هي المرأة الوحيدة المذكورة باسمها في القرآن.", v: "true", key: "maryam", a: "نعم، ورد اسمها 34 مرة، وسُمّيت باسمها سورة كاملة: سورة مريم (19)." },
    { q: "ذُكر النبي محمد ﷺ باسمه أربع مرات فقط.", v: "true", key: "muhammad", a: "أربع مرات باسم «محمد» (آل عمران 144، الأحزاب 40، محمد 2، الفتح 29)، ومرة باسم «أحمد» (الصف 6)، ويخاطبه الله في مواضع كثيرة بـ«يا أيها النبي» و«يا أيها الرسول»." },
  ],
  factsTitle: "ما يدعو إلى التأمل حقًّا، مع المصدر",
  facts: [
    { ar: "الفاتحة", title: "أعظم سورة", body: "سمّى النبي ﷺ الفاتحة أعظم سورة في القرآن، وهي السبع المثاني، تُقرأ في كل ركعة.", src: "صحيح البخاري 4474" },
    { ar: "آية الكرسي", title: "أعظم آية", body: "آية الكرسي (البقرة: 255) أعظم آية في كتاب الله، كما علّم النبي ﷺ أُبيَّ بن كعب.", src: "صحيح مسلم 810" },
    { ar: "الإخلاص", title: "ثلث القرآن", body: "سورة الإخلاص (112) تعدل ثلث القرآن، أربع آيات قصيرة في توحيد الله.", src: "صحيح البخاري 5013" },
    { ar: "اقرأ", title: "الكلمة الأولى", body: "بدأ الوحي في غار حراء بقوله تعالى: ﴿اقْرَأْ﴾ (العلق: 1–5)، فكان أول ما نزل دعوة إلى العلم.", src: "صحيح البخاري 3" },
    { ar: "البسملة", title: "114 بسملة", body: "«بسم الله الرحمن الرحيم» في أول 113 سورة، كلها إلا التوبة، ومرة في أثناء سورة: في كتاب سليمان إلى ملكة سبأ (النمل: 30). فالمجموع 114، بعدد السور.", src: "النمل: 30" },
    { ar: "الدَّين", title: "أطول آية", body: "أطول آية في القرآن آية الدَّين (البقرة: 282)، تنظّم توثيق الديون كتابةً، دليلًا على عناية القرآن بالعدل في المعاملات اليومية.", src: "البقرة: 282" },
    { ar: "الكوثر", title: "أقصر سورة", body: "سورة الكوثر (108) ثلاث آيات وعشر كلمات، وأطول السور البقرة بمئتين وست وثمانين آية.", src: "الكوثر، البقرة" },
    { ar: "١١٤", title: "114 سورة و6236 آية", body: "في القرآن 114 سورة و6236 آية بعدّ حفص، مقسّمة إلى ثلاثين جزءًا. وفي النص الذي عددنا فيه 77429 كلمة، وقد تختلف الأعداد قليلًا باختلاف طريقة العدّ.", src: "النص العثماني، مجمع الملك فهد" },
  ],
  readTitle: "ما وُعد به قارئ القرآن",
  readLead: "القرآن ليس كتابًا يُقرأ مرة ثم يُترك. وهذه أحاديث صحيحة عن النبي ﷺ:",
  hadith: [
    { text: "«مَن قرأ حرفًا من كتاب الله فله به حسنة، والحسنة بعشر أمثالها، لا أقول: الم حرف، ولكن ألفٌ حرف، ولامٌ حرف، وميمٌ حرف».", src: "سنن الترمذي 2910" },
    { text: "«اقرؤوا القرآن؛ فإنه يأتي يوم القيامة شفيعًا لأصحابه».", src: "صحيح مسلم 804" },
    { text: "«خيركم مَن تعلّم القرآن وعلّمه».", src: "صحيح البخاري 5027" },
    { text: "«الماهر بالقرآن مع السفرة الكرام البررة، والذي يقرأ القرآن ويتتعتع فيه وهو عليه شاقّ له أجران».", src: "صحيح البخاري 4937، صحيح مسلم 798" },
    { text: "«يُقال لصاحب القرآن: اقرأ وارتقِ ورتّل كما كنت ترتّل في الدنيا، فإن منزلتك عند آخر آية تقرؤها».", src: "سنن أبي داود 1464، سنن الترمذي 2914" },
  ],
  wealthTitle: "البركة والرزق والسعة",
  wealthLead: "القرآن لا يعِد بوصفة للمال السريع، بل يعِد بما هو أعظم: البركة التي تجعل القليل كثيرًا، والحياة الطيبة، والرزق من حيث لا يُحتسب. وهذه كلماته (بالمعنى):",
  promises: [
    { ref: "71:10-12", title: "الاستغفار", text: "استغفروا ربكم إنه كان غفارًا، يرسل السماء عليكم مدرارًا، ويمددكم بأموال وبنين، ويجعل لكم جنات ويجعل لكم أنهارًا." },
    { ref: "14:7", title: "الشكر", text: "لئن شكرتم لأزيدنّكم." },
    { ref: "65:2-3", title: "التقوى والتوكل", text: "ومن يتق الله يجعل له مخرجًا، ويرزقه من حيث لا يحتسب، ومن يتوكل على الله فهو حسبه." },
    { ref: "7:96", title: "بركات للقرى", text: "ولو أن أهل القرى آمنوا واتقوا لفتحنا عليهم بركات من السماء والأرض." },
    { ref: "16:97", title: "الحياة الطيبة", text: "من عمل صالحًا من ذكر أو أنثى وهو مؤمن فلنحيينّه حياة طيبة." },
    { ref: "35:29-30", title: "تجارة لن تبور", text: "إن الذين يتلون كتاب الله وأقاموا الصلاة وأنفقوا مما رزقناهم سرًّا وعلانية يرجون تجارة لن تبور." },
    { ref: "13:28", title: "طمأنينة القلب", text: "ألا بذكر الله تطمئن القلوب." },
    { ref: "17:82", title: "الشفاء", text: "وننزّل من القرآن ما هو شفاء ورحمة للمؤمنين." },
  ],
  wealthNote: "فمن أكثر من قراءة القرآن لا يصير غنيًّا «تلقائيًّا»، لكنه يغتني بما يبقى: السكينة والشكر والتوكل وأجرٌ لا ينقطع. ومن عمل بصدق وشكر واستغفر فليرجُ رزق الله.",
  wealthHadith: { text: "«ليس الغنى عن كثرة العَرَض، ولكن الغنى غنى النفس».", src: "صحيح البخاري 6446، صحيح مسلم 1051" },
  placesTitle: "أماكن يجد فيها القلب السكينة",
  placesLead: "السكينة مع الله ممكنة في كل مكان، فهو قريب. لكن ثمة أماكن وأوقاتًا خصّها الله بالبركة.",
  places: [
    { ar: "المسجد الحرام", title: "المسجد الحرام، مكة المكرمة", body: "بيت الله والكعبة، قبلة كل مصلٍّ. والصلاة فيه أفضل من مئة ألف صلاة فيما سواه.", src: "سنن ابن ماجه 1406 (صحّحه أهل العلم)" },
    { ar: "المسجد النبوي", title: "المسجد النبوي، المدينة المنورة", body: "الصلاة فيه خير من ألف صلاة فيما سواه إلا المسجد الحرام، و«ما بين بيتي ومنبري روضة من رياض الجنة».", src: "صحيح البخاري 1190، 1196؛ صحيح مسلم 1394" },
    { ar: "المسجد الأقصى", title: "المسجد الأقصى، القدس", body: "القبلة الأولى، الذي بارك الله حوله (الإسراء: 1)، وأحد المساجد الثلاثة التي تُشدّ إليها الرحال.", src: "صحيح البخاري 1189، صحيح مسلم 1397" },
    { ar: "بيوت الله", title: "كل مسجد", body: "أحبّ البلاد إلى الله مساجدها، وما اجتمع قوم في بيت من بيوت الله يتلون كتاب الله ويتدارسونه بينهم إلا نزلت عليهم السكينة وغشيتهم الرحمة وحفّتهم الملائكة.", src: "صحيح مسلم 671، 2699" },
    { ar: "بيتك", title: "بيتك", body: "«لا تجعلوا بيوتكم مقابر، إن الشيطان ينفر من البيت الذي تُقرأ فيه سورة البقرة». ومكان ثابت لوِردك اليومي يجعل بيتك موضع سكينة.", src: "صحيح مسلم 780" },
    { ar: "الثلث الأخير", title: "الثلث الأخير من الليل", body: "مكانٌ في الزمن: ينادي الله في الثلث الأخير من كل ليلة: «مَن يدعوني فأستجيب له؟ مَن يسألني فأعطيه؟».", src: "صحيح البخاري 1145، صحيح مسلم 758" },
    { ar: "آيات الكون", title: "في الخلق", body: "﴿إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ﴾، الذين يذكرون الله قيامًا وقعودًا وعلى جنوبهم (آل عمران: 190–191).", src: "آل عمران: 190–191" },
    { ar: "جامع الشيخ زايد", title: "في الإمارات", body: "جامع الشيخ زايد الكبير في أبوظبي، ومسجد جميرا في دبي، والمساجد الكبرى في الشارقة، ترحّب بالزوار، وهي واحات سكينة في قلب الحياة.", src: "", href: "/islam/mosques" },
  ],
  note: "الأحاديث مذكورة بالكتاب والرقم، والآيات في قسم البركة مذكورة بالمعنى؛ اضغط على رقم الآية لقراءة نصها كاملًا. وللأحكام الشرعية ارجع إلى أهل العلم.",
  ctaTitle: "لا تقف عند الإعجاب",
  ctaBody: "كل حرف بعشر حسنات. ابدأ اليوم بآية واحدة، ومنهج شمس يرافقك خطوة بخطوة.",
  cta: "احفظ أول آية",
};

export async function secretsContent(locale: string): Promise<SecretsContent> {
  if (locale === "de") return de;
  if (locale === "ar") return ar;
  if (locale === "en") return en;
  try { return (await import(`../pagecontent/${locale}/secrets`)).default as SecretsContent; } catch { return en; }
}
