import type { SecretsContent } from "../../secrets/content";
const c: SecretsContent = {
  kicker: "Vérifié, pas deviné",
  title: "Les secrets du Coran",
  lead: "De nombreux chiffres et « miracles » circulent à propos du Coran – certains sont vrais, d’autres non. Ici, nous comptons nous-mêmes, dans le texte uthmanien complet, et disons ouvertement ce qui est établi. Et aussi : ce qui est promis à celui qui lit le Coran, et où le cœur trouve le plus facilement la paix.",
  counterTitle: "Combien de fois cela apparaît-il dans le Coran ?",
  counterLead: "Touche un mot. Tu vois combien de fois il apparaît – et chaque passage, prêt à être lu.",
  method: "Compté dans le texte uthmanien du Complexe du Roi Fahd à Médine (6 236 versets, décompte de Hafs). Les formes de mots sont comptées avec l’article et les particules préfixées (wa-, fa-, bi-, li-, ka-), sans les pronoms suffixes ; pour les noms, aussi avec l’interpellation « yā ». D’autres façons de compter peuvent donner des chiffres légèrement différents – c’est pourquoi nous indiquons la méthode.",
  times: "fois", spots: "passages", open: "Ouvrir", allahNote: "Pour « Allah », nous ne montrons que le nombre – les passages seraient trop nombreux pour une liste.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "« N’aie pas peur »" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "« Pas de crainte pour eux »" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "Le Tout Miséricordieux" },
    { key: "yawm", ar: "يَوْم", label: "Jour" },
    { key: "shahr", ar: "شَهْر", label: "Mois" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "Ici-bas" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "L’au-delà" },
    { key: "musa", ar: "مُوسَىٰ", label: "Moussa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nouh" },
    { key: "yusuf", ar: "يُوسُف", label: "Youssef" },
    { key: "isa", ar: "عِيسَىٰ", label: "Issa" },
    { key: "adam", ar: "ءَادَم", label: "Adam" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Affirmations répandues – recomptées",
  claimsLead: "Ce qui est partagé sur les réseaux sociaux part souvent d’une bonne intention. Mais le Coran n’a pas besoin de chiffres inventés. Nous avons vérifié chaque affirmation nous-mêmes.",
  verdicts: { true: "Exact", false: "Pas tout à fait", method: "Exact – avec cette façon de compter" },
  claims: [
    { q: "« N’aie pas peur » apparaît 365 fois dans le Coran – une fois pour chaque jour de l’année.", v: "false", key: "fearNot", a: "Comme injonction directe – « lā takhaf », « lā takhāfī », « lā takhāfū », « lā takhāfā » – cela revient 13 fois : dit à Ibrahim, à Moussa et Haroun, à la mère de Moussa, à Lout, à Dawoud et aux croyants. À cela s’ajoute, 13 fois, la promesse « aucune crainte ne sera sur eux, et ils ne seront pas affligés ». Ensemble, 26 passages – moins que ce qui est prétendu, mais chacun d’eux est une consolation." },
    { q: "Le mot « jour » apparaît 365 fois dans le Coran.", v: "method", key: "yawm", a: "En comptant le singulier « yawm » et « yawman » – avec l’article et les particules, mais sans pronoms suffixes et sans « yawma’idhin » (ce jour-là) –, on obtient exactement 365 passages. D’autres façons de compter donnent d’autres chiffres. Cela reste remarquable." },
    { q: "Le mot « mois » apparaît 12 fois dans le Coran.", v: "true", key: "shahr", a: "Au singulier (« shahr », « ash-shahr », « shahran »), il y a 12 passages. Et le Coran dit lui-même : « Le nombre des mois auprès d’Allah est de douze » (9:36)." },
    { q: "« Ici-bas » et « l’au-delà » apparaissent aussi souvent l’un que l’autre – 115 fois chacun.", v: "method", key: "dunya", a: "Comptés avec l’article et les particules : ad-dunyā 115 fois, al-ākhira 115 fois. N’est pas compté 3:72, où « ākhirahu » signifie « sa fin » (du jour), et non l’au-delà." },
    { q: "Le nom « Allah » apparaît 2 699 fois dans le Coran.", v: "true", key: "allah", a: "Compté avec tous les préfixes comme wallāhi, billāhi, lillāhi, cela donne 2 699 passages (sans « Allāhumma »). Cela correspond aux décomptes connus." },
    { q: "Moussa est le prophète le plus souvent mentionné.", v: "true", key: "musa", a: "Moussa est nommé 136 fois – plus que tout autre prophète. Viennent ensuite Ibrahim (69), Nouh (43), Youssef (27), Issa et Adam (25 chacun)." },
    { q: "Maryam est la seule femme mentionnée par son nom dans le Coran.", v: "true", key: "maryam", a: "Oui. Son nom apparaît 34 fois, et toute une sourate porte son nom : la sourate 19, Maryam." },
    { q: "Le Prophète Muhammad ﷺ n’est mentionné par son nom que quatre fois.", v: "true", key: "muhammad", a: "Quatre fois sous le nom de « Muhammad » (3:144, 33:40, 47:2, 48:29) et une fois sous celui d’« Ahmad » (61:6) – en de nombreux autres endroits, Allah s’adresse à lui par « Ô Prophète » et « Ô Messager »." },
  ],
  factsTitle: "Ce qui étonne vraiment – avec la source",
  facts: [
    { ar: "الفاتحة", title: "La plus grande sourate", body: "Le Prophète ﷺ a appelé Al-Fātiḥa la plus grande sourate du Coran et « les sept versets souvent répétés » – elle est récitée à chaque unité de prière.", src: "Sahih al-Bukhari 4474" },
    { ar: "آية الكرسي", title: "Le plus grand verset", body: "Āyat al-Kursī (2:255) est le plus grand verset du Livre d’Allah – c’est ce que le Prophète ﷺ a enseigné à son compagnon Ubayy ibn Ka‘b.", src: "Sahih Muslim 810" },
    { ar: "الإخلاص", title: "Un tiers du Coran", body: "La sourate Al-Ikhlāṣ (112) équivaut à un tiers du Coran – quatre courts versets sur l’unicité d’Allah.", src: "Sahih al-Bukhari 5013" },
    { ar: "اقرأ", title: "Le premier mot", body: "La première révélation dans la grotte de Ḥirā’ commence par « Lis ! » (96:1–5). Le Coran commence sa descente par la connaissance.", src: "Sahih al-Bukhari 3" },
    { ar: "البسملة", title: "114 basmalas", body: "« Bismillāh ar-Raḥmān ar-Raḥīm » figure au début de 113 sourates – toutes sauf At-Tawba – et une fois au milieu d’une sourate : dans la lettre de Soulayman à la reine de Saba (27:30). Cela fait 114 en tout, autant que de sourates.", src: "Coran 27:30" },
    { ar: "الدَّين", title: "Le plus long verset", body: "Le plus long verset est le « verset de la dette » (2:282) : il règle la manière de consigner les dettes par écrit – signe de la gravité avec laquelle le Coran prend la justice au quotidien.", src: "Coran 2:282" },
    { ar: "الكوثر", title: "La plus courte sourate", body: "Al-Kawthar (108) compte trois versets et dix mots. La plus longue sourate, Al-Baqara, compte 286 versets.", src: "Coran 108, 2" },
    { ar: "١١٤", title: "114 sourates, 6 236 versets", body: "Le Coran compte 114 sourates et 6 236 versets (décompte de Hafs), répartis en 30 parties. Notre texte compte 77 429 mots – selon la façon de compter, d’autres donnent des chiffres légèrement différents.", src: "Texte uthmanien, Complexe du Roi Fahd" },
  ],
  readTitle: "Celui qui lit le Coran – ce qui lui est promis",
  readLead: "Le Coran n’est pas un livre que l’on lit une fois pour le ranger ensuite. Ces paroles du Prophète ﷺ sont rapportées de façon authentique :",
  hadith: [
    { text: "« Celui qui lit une lettre du Livre d’Allah reçoit une bonne action, et la bonne action vaut dix fois. Je ne dis pas que Alif-Lām-Mīm est une lettre – mais Alif est une lettre, Lām est une lettre et Mīm est une lettre. »", src: "at-Tirmidhi 2910" },
    { text: "« Lisez le Coran, car il viendra au Jour de la Résurrection comme intercesseur pour ceux qui l’ont lu. »", src: "Sahih Muslim 804" },
    { text: "« Les meilleurs d’entre vous sont ceux qui apprennent le Coran et l’enseignent. »", src: "Sahih al-Bukhari 5027" },
    { text: "« Celui qui maîtrise le Coran est avec les nobles et obéissants scribes. Et celui qui le lit en butant, trouvant cela difficile, a une double récompense. »", src: "Sahih al-Bukhari 4937, Sahih Muslim 798" },
    { text: "« Il sera dit au compagnon du Coran : Lis et monte, et récite comme tu récitais en ce monde – ton rang est au dernier verset que tu lis. »", src: "Abu Dawud 1464, at-Tirmidhi 2914" },
  ],
  wealthTitle: "Bénédiction, subsistance, prospérité",
  wealthLead: "Le Coran ne promet aucune formule pour gagner vite de l’argent. Il promet quelque chose de plus grand : la barakah – la bénédiction qui fait que peu suffit largement –, une bonne vie et une subsistance venant d’où l’on ne s’y attend pas. Ce sont ses propres paroles (quant au sens) :",
  promises: [
    { ref: "71:10-12", title: "Demander pardon", text: "« Demandez pardon à votre Seigneur – Il est Très Pardonneur. Il vous enverra la pluie en abondance, vous accordera davantage de biens et d’enfants, et vous donnera des jardins et des rivières. »" },
    { ref: "14:7", title: "La gratitude", text: "« Si vous êtes reconnaissants, Je vous donnerai assurément davantage. »" },
    { ref: "65:2-3", title: "Piété et confiance", text: "« Quiconque craint Allah, Il lui ouvrira une issue et le pourvoira d’où il ne s’y attend pas. Et quiconque place sa confiance en Allah, Il lui suffit. »" },
    { ref: "7:96", title: "Bénédiction pour des villes entières", text: "« Si les habitants des cités avaient cru et craint Allah, Nous leur aurions ouvert des bénédictions du ciel et de la terre. »" },
    { ref: "16:97", title: "Une bonne vie", text: "« Quiconque fait le bien, homme ou femme, tout en étant croyant, Nous lui ferons assurément vivre une bonne vie. »" },
    { ref: "35:29-30", title: "Un commerce qui ne perd jamais", text: "« Ceux qui récitent le Livre d’Allah, accomplissent la prière et dépensent de ce que Nous leur avons accordé, espèrent un commerce qui ne périra jamais. »" },
    { ref: "13:28", title: "Le repos du cœur", text: "« En vérité, c’est par le rappel d’Allah que les cœurs trouvent le repos. »" },
    { ref: "17:82", title: "Guérison", text: "« Nous faisons descendre du Coran ce qui est guérison et miséricorde pour les croyants. »" },
  ],
  wealthNote: "Lire beaucoup le Coran ne rend donc personne riche « automatiquement » – mais cela rend riche de ce qui demeure : le calme, la gratitude, la confiance et une récompense qui ne cesse pas. Et celui qui travaille honnêtement, remercie et demande pardon peut espérer la subsistance d’Allah.",
  wealthHadith: { text: "« La richesse n’est pas la quantité des biens ; la richesse est la richesse de l’âme. »", src: "Sahih al-Bukhari 6446, Sahih Muslim 1051" },
  placesTitle: "Des lieux où le cœur trouve la paix",
  placesLead: "On peut trouver la paix avec Allah partout – Il est proche. Mais il existe des lieux et des moments qu’Il a particulièrement bénis.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masjid al-Haram, La Mecque", body: "La Maison d’Allah, la Kaaba, la direction de chaque prière. Une prière là-bas vaut plus que cent mille prières ailleurs.", src: "Ibn Majah 1406 (jugé authentique par les savants)" },
    { ar: "المسجد النبوي", title: "La Mosquée du Prophète, Médine", body: "Une prière là-bas vaut mieux que mille ailleurs – sauf la Mosquée sacrée. Et entre sa maison et son minbar se trouve « un jardin parmi les jardins du Paradis ».", src: "Sahih al-Bukhari 1190, 1196 ; Sahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masjid al-Aqsa, Jérusalem", body: "La première qibla, dont Allah a béni les alentours (17:1) – l’une des trois mosquées vers lesquelles on se met spécialement en route.", src: "Sahih al-Bukhari 1189, Sahih Muslim 1397" },
    { ar: "بيوت الله", title: "Chaque mosquée", body: "Les lieux les plus aimés d’Allah sont les mosquées. Et là où des gens se rassemblent, lisent le Coran et l’étudient ensemble, la sérénité (sakīnah) descend sur eux, la miséricorde les recouvre et les anges les entourent.", src: "Sahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Ta maison", body: "« Ne faites pas de vos maisons des cimetières. Satan fuit la maison où l’on récite la sourate Al-Baqara. » Un endroit fixe pour ta lecture quotidienne fait de ta maison un lieu de paix.", src: "Sahih Muslim 780" },
    { ar: "الثلث الأخير", title: "Le dernier tiers de la nuit", body: "Un lieu dans le temps : dans le dernier tiers de chaque nuit, Allah appelle : « Qui M’invoque, que Je lui réponde ? Qui Me demande, que Je lui donne ? »", src: "Sahih al-Bukhari 1145, Sahih Muslim 758" },
    { ar: "آيات الكون", title: "Dans la création", body: "« Dans la création des cieux et de la terre et dans l’alternance de la nuit et du jour, il y a des signes pour les gens doués d’intelligence » – ceux qui invoquent Allah debout, assis et couchés sur le côté (3:190–191).", src: "Coran 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "Aux Émirats", body: "La Grande Mosquée Cheikh Zayed à Abou Dhabi, la mosquée de Jumeirah à Dubaï et les grandes mosquées de Sharjah accueillent les visiteurs – des lieux de calme au milieu de la vie.", src: "", href: "/islam/mosques" },
  ],
  note: "Les hadiths sont donnés avec leur recueil et leur numéro. Les versets sont rendus dans leur sens ; touche une référence pour lire le texte arabe et une traduction reconnue. Pour les questions de jugements religieux, adresse-toi à un savant.",
  ctaTitle: "Ne t’arrête pas à l’émerveillement",
  ctaBody: "Chaque lettre compte dix fois. Commence dès aujourd’hui par un verset – la Méthode Shams te guide pas à pas.",
  cta: "Apprendre ton premier verset",
};
export default c;
