import type { SecretsContent } from "../../secrets/content";
const c: SecretsContent = {
  kicker: "Disemak, bukan diteka",
  title: "Rahsia al-Quran",
  lead: "Banyak angka dan “keajaiban” tentang al-Quran yang tersebar – sebahagian benar, sebahagian tidak. Di sini kami mengira sendiri, dalam teks Uthmani yang lengkap, dan menyatakan dengan jujur apa yang terbukti. Tambahan: apa yang dijanjikan kepada orang yang membaca al-Quran, dan di mana hati paling mudah mendapat ketenangan.",
  counterTitle: "Berapa kali ini muncul dalam al-Quran?",
  counterLead: "Sentuh sesuatu perkataan. Anda akan melihat berapa kali ia muncul – dan setiap tempatnya, sedia untuk dibaca.",
  method: "Dikira dalam teks Uthmani Kompleks Raja Fahd di Madinah (6,236 ayat, kiraan Hafs). Bentuk perkataan dikira dengan kata sandang dan partikel awalan (wa-, fa-, bi-, li-, ka-), tanpa kata ganti yang bercantum; bagi nama pula dengan seruan “yā”. Cara pengiraan lain boleh memberikan angka yang sedikit berbeza – sebab itu kami nyatakan kaedahnya.",
  times: "kali", spots: "tempat", open: "Buka", allahNote: "Bagi “Allah” kami hanya menunjukkan angkanya – tempatnya terlalu banyak untuk disenaraikan.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "“Jangan takut”" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "“Tiada ketakutan ke atas mereka”" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "Ar-Rahman (Maha Pemurah)" },
    { key: "yawm", ar: "يَوْم", label: "Hari" },
    { key: "shahr", ar: "شَهْر", label: "Bulan" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "Dunia" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "Akhirat" },
    { key: "musa", ar: "مُوسَىٰ", label: "Musa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nuh" },
    { key: "yusuf", ar: "يُوسُف", label: "Yusuf" },
    { key: "isa", ar: "عِيسَىٰ", label: "Isa" },
    { key: "adam", ar: "ءَادَم", label: "Adam" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Dakwaan popular – dikira semula",
  claimsLead: "Apa yang dikongsi di media sosial sering kali bermaksud baik. Tetapi al-Quran tidak memerlukan angka rekaan. Kami menyemak setiap pernyataan sendiri.",
  verdicts: { true: "Benar", false: "Kurang tepat", method: "Benar – dengan cara pengiraan ini" },
  claims: [
    { q: "“Jangan takut” muncul 365 kali dalam al-Quran – sekali untuk setiap hari dalam setahun.", v: "false", key: "fearNot", a: "Sebagai perintah langsung – “lā takhaf”, “lā takhāfī”, “lā takhāfū”, “lā takhāfā” – ia muncul 13 kali: dikatakan kepada Ibrahim, kepada Musa dan Harun, kepada ibu Musa, kepada Lut, kepada Daud dan kepada orang beriman. Ditambah pula 13 kali janji “tiada ketakutan ke atas mereka, dan mereka tidak akan berdukacita”. Jumlahnya 26 tempat – kurang daripada yang didakwa, tetapi setiap satunya satu penghiburan." },
    { q: "Perkataan “hari” muncul 365 kali dalam al-Quran.", v: "method", key: "yawm", a: "Jika kita mengira bentuk tunggal “yawm” dan “yawman” – dengan kata sandang dan partikel, tetapi tanpa kata ganti yang bercantum dan tanpa “yawma’idhin” (pada hari itu) – hasilnya tepat 365 tempat. Dengan cara pengiraan lain, angkanya berbeza. Ia tetap luar biasa." },
    { q: "Perkataan “bulan” muncul 12 kali dalam al-Quran.", v: "true", key: "shahr", a: "Dalam bentuk tunggal (“shahr”, “ash-shahr”, “shahran”) terdapat 12 tempat. Dan al-Quran sendiri berfirman: “Sesungguhnya bilangan bulan di sisi Allah ialah dua belas” (9:36)." },
    { q: "“Dunia” dan “akhirat” muncul sama banyak – masing-masing 115 kali.", v: "method", key: "dunya", a: "Dikira dengan kata sandang dan partikel: ad-dunyā 115 kali, al-ākhira 115 kali. Tidak dikira 3:72, kerana di sana “ākhirahu” bermaksud “penghujungnya” (hari itu), bukan akhirat." },
    { q: "Nama “Allah” muncul 2,699 kali dalam al-Quran.", v: "true", key: "allah", a: "Dikira dengan semua awalan seperti wallāhi, billāhi, lillāhi, jumlahnya 2,699 tempat (tanpa “Allāhumma”). Ini sepadan dengan kiraan yang terkenal." },
    { q: "Musa ialah nabi yang paling banyak disebut.", v: "true", key: "musa", a: "Musa disebut namanya 136 kali – lebih banyak daripada mana-mana nabi lain. Seterusnya Ibrahim (69), Nuh (43), Yusuf (27), Isa dan Adam (masing-masing 25)." },
    { q: "Maryam ialah satu-satunya wanita yang disebut namanya dalam al-Quran.", v: "true", key: "maryam", a: "Ya. Namanya muncul 34 kali, dan sebuah surah penuh memakai namanya: surah 19, Maryam." },
    { q: "Nabi Muhammad ﷺ hanya disebut namanya sebanyak empat kali.", v: "true", key: "muhammad", a: "Empat kali sebagai “Muhammad” (3:144, 33:40, 47:2, 48:29) dan sekali sebagai “Ahmad” (61:6) – di banyak tempat lain Allah menyeru baginda dengan “Wahai Nabi” dan “Wahai Rasul”." },
  ],
  factsTitle: "Yang benar-benar menakjubkan – beserta sumbernya",
  facts: [
    { ar: "الفاتحة", title: "Surah paling agung", body: "Nabi ﷺ menamakan al-Fatihah sebagai surah paling agung dalam al-Quran dan “tujuh ayat yang diulang-ulang” – ia dibaca dalam setiap rakaat solat.", src: "Sahih al-Bukhari 4474" },
    { ar: "آية الكرسي", title: "Ayat paling agung", body: "Ayat al-Kursi (2:255) ialah ayat paling agung dalam Kitab Allah – demikianlah Nabi ﷺ mengajar sahabatnya, Ubay bin Ka‘b.", src: "Sahih Muslim 810" },
    { ar: "الإخلاص", title: "Satu pertiga al-Quran", body: "Surah al-Ikhlas (112) setara dengan satu pertiga al-Quran – empat ayat pendek tentang keesaan Allah.", src: "Sahih al-Bukhari 5013" },
    { ar: "اقرأ", title: "Perkataan pertama", body: "Wahyu pertama di Gua Hira bermula dengan “Bacalah!” (96:1–5). Al-Quran memulakan penurunannya dengan ilmu.", src: "Sahih al-Bukhari 3" },
    { ar: "البسملة", title: "114 basmalah", body: "“Bismillāh ar-Raḥmān ar-Raḥīm” terdapat di permulaan 113 surah – semuanya kecuali at-Taubah – dan sekali di tengah sebuah surah: dalam surat Sulaiman kepada Ratu Saba’ (27:30). Jumlahnya 114, sebanyak bilangan surah.", src: "al-Quran 27:30" },
    { ar: "الدَّين", title: "Ayat paling panjang", body: "Ayat yang paling panjang ialah “ayat hutang” (2:282): ia mengatur cara mencatat hutang secara bertulis – tanda betapa al-Quran mengambil berat soal keadilan dalam kehidupan seharian.", src: "al-Quran 2:282" },
    { ar: "الكوثر", title: "Surah paling pendek", body: "Al-Kauthar (108) mempunyai tiga ayat dan sepuluh perkataan. Surah paling panjang, al-Baqarah, mempunyai 286 ayat.", src: "al-Quran 108, 2" },
    { ar: "١١٤", title: "114 surah, 6,236 ayat", body: "Al-Quran mempunyai 114 surah dan 6,236 ayat (kiraan Hafs), dibahagikan kepada 30 juzuk. Teks kami mengandungi 77,429 perkataan – bergantung pada cara pengiraan, pihak lain menyebut angka yang sedikit berbeza.", src: "Teks Uthmani, Kompleks Raja Fahd" },
  ],
  moreTitle: "Lebih banyak rahsia",
  more: [
    { ar: "التوبة", title: "Surah tanpa basmalah", body: "At-Taubah (surah 9) ialah satu-satunya surah yang tidak bermula dengan “Bismillāh ar-Raḥmān ar-Raḥīm”. Para ulama memberikan pelbagai sebab – misalnya kerana ia dibuka dengan pengisytiharan tegas berlepas diri (bara’ah).", src: "al-Quran 9:1" },
    { ar: "النمل", title: "Surah dengan dua basmalah", body: "An-Naml (surah 27) mengandungi basmalah dua kali: pada permulaannya dan pada ayat 30, dalam surat Sulaiman kepada Ratu Saba’.", src: "al-Quran 27:30" },
    { ar: "المجادلة", title: "Allah dalam setiap ayat", body: "Dalam surah al-Mujadilah (58), nama “Allah” muncul dalam setiap satu daripada 22 ayatnya – kami menyemak satu demi satu.", src: "al-Quran 58" },
    { ar: "الرحمن", title: "Soalan yang sama 31 kali", body: "Dalam surah ar-Rahman (55), satu soalan berulang 31 kali: “Maka yang mana satu di antara nikmat-nikmat Tuhan kamu yang kamu hendak dustakan?”", src: "al-Quran 55:13" },
    { ar: "المرسلات", title: "Sepuluh kali: “Kecelakaan besar pada hari itu …”", body: "Surah al-Mursalat (77) mengulang sepuluh kali: “Kecelakaan besar pada hari itu bagi orang-orang yang mendustakan!”", src: "al-Quran 77:15" },
    { ar: "أبجد", title: "Kesemua 28 huruf dalam satu ayat", body: "Hanya dua ayat yang mengandungi kesemua 28 huruf abjad Arab: 3:154 dan 48:29, ayat yang menggambarkan para sahabat Nabi ﷺ.", src: "al-Quran 3:154, 48:29" },
    { ar: "الم", title: "29 surah dengan huruf-huruf misteri", body: "29 surah bermula dengan huruf-huruf tunggal seperti Alif Lam Mim, Ya Sin atau Qaf. Maknanya hanya Allah yang mengetahui – ramai ulama melihat padanya tanda bahawa al-Quran terdiri daripada huruf-huruf ini juga, namun tidak dapat ditandingi.", src: "cth. al-Quran 2:1, 36:1, 50:1" },
    { ar: "يونس", title: "Surah bernama nabi", body: "Enam surah membawa nama seorang nabi: Yunus, Hud, Yusuf, Ibrahim, Muhammad ﷺ dan Nuh. Dan satu surah membawa nama seorang wanita: Maryam.", src: "al-Quran 10, 11, 12, 14, 47, 71, 19" },
    { ar: "مكية", title: "86 surah Makkiyyah, 28 surah Madaniyyah", body: "Menurut pengelasan dalam Mushaf Madinah, 86 surah diturunkan di Makkah dan 28 di Madinah. Surah Makkiyyah terutamanya berbicara tentang iman, manakala surah Madaniyyah juga tentang kehidupan bermasyarakat.", src: "Mushaf Madinah" },
    { ar: "سجدة", title: "Tempat-tempat sujud", body: "Pada 15 tempat Mushaf Madinah menandakan sujud ketika bacaan (sujud tilawah). Mazhab-mazhab fiqh mengira 14 atau 15.", src: "cth. al-Quran 7:206, 96:19" },
    { ar: "العصر", title: "Tiga surah dengan tiga ayat", body: "Al-‘Asr, al-Kauthar dan an-Nasr masing-masing hanya mempunyai tiga ayat. Imam asy-Syafi‘i diriwayatkan berkata: sekiranya manusia hanya merenungi surah al-‘Asr, itu sudah memadai bagi mereka.", src: "al-Quran 103, 108, 110; Tafsir Ibn Kathir" },
    { ar: "فأسقيناكموه", title: "Salah satu perkataan terpanjang", body: "“fa-asqaynākumūhu” – “dan Kami beri kamu meminumnya” (15:22) – mempunyai sebelas huruf dan merupakan salah satu perkataan terpanjang dalam al-Quran.", src: "al-Quran 15:22" },
    { ar: "عمّ", title: "Bahagian terakhir: 37 surah", body: "Juzuk ketiga puluh, Juzuk Amma, mengandungi 37 surah (78–114) – surah-surah yang paling awal dihafal oleh kebanyakan umat Islam.", src: "al-Quran 78–114" },
  ],
  readTitle: "Sesiapa yang membaca al-Quran – apa yang dijanjikan kepadanya",
  readLead: "Al-Quran bukan kitab yang dibaca sekali lalu disimpan. Sabda Nabi ﷺ ini diriwayatkan dengan sahih:",
  hadith: [
    { text: "“Sesiapa membaca satu huruf daripada Kitab Allah, dia mendapat satu kebaikan, dan satu kebaikan digandakan sepuluh kali. Aku tidak mengatakan Alif-Lām-Mīm itu satu huruf – tetapi Alif satu huruf, Lām satu huruf dan Mīm satu huruf.”", src: "at-Tirmizi 2910" },
    { text: "“Bacalah al-Quran, kerana pada hari kiamat ia akan datang sebagai pemberi syafaat kepada orang yang membacanya.”", src: "Sahih Muslim 804" },
    { text: "“Sebaik-baik kamu ialah orang yang mempelajari al-Quran dan mengajarkannya.”", src: "Sahih al-Bukhari 5027" },
    { text: "“Orang yang mahir dengan al-Quran bersama para penulis yang mulia lagi taat. Dan orang yang membacanya dengan tersekat-sekat kerana merasa sukar, dia mendapat dua pahala.”", src: "Sahih al-Bukhari 4937, Sahih Muslim 798" },
    { text: "“Akan dikatakan kepada sahabat al-Quran: Bacalah dan naiklah, dan alunkanlah sebagaimana kamu mengalunkannya di dunia – kedudukanmu ialah pada ayat terakhir yang kamu baca.”", src: "Abu Daud 1464, at-Tirmizi 2914" },
  ],
  wealthTitle: "Keberkatan, rezeki, kemakmuran",
  wealthLead: "Al-Quran tidak menjanjikan formula wang cepat. Ia menjanjikan sesuatu yang lebih besar: barakah – keberkatan yang menjadikan sedikit terasa cukup –, kehidupan yang baik dan rezeki dari arah yang tidak disangka-sangka. Inilah firman-Nya sendiri (dari segi maknanya):",
  promises: [
    { ref: "71:10-12", title: "Memohon keampunan", text: "“Mohonlah keampunan daripada Tuhanmu – sesungguhnya Dia Maha Pengampun. Dia akan menurunkan hujan yang lebat kepadamu, menambah harta dan anak-anakmu, serta mengurniakan kebun-kebun dan sungai-sungai untukmu.”" },
    { ref: "14:7", title: "Kesyukuran", text: "“Jika kamu bersyukur, Aku pasti akan menambah (nikmat) kepadamu.”" },
    { ref: "65:2-3", title: "Takwa dan tawakal", text: "“Sesiapa bertakwa kepada Allah, Dia akan menyediakan jalan keluar baginya dan mengurniakan rezeki kepadanya dari arah yang tidak disangka-sangka. Dan sesiapa bertawakal kepada Allah, Dia mencukupkan (keperluan)nya.”" },
    { ref: "7:96", title: "Keberkatan untuk seluruh negeri", text: "“Sekiranya penduduk negeri-negeri itu beriman dan bertakwa, pasti Kami bukakan kepada mereka keberkatan dari langit dan bumi.”" },
    { ref: "16:97", title: "Kehidupan yang baik", text: "“Sesiapa melakukan amal soleh, lelaki mahupun perempuan, sedang dia beriman, pasti Kami berikan kepadanya kehidupan yang baik.”" },
    { ref: "35:29-30", title: "Perniagaan yang tidak pernah rugi", text: "“Orang yang membaca Kitab Allah, mendirikan solat dan membelanjakan sebahagian rezeki yang Kami kurniakan kepada mereka, mengharapkan perniagaan yang tidak akan binasa.”" },
    { ref: "13:28", title: "Ketenangan untuk hati", text: "“Ketahuilah, dengan mengingati Allah hati menjadi tenang.”" },
    { ref: "17:82", title: "Penyembuh", text: "“Kami turunkan daripada al-Quran sesuatu yang menjadi penawar dan rahmat bagi orang yang beriman.”" },
  ],
  wealthNote: "Jadi, banyak membaca al-Quran tidak menjadikan sesiapa kaya “secara automatik” – tetapi ia menjadikan kita kaya dengan apa yang kekal: ketenangan, kesyukuran, tawakal dan pahala yang tidak berakhir. Dan sesiapa yang bekerja dengan jujur, bersyukur dan memohon keampunan boleh berharap pada rezeki Allah.",
  wealthHadith: { text: "“Kekayaan bukanlah banyaknya harta benda; kekayaan ialah kekayaan jiwa.”", src: "Sahih al-Bukhari 6446, Sahih Muslim 1051" },
  placesTitle: "Tempat di mana hati menemui kedamaian",
  placesLead: "Kedamaian bersama Allah boleh ditemui di mana-mana – Dia dekat. Tetapi ada tempat dan waktu yang Dia berkati secara khusus.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masjid al-Haram, Makkah", body: "Rumah Allah, Kaabah, arah setiap solat. Satu solat di sana lebih utama daripada seratus ribu solat di tempat lain.", src: "Ibn Majah 1406 (dinilai sahih oleh para ulama)" },
    { ar: "المسجد النبوي", title: "Masjid Nabawi, Madinah", body: "Satu solat di sana lebih baik daripada seribu solat di tempat lain – kecuali Masjidil Haram. Dan antara rumah baginda dengan mimbarnya terdapat “sebuah taman daripada taman-taman syurga”.", src: "Sahih al-Bukhari 1190, 1196; Sahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masjid al-Aqsa, Baitulmaqdis", body: "Kiblat pertama, yang sekelilingnya telah Allah berkati (17:1) – salah satu daripada tiga masjid yang khusus dituju untuk bermusafir.", src: "Sahih al-Bukhari 1189, Sahih Muslim 1397" },
    { ar: "بيوت الله", title: "Setiap masjid", body: "Tempat yang paling dikasihi Allah ialah masjid. Dan di mana orang berkumpul di sana, membaca al-Quran dan mempelajarinya bersama-sama, ketenangan (sakīnah) turun ke atas mereka, rahmat meliputi mereka dan para malaikat mengelilingi mereka.", src: "Sahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Rumah anda", body: "“Janganlah jadikan rumah kamu seperti perkuburan. Syaitan lari daripada rumah yang di dalamnya dibaca surah al-Baqarah.” Tempat tetap untuk bacaan harian anda menjadikan rumah anda tempat yang aman damai.", src: "Sahih Muslim 780" },
    { ar: "الثلث الأخير", title: "Sepertiga malam terakhir", body: "Satu tempat dalam masa: pada sepertiga malam yang terakhir setiap malam Allah menyeru: “Siapa yang berdoa kepada-Ku, nescaya Aku perkenankan? Siapa yang memohon kepada-Ku, nescaya Aku berikan?”", src: "Sahih al-Bukhari 1145, Sahih Muslim 758" },
    { ar: "آيات الكون", title: "Dalam ciptaan", body: "“Sesungguhnya pada penciptaan langit dan bumi serta pertukaran malam dan siang terdapat tanda-tanda bagi orang yang berakal” – iaitu mereka yang mengingati Allah sambil berdiri, duduk dan berbaring (3:190–191).", src: "al-Quran 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "Di Emiriah", body: "Masjid Agung Sheikh Zayed di Abu Dhabi, Masjid Jumeirah di Dubai dan masjid-masjid besar di Sharjah mengalu-alukan pengunjung – tempat yang tenang di tengah kehidupan.", src: "", href: "/islam/mosques" },
  ],
  note: "Hadis diberikan bersama koleksi dan nombornya. Ayat-ayat disampaikan dari segi maknanya; sentuh sesuatu rujukan untuk membaca lafaz Arab dan terjemahan yang diiktiraf. Untuk soalan tentang hukum, sila rujuk ulama.",
  ctaTitle: "Jangan berhenti pada kekaguman",
  ctaBody: "Setiap huruf dikira sepuluh kali ganda. Mulakan hari ini dengan satu ayat – Kaedah Shams membimbing anda langkah demi langkah.",
  cta: "Pelajari ayat pertama anda",
};
export default c;
