import type { SecretsContent } from "../../secrets/content";
const c: SecretsContent = {
  kicker: "Diperiksa, bukan ditebak",
  title: "Rahasia Al-Qur’an",
  lead: "Banyak angka dan “keajaiban” tentang Al-Qur’an yang beredar – sebagian benar, sebagian tidak. Di sini kami menghitung sendiri, dalam teks Utsmani yang lengkap, dan menyampaikan secara terbuka apa yang terbukti. Ditambah: apa yang dijanjikan bagi orang yang membaca Al-Qur’an, dan di mana hati paling mudah menemukan ketenangan.",
  counterTitle: "Berapa kali ini muncul dalam Al-Qur’an?",
  counterLead: "Ketuk sebuah kata. Kamu akan melihat berapa kali kata itu muncul – dan setiap tempatnya, siap dibaca.",
  method: "Dihitung dalam teks Utsmani Kompleks Raja Fahd di Madinah (6.236 ayat, hitungan Hafs). Bentuk kata dihitung dengan kata sandang dan partikel awalan (wa-, fa-, bi-, li-, ka-), tanpa kata ganti yang menempel; pada nama-nama, juga dengan seruan “yā”. Cara menghitung lain dapat menghasilkan angka yang sedikit berbeda – karena itu kami menyebutkan metodenya.",
  times: "kali", spots: "tempat", open: "Buka", allahNote: "Untuk “Allah” kami hanya menampilkan angkanya – tempatnya terlalu banyak untuk sebuah daftar.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "“Jangan takut”" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "“Tidak ada ketakutan atas mereka”" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "Ar-Rahman (Yang Maha Pengasih)" },
    { key: "yawm", ar: "يَوْم", label: "Hari" },
    { key: "shahr", ar: "شَهْر", label: "Bulan" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "Dunia" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "Akhirat" },
    { key: "musa", ar: "مُوسَىٰ", label: "Musa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nuh" },
    { key: "yusuf", ar: "يُوسُف", label: "Yusuf" },
    { key: "isa", ar: "عِيسَىٰ", label: "Isa" },
    { key: "adam", ar: "ءَادَم", label: "Adam" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Klaim populer – dihitung ulang",
  claimsLead: "Apa yang dibagikan di media sosial sering kali berniat baik. Tetapi Al-Qur’an tidak membutuhkan angka karangan. Kami memeriksa setiap pernyataan sendiri.",
  verdicts: { true: "Benar", false: "Kurang tepat", method: "Benar – dengan cara menghitung ini" },
  claims: [
    { q: "“Jangan takut” muncul 365 kali dalam Al-Qur’an – satu kali untuk setiap hari dalam setahun.", v: "false", key: "fearNot", a: "Sebagai perintah langsung – “lā takhaf”, “lā takhāfī”, “lā takhāfū”, “lā takhāfā” – kata ini muncul 13 kali: diucapkan kepada Ibrahim, kepada Musa dan Harun, kepada ibu Musa, kepada Luth, kepada Dawud, dan kepada orang-orang beriman. Ditambah lagi 13 kali janji “tidak ada ketakutan atas mereka, dan mereka tidak akan bersedih”. Totalnya 26 tempat – lebih sedikit daripada yang diklaim, tetapi setiap tempat adalah penghiburan." },
    { q: "Kata “hari” muncul 365 kali dalam Al-Qur’an.", v: "method", key: "yawm", a: "Jika kita menghitung bentuk tunggal “yawm” dan “yawman” – dengan kata sandang dan partikel, tetapi tanpa kata ganti yang menempel dan tanpa “yawma’idhin” (pada hari itu) – hasilnya tepat 365 tempat. Dengan cara menghitung lain, angkanya berbeda. Tetap saja ini menakjubkan." },
    { q: "Kata “bulan” muncul 12 kali dalam Al-Qur’an.", v: "true", key: "shahr", a: "Dalam bentuk tunggal (“shahr”, “ash-shahr”, “shahran”) ada 12 tempat. Dan Al-Qur’an sendiri berfirman: “Sesungguhnya jumlah bulan di sisi Allah ada dua belas” (9:36)." },
    { q: "“Dunia” dan “akhirat” muncul sama banyak – masing-masing 115 kali.", v: "method", key: "dunya", a: "Dihitung dengan kata sandang dan partikel: ad-dunyā 115 kali, al-ākhira 115 kali. Tidak dihitung 3:72, karena di sana “ākhirahu” berarti “ujungnya” (dari hari itu), bukan akhirat." },
    { q: "Nama “Allah” muncul 2.699 kali dalam Al-Qur’an.", v: "true", key: "allah", a: "Dihitung dengan semua awalan seperti wallāhi, billāhi, lillāhi, jumlahnya 2.699 tempat (tanpa “Allāhumma”). Ini sesuai dengan penghitungan yang dikenal." },
    { q: "Musa adalah nabi yang paling sering disebut.", v: "true", key: "musa", a: "Musa disebut namanya 136 kali – lebih banyak daripada nabi mana pun. Berikutnya Ibrahim (69), Nuh (43), Yusuf (27), Isa dan Adam (masing-masing 25)." },
    { q: "Maryam adalah satu-satunya perempuan yang disebut namanya dalam Al-Qur’an.", v: "true", key: "maryam", a: "Ya. Namanya muncul 34 kali, dan satu surah penuh memakai namanya: surah 19, Maryam." },
    { q: "Nabi Muhammad ﷺ hanya empat kali disebut namanya.", v: "true", key: "muhammad", a: "Empat kali sebagai “Muhammad” (3:144, 33:40, 47:2, 48:29) dan satu kali sebagai “Ahmad” (61:6) – di banyak tempat lain Allah menyapanya dengan “Wahai Nabi” dan “Wahai Rasul”." },
  ],
  factsTitle: "Yang benar-benar menakjubkan – beserta sumbernya",
  facts: [
    { ar: "الفاتحة", title: "Surah terbesar", body: "Nabi ﷺ menyebut Al-Fatihah sebagai surah terbesar dalam Al-Qur’an dan “tujuh ayat yang diulang-ulang” – dibaca dalam setiap rakaat shalat.", src: "Shahih al-Bukhari 4474" },
    { ar: "آية الكرسي", title: "Ayat terbesar", body: "Ayat Kursi (2:255) adalah ayat terbesar dalam Kitab Allah – demikian Nabi ﷺ mengajarkannya kepada sahabatnya, Ubay bin Ka‘b.", src: "Shahih Muslim 810" },
    { ar: "الإخلاص", title: "Sepertiga Al-Qur’an", body: "Surah Al-Ikhlas (112) setara dengan sepertiga Al-Qur’an – empat ayat pendek tentang keesaan Allah.", src: "Shahih al-Bukhari 5013" },
    { ar: "اقرأ", title: "Kata pertama", body: "Wahyu pertama di Gua Hira diawali dengan “Bacalah!” (96:1–5). Al-Qur’an memulai turunnya dengan ilmu.", src: "Shahih al-Bukhari 3" },
    { ar: "البسملة", title: "114 basmalah", body: "“Bismillāh ar-Raḥmān ar-Raḥīm” terdapat di awal 113 surah – semuanya kecuali At-Taubah – dan sekali di tengah sebuah surah: dalam surat Sulaiman kepada Ratu Saba (27:30). Totalnya 114, sebanyak jumlah surah.", src: "Al-Qur’an 27:30" },
    { ar: "الدَّين", title: "Ayat terpanjang", body: "Ayat terpanjang adalah “ayat utang” (2:282): ayat ini mengatur cara mencatat utang secara tertulis – tanda betapa seriusnya Al-Qur’an memandang keadilan dalam kehidupan sehari-hari.", src: "Al-Qur’an 2:282" },
    { ar: "الكوثر", title: "Surah terpendek", body: "Al-Kautsar (108) terdiri atas tiga ayat dan sepuluh kata. Surah terpanjang, Al-Baqarah, terdiri atas 286 ayat.", src: "Al-Qur’an 108, 2" },
    { ar: "١١٤", title: "114 surah, 6.236 ayat", body: "Al-Qur’an terdiri atas 114 surah dan 6.236 ayat (hitungan Hafs), terbagi menjadi 30 juz. Teks kami berisi 77.429 kata – tergantung cara menghitung, yang lain menyebut angka yang sedikit berbeda.", src: "Teks Utsmani, Kompleks Raja Fahd" },
  ],
  moreTitle: "Rahasia lainnya",
  more: [
    { ar: "التوبة", title: "Surah tanpa basmalah", body: "At-Taubah (surah 9) adalah satu-satunya surah yang tidak diawali dengan “Bismillāh ar-Raḥmān ar-Raḥīm”. Para ulama menyebut berbagai alasan – misalnya karena surah ini dibuka dengan pernyataan tegas pemutusan hubungan (bara’ah).", src: "Al-Qur’an 9:1" },
    { ar: "النمل", title: "Surah dengan dua basmalah", body: "An-Naml (surah 27) memuat basmalah dua kali: di awalnya dan pada ayat 30, dalam surat Sulaiman kepada Ratu Saba.", src: "Al-Qur’an 27:30" },
    { ar: "المجادلة", title: "Allah di setiap ayat", body: "Dalam surah Al-Mujadilah (58) nama “Allah” muncul di setiap ayatnya yang berjumlah 22 – kami memeriksa satu per satu.", src: "Al-Qur’an 58" },
    { ar: "الرحمن", title: "Pertanyaan yang sama 31 kali", body: "Dalam surah Ar-Rahman (55) satu pertanyaan berulang 31 kali: “Maka nikmat Tuhanmu yang manakah yang kamu dustakan?”", src: "Al-Qur’an 55:13" },
    { ar: "المرسلات", title: "Sepuluh kali: “Celakalah pada hari itu …”", body: "Surah Al-Mursalat (77) mengulang sepuluh kali: “Celakalah pada hari itu bagi orang-orang yang mendustakan!”", src: "Al-Qur’an 77:15" },
    { ar: "أبجد", title: "Seluruh 28 huruf dalam satu ayat", body: "Hanya dua ayat yang memuat seluruh 28 huruf abjad Arab: 3:154 dan 48:29, ayat yang menggambarkan para sahabat Nabi ﷺ.", src: "Al-Qur’an 3:154, 48:29" },
    { ar: "الم", title: "29 surah dengan huruf-huruf misterius", body: "29 surah diawali dengan huruf-huruf tunggal seperti Alif Lam Mim, Ya Sin, atau Qaf. Maknanya hanya Allah yang mengetahui – banyak ulama melihat di dalamnya tanda bahwa Al-Qur’an tersusun dari huruf-huruf ini juga, namun tidak dapat ditiru.", src: "mis. Al-Qur’an 2:1, 36:1, 50:1" },
    { ar: "يونس", title: "Surah bernama nabi", body: "Enam surah memakai nama seorang nabi: Yunus, Hud, Yusuf, Ibrahim, Muhammad ﷺ, dan Nuh. Dan satu surah memakai nama seorang perempuan: Maryam.", src: "Al-Qur’an 10, 11, 12, 14, 47, 71, 19" },
    { ar: "مكية", title: "86 surah Makkiyah, 28 surah Madaniyah", body: "Menurut penggolongan dalam Mushaf Madinah, 86 surah diturunkan di Makkah dan 28 di Madinah. Surah-surah Makkiyah terutama berbicara tentang iman, sedangkan surah-surah Madaniyah juga tentang kehidupan bermasyarakat.", src: "Mushaf Madinah" },
    { ar: "سجدة", title: "Tempat-tempat sujud", body: "Di 15 tempat Mushaf Madinah menandai sujud saat membaca (sujud tilawah). Para mazhab menghitungnya 14 atau 15.", src: "mis. Al-Qur’an 7:206, 96:19" },
    { ar: "العصر", title: "Tiga surah dengan tiga ayat", body: "Al-‘Ashr, Al-Kautsar, dan An-Nashr masing-masing hanya terdiri atas tiga ayat. Imam asy-Syafi‘i diriwayatkan berkata: seandainya manusia hanya merenungkan surah Al-‘Ashr, itu sudah cukup bagi mereka.", src: "Al-Qur’an 103, 108, 110; Tafsir Ibnu Katsir" },
    { ar: "فأسقيناكموه", title: "Salah satu kata terpanjang", body: "“fa-asqaynākumūhu” – “lalu Kami beri kamu minum dengannya” (15:22) – terdiri atas sebelas huruf dan merupakan salah satu kata terpanjang dalam Al-Qur’an.", src: "Al-Qur’an 15:22" },
    { ar: "عمّ", title: "Bagian terakhir: 37 surah", body: "Juz ketiga puluh, Juz Amma, memuat 37 surah (78–114) – surah-surah yang paling dahulu dihafal oleh kebanyakan Muslim.", src: "Al-Qur’an 78–114" },
  ],
  readTitle: "Siapa yang membaca Al-Qur’an – apa yang dijanjikan baginya",
  readLead: "Al-Qur’an bukan kitab yang dibaca sekali lalu disimpan. Sabda-sabda Nabi ﷺ berikut ini diriwayatkan dengan sahih:",
  hadith: [
    { text: "“Barang siapa membaca satu huruf dari Kitab Allah, ia mendapat satu kebaikan, dan satu kebaikan dilipatgandakan sepuluh kali. Aku tidak mengatakan bahwa Alif-Lām-Mīm itu satu huruf – tetapi Alif satu huruf, Lām satu huruf, dan Mīm satu huruf.”", src: "at-Tirmidzi 2910" },
    { text: "“Bacalah Al-Qur’an, karena pada hari kiamat ia akan datang sebagai pemberi syafaat bagi orang-orang yang membacanya.”", src: "Shahih Muslim 804" },
    { text: "“Yang terbaik di antara kalian adalah orang yang mempelajari Al-Qur’an dan mengajarkannya.”", src: "Shahih al-Bukhari 5027" },
    { text: "“Orang yang mahir dalam Al-Qur’an bersama para penulis yang mulia lagi taat. Dan orang yang membacanya dengan terbata-bata karena merasa sulit, baginya dua pahala.”", src: "Shahih al-Bukhari 4937, Shahih Muslim 798" },
    { text: "“Dikatakan kepada sahabat Al-Qur’an: Bacalah dan naiklah, dan lantunkanlah sebagaimana engkau dahulu melantunkan di dunia – kedudukanmu ada pada ayat terakhir yang engkau baca.”", src: "Abu Dawud 1464, at-Tirmidzi 2914" },
  ],
  wealthTitle: "Berkah, rezeki, kemakmuran",
  wealthLead: "Al-Qur’an tidak menjanjikan rumus uang cepat. Ia menjanjikan sesuatu yang lebih besar: barakah – berkah yang membuat yang sedikit terasa cukup –, kehidupan yang baik, dan rezeki dari arah yang tidak disangka-sangka. Inilah firman-Nya sendiri (maknanya):",
  promises: [
    { ref: "71:10-12", title: "Memohon ampun", text: "“Mohonlah ampun kepada Tuhanmu – sungguh Dia Maha Pengampun. Dia akan menurunkan hujan yang lebat kepadamu, memperbanyak harta dan anak-anakmu, serta mengadakan kebun-kebun dan sungai-sungai untukmu.”" },
    { ref: "14:7", title: "Syukur", text: "“Jika kamu bersyukur, Aku pasti akan menambah (nikmat) kepadamu.”" },
    { ref: "65:2-3", title: "Takwa dan tawakal", text: "“Barang siapa bertakwa kepada Allah, Dia akan membukakan jalan keluar baginya dan memberinya rezeki dari arah yang tidak disangka-sangka. Dan barang siapa bertawakal kepada Allah, Dia akan mencukupkan (keperluan)nya.”" },
    { ref: "7:96", title: "Berkah bagi seluruh negeri", text: "“Sekiranya penduduk negeri-negeri itu beriman dan bertakwa, pasti Kami akan membukakan bagi mereka berkah dari langit dan bumi.”" },
    { ref: "16:97", title: "Kehidupan yang baik", text: "“Barang siapa mengerjakan kebajikan, laki-laki maupun perempuan, sedang dia beriman, pasti akan Kami berikan kepadanya kehidupan yang baik.”" },
    { ref: "35:29-30", title: "Perniagaan yang tidak pernah rugi", text: "“Orang-orang yang membaca Kitab Allah, mendirikan shalat, dan menginfakkan sebagian rezeki yang Kami berikan kepada mereka, mengharapkan perniagaan yang tidak akan pernah rugi.”" },
    { ref: "13:28", title: "Ketenangan bagi hati", text: "“Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram.”" },
    { ref: "17:82", title: "Penyembuh", text: "“Kami turunkan dari Al-Qur’an sesuatu yang menjadi penyembuh dan rahmat bagi orang-orang yang beriman.”" },
  ],
  wealthNote: "Jadi, banyak membaca Al-Qur’an tidak membuat seseorang kaya “secara otomatis” – tetapi ia menjadi kaya akan apa yang kekal: ketenangan, rasa syukur, tawakal, dan pahala yang tak berhenti. Dan siapa yang bekerja dengan jujur, bersyukur, dan memohon ampun, boleh berharap pada rezeki dari Allah.",
  wealthHadith: { text: "“Kekayaan bukanlah banyaknya harta, tetapi kekayaan adalah kekayaan jiwa.”", src: "Shahih al-Bukhari 6446, Shahih Muslim 1051" },
  placesTitle: "Tempat-tempat di mana hati menemukan kedamaian",
  placesLead: "Kedamaian bersama Allah dapat ditemukan di mana saja – Dia dekat. Tetapi ada tempat dan waktu yang Dia berkahi secara khusus.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masjid al-Haram, Makkah", body: "Rumah Allah, Ka’bah, arah setiap shalat. Satu shalat di sana lebih utama daripada seratus ribu shalat di tempat lain.", src: "Ibnu Majah 1406 (dinilai sahih oleh para ulama)" },
    { ar: "المسجد النبوي", title: "Masjid Nabawi, Madinah", body: "Satu shalat di sana lebih baik daripada seribu shalat di tempat lain – kecuali Masjidil Haram. Dan antara rumah dan mimbar beliau terdapat “sebuah taman dari taman-taman surga”.", src: "Shahih al-Bukhari 1190, 1196; Shahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masjid al-Aqsa, Yerusalem", body: "Kiblat pertama, yang sekelilingnya telah Allah berkahi (17:1) – salah satu dari tiga masjid yang secara khusus dituju dalam perjalanan.", src: "Shahih al-Bukhari 1189, Shahih Muslim 1397" },
    { ar: "بيوت الله", title: "Setiap masjid", body: "Tempat yang paling dicintai Allah adalah masjid-masjid. Dan di mana orang-orang berkumpul di sana, membaca Al-Qur’an, dan mempelajarinya bersama, ketenangan (sakīnah) turun kepada mereka, rahmat menyelimuti mereka, dan para malaikat mengelilingi mereka.", src: "Shahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Rumahmu", body: "“Janganlah jadikan rumah-rumah kalian seperti kuburan. Setan lari dari rumah yang di dalamnya dibaca surah Al-Baqarah.” Tempat tetap untuk bacaan harianmu menjadikan rumahmu tempat yang damai.", src: "Shahih Muslim 780" },
    { ar: "الثلث الأخير", title: "Sepertiga malam terakhir", body: "Sebuah tempat dalam waktu: pada sepertiga malam terakhir setiap malam Allah menyeru: “Siapa yang berdoa kepada-Ku, niscaya Aku kabulkan? Siapa yang memohon kepada-Ku, niscaya Aku beri?”", src: "Shahih al-Bukhari 1145, Shahih Muslim 758" },
    { ar: "آيات الكون", title: "Dalam ciptaan", body: "“Sesungguhnya dalam penciptaan langit dan bumi serta pergantian malam dan siang terdapat tanda-tanda bagi orang yang berakal” – yaitu mereka yang mengingat Allah sambil berdiri, duduk, dan berbaring (3:190–191).", src: "Al-Qur’an 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "Di Emirat", body: "Masjid Agung Syekh Zayed di Abu Dhabi, Masjid Jumeirah di Dubai, dan masjid-masjid besar di Sharjah menyambut para pengunjung – tempat-tempat hening di tengah kehidupan.", src: "", href: "/islam/mosques" },
  ],
  note: "Hadis disebutkan beserta kitab dan nomornya. Ayat-ayat disampaikan maknanya; ketuk rujukan untuk membaca lafal Arab dan terjemahan yang diakui. Untuk pertanyaan tentang hukum, silakan bertanya kepada ulama.",
  ctaTitle: "Jangan berhenti pada rasa kagum",
  ctaBody: "Setiap huruf dihitung sepuluh kali lipat. Mulailah hari ini dengan satu ayat – Metode Shams menuntunmu langkah demi langkah.",
  cta: "Pelajari ayat pertamamu",
};
export default c;
