import type { SecretsContent } from "../../secrets/content";
const c: SecretsContent = {
  kicker: "Comprobado, no supuesto",
  title: "Los secretos del Corán",
  lead: "Sobre el Corán circulan muchas cifras y «milagros»: algunos son ciertos y otros no. Aquí contamos nosotros mismos, en el texto uzmaní (Uthmani) completo, y decimos abiertamente lo que está comprobado. Además: lo que se promete a quien lee el Corán, y dónde el corazón encuentra paz con más facilidad.",
  counterTitle: "¿Cuántas veces aparece esto en el Corán?",
  counterLead: "Toca una palabra. Verás cuántas veces aparece, y cada uno de los lugares, listo para leer.",
  method: "Contado en el texto uzmaní (Uthmani) del Complejo del Rey Fahd en Medina (6.236 aleyas, recuento de Hafs). Se cuentan las formas de la palabra con el artículo y las partículas prefijadas (wa-, fa-, bi-, li-, ka-), sin los pronombres sufijos; en los nombres, también con la partícula vocativa «yā». Otras maneras de contar pueden dar cifras ligeramente distintas; por eso indicamos el método.",
  times: "veces", spots: "lugares", open: "Abrir", allahNote: "Para «Allah» solo mostramos la cifra: los lugares serían demasiados para una lista.",
  words: [
    { key: "fearNot", ar: "لَا تَخَفْ", label: "«No temas»" },
    { key: "noFear", ar: "لَا خَوْفٌ عَلَيْهِمْ", label: "«No hay temor sobre ellos»" },
    { key: "allah", ar: "ٱللَّه", label: "Allah" },
    { key: "rahman", ar: "ٱلرَّحْمَـٰن", label: "El Misericordioso" },
    { key: "yawm", ar: "يَوْم", label: "Día" },
    { key: "shahr", ar: "شَهْر", label: "Mes" },
    { key: "dunya", ar: "ٱلدُّنْيَا", label: "Esta vida" },
    { key: "akhira", ar: "ٱلْـَٔاخِرَة", label: "La otra vida" },
    { key: "musa", ar: "مُوسَىٰ", label: "Musa" },
    { key: "ibrahim", ar: "إِبْرَٰهِيم", label: "Ibrahim" },
    { key: "nuh", ar: "نُوح", label: "Nuh" },
    { key: "yusuf", ar: "يُوسُف", label: "Yusuf" },
    { key: "isa", ar: "عِيسَىٰ", label: "Isa" },
    { key: "adam", ar: "ءَادَم", label: "Adán" },
    { key: "maryam", ar: "مَرْيَم", label: "Maryam" },
    { key: "muhammad", ar: "مُحَمَّد", label: "Muhammad ﷺ" },
    { key: "ahmad", ar: "أَحْمَد", label: "Ahmad ﷺ" },
  ],
  claimsTitle: "Afirmaciones populares: contadas de nuevo",
  claimsLead: "Lo que se comparte en las redes sociales suele hacerse con buena intención. Pero el Corán no necesita cifras inventadas. Hemos comprobado cada afirmación nosotros mismos.",
  verdicts: { true: "Cierto", false: "No exactamente", method: "Cierto, con esta manera de contar" },
  claims: [
    { q: "«No temas» aparece 365 veces en el Corán: una por cada día del año.", v: "false", key: "fearNot", a: "Como orden directa –«lā takhaf», «lā takhāfī», «lā takhāfū», «lā takhāfā»– aparece 13 veces: dicho a Ibrahim, a Musa y Harun, a la madre de Musa, a Lut, a Dawud y a los creyentes. A ello se suma, 13 veces, la promesa «no habrá temor sobre ellos ni se entristecerán». En total, 26 lugares: menos de lo que se afirma, pero cada uno de ellos es un consuelo." },
    { q: "La palabra «día» aparece 365 veces en el Corán.", v: "method", key: "yawm", a: "Si se cuenta el singular «yawm» y «yawman» –con artículo y partículas, pero sin pronombres sufijos y sin «yawma’idhin» (en aquel día)–, salen exactamente 365 lugares. Con otras maneras de contar salen otras cifras. Sigue siendo notable." },
    { q: "La palabra «mes» aparece 12 veces en el Corán.", v: "true", key: "shahr", a: "En singular («shahr», «ash-shahr», «shahran») hay 12 lugares. Y el propio Corán dice: «El número de los meses ante Allah es de doce» (9:36)." },
    { q: "«Esta vida» y «la otra vida» aparecen con la misma frecuencia: 115 veces cada una.", v: "method", key: "dunya", a: "Contadas con artículo y partículas: ad-dunyā 115 veces, al-ākhira 115 veces. No se cuenta 3:72, donde «ākhirahu» significa «su final» (del día) y no la otra vida." },
    { q: "El nombre «Allah» aparece 2.699 veces en el Corán.", v: "true", key: "allah", a: "Contado con todos los prefijos, como wallāhi, billāhi, lillāhi, hay 2.699 lugares (sin «Allāhumma»). Coincide con los recuentos conocidos." },
    { q: "Musa es el profeta más mencionado.", v: "true", key: "musa", a: "Musa es nombrado 136 veces, más que cualquier otro profeta. Le siguen Ibrahim (69), Nuh (43), Yusuf (27), Isa y Adán (25 cada uno)." },
    { q: "Maryam es la única mujer mencionada por su nombre en el Corán.", v: "true", key: "maryam", a: "Sí. Su nombre aparece 34 veces, y toda una sura lleva su nombre: la sura 19, Maryam." },
    { q: "El Profeta Muhammad ﷺ solo es mencionado por su nombre cuatro veces.", v: "true", key: "muhammad", a: "Cuatro veces como «Muhammad» (3:144, 33:40, 47:2, 48:29) y una vez como «Ahmad» (61:6); en muchos otros lugares Allah se dirige a él como «¡Oh Profeta!» y «¡Oh Mensajero!»." },
  ],
  factsTitle: "Lo que de verdad asombra, con su fuente",
  facts: [
    { ar: "الفاتحة", title: "La sura más grande", body: "El Profeta ﷺ llamó a Al-Fatiha la sura más grande del Corán y «las siete que se repiten con frecuencia»: se recita en cada unidad de la oración.", src: "Sahih al-Bujari 4474" },
    { ar: "آية الكرسي", title: "La aleya más grande", body: "Āyat al-Kursī (2:255) es la aleya más grande del Libro de Allah: así se lo enseñó el Profeta ﷺ a su compañero Ubayy ibn Ka‘b.", src: "Sahih Muslim 810" },
    { ar: "الإخلاص", title: "Un tercio del Corán", body: "La sura Al-Ijlas (112) equivale a un tercio del Corán: cuatro aleyas breves sobre la unicidad de Allah.", src: "Sahih al-Bujari 5013" },
    { ar: "اقرأ", title: "La primera palabra", body: "La primera revelación en la cueva de Hira comienza con «¡Lee!» (96:1–5). El Corán comienza su descenso con el conocimiento.", src: "Sahih al-Bujari 3" },
    { ar: "البسملة", title: "114 basmalas", body: "«Bismillāh ar-Raḥmān ar-Raḥīm» figura al comienzo de 113 suras (todas salvo At-Tawba) y una vez dentro de una sura: en la carta de Sulayman a la reina de Saba (27:30). En total 114, tantas como suras.", src: "Corán 27:30" },
    { ar: "الدَّين", title: "La aleya más larga", body: "La aleya más larga es la «aleya de la deuda» (2:282): establece cómo registrar por escrito las deudas, señal de lo en serio que el Corán se toma la justicia en la vida diaria.", src: "Corán 2:282" },
    { ar: "الكوثر", title: "La sura más corta", body: "Al-Kawzar (108) tiene tres aleyas y diez palabras. La sura más larga, Al-Baqara, tiene 286 aleyas.", src: "Corán 108, 2" },
    { ar: "١١٤", title: "114 suras, 6.236 aleyas", body: "El Corán tiene 114 suras y 6.236 aleyas (recuento de Hafs), divididas en 30 partes. Nuestro texto tiene 77.429 palabras; según la manera de contar, otros dan cifras ligeramente distintas.", src: "Texto uzmaní (Uthmani), Complejo del Rey Fahd" },
  ],
  moreTitle: "Más secretos",
  more: [
    { ar: "التوبة", title: "La sura sin basmala", body: "At-Tawba (sura 9) es la única sura que no comienza con «Bismillāh ar-Raḥmān ar-Raḥīm». Los sabios dan varias razones, por ejemplo que se abre con una solemne declaración de desvinculación.", src: "Corán 9:1" },
    { ar: "النمل", title: "La sura con dos basmalas", body: "An-Naml (sura 27) tiene la basmala dos veces: al comienzo y en la aleya 30, en la carta de Sulayman a la reina de Saba.", src: "Corán 27:30" },
    { ar: "المجادلة", title: "Allah en cada aleya", body: "En la sura Al-Muyadala (58) el nombre «Allah» aparece en cada una de sus 22 aleyas; las hemos comprobado una por una.", src: "Corán 58" },
    { ar: "الرحمن", title: "La misma pregunta 31 veces", body: "En la sura Ar-Rahman (55) una misma pregunta vuelve 31 veces: «¿Cuál, pues, de los beneficios de vuestro Señor negaréis?»", src: "Corán 55:13" },
    { ar: "المرسلات", title: "Diez veces: «Ay, ese día …»", body: "La sura Al-Mursalat (77) repite diez veces: «¡Ay, ese día, de los desmentidores!»", src: "Corán 77:15" },
    { ar: "أبجد", title: "Las 28 letras en una aleya", body: "Solo dos aleyas contienen cada una de las 28 letras del alfabeto árabe: 3:154 y 48:29, la aleya que describe a los compañeros del Profeta ﷺ.", src: "Corán 3:154, 48:29" },
    { ar: "الم", title: "29 suras con letras misteriosas", body: "29 suras comienzan con letras sueltas como Alif-Lam-Mim, Ya-Sin o Qaf. Su significado solo lo conoce Allah; muchos sabios ven en ellas una señal de que el Corán está hecho exactamente de estas letras y, sin embargo, es inimitable.", src: "p. ej. Corán 2:1, 36:1, 50:1" },
    { ar: "يونس", title: "Suras con nombres de profetas", body: "Seis suras llevan el nombre de un profeta: Yunus, Hud, Yusuf, Ibrahim, Muhammad ﷺ y Nuh. Y una sura lleva el nombre de una mujer: Maryam.", src: "Corán 10, 11, 12, 14, 47, 71, 19" },
    { ar: "مكية", title: "86 suras mequíes, 28 medinenses", body: "Según la clasificación del mushaf de Medina, 86 suras fueron reveladas en La Meca y 28 en Medina. Las suras mequíes hablan sobre todo de la fe; las medinenses, también de la vida en comunidad.", src: "Mushaf de Medina" },
    { ar: "سجدة", title: "Lugares de prosternación", body: "En 15 lugares el mushaf de Medina marca una prosternación durante la recitación (suyud at-tilawa). Las escuelas jurídicas cuentan 14 o 15.", src: "p. ej. Corán 7:206, 96:19" },
    { ar: "العصر", title: "Tres suras de tres aleyas", body: "Al-Asr, Al-Kawzar y An-Nasr tienen solo tres aleyas cada una. Se cuenta que el imam ash-Shafi‘i dijo: si la gente reflexionara solo sobre Al-Asr, le bastaría.", src: "Corán 103, 108, 110; Tafsir de Ibn Kazir" },
    { ar: "فأسقيناكموه", title: "Una de las palabras más largas", body: "«fa-asqaynākumūhu» («y os lo dimos a beber», 15:22) tiene once letras y es una de las palabras más largas del Corán.", src: "Corán 15:22" },
    { ar: "عمّ", title: "La última parte: 37 suras", body: "La trigésima parte, el Yuz Amma, contiene 37 suras (78–114): las suras que la mayoría de los musulmanes aprende primero de memoria.", src: "Corán 78–114" },
  ],
  readTitle: "Quien lee el Corán: lo que se le promete",
  readLead: "El Corán no es un libro que se lee una vez y se deja a un lado. Estas palabras del Profeta ﷺ están transmitidas de forma auténtica:",
  hadith: [
    { text: "«Quien lee una letra del Libro de Allah recibe una buena acción, y la buena acción se multiplica por diez. No digo que Alif-Lām-Mīm sea una letra; más bien Alif es una letra, Lām es una letra y Mīm es una letra.»", src: "at-Tirmidhi 2910" },
    { text: "«Leed el Corán, pues el Día de la Resurrección vendrá como intercesor de quienes lo leyeron.»", src: "Sahih Muslim 804" },
    { text: "«Los mejores de vosotros son quienes aprenden el Corán y lo enseñan.»", src: "Sahih al-Bujari 5027" },
    { text: "«Quien domina el Corán está con los nobles y obedientes escribas. Y quien lo lee y tropieza, porque le resulta difícil, tiene doble recompensa.»", src: "Sahih al-Bujari 4937, Sahih Muslim 798" },
    { text: "«Se le dirá al compañero del Corán: Lee y asciende, y recita como solías recitar en el mundo; tu rango estará en la última aleya que leas.»", src: "Abu Dawud 1464, at-Tirmidhi 2914" },
  ],
  wealthTitle: "Bendición, sustento, prosperidad",
  wealthLead: "El Corán no promete ninguna fórmula para hacer dinero rápido. Promete algo mayor: la baraka –una bendición que hace que lo poco rinda mucho–, una buena vida y sustento de donde uno no lo espera. Estas son sus propias palabras (en cuanto al sentido):",
  promises: [
    { ref: "71:10-12", title: "Pedir perdón", text: "«Pedid perdón a vuestro Señor: Él es Perdonador. Os enviará lluvia en abundancia, os dará aumento de riquezas e hijos, y os proveerá de jardines y ríos.»" },
    { ref: "14:7", title: "Gratitud", text: "«Si sois agradecidos, os daré sin duda más.»" },
    { ref: "65:2-3", title: "Conciencia de Allah y confianza", text: "«Quien teme a Allah, Él le abrirá una salida y le proveerá de donde no espera. Y quien confía en Allah, Él le basta.»" },
    { ref: "7:96", title: "Bendición para ciudades enteras", text: "«Si los habitantes de las ciudades hubieran creído y hubieran temido a Allah, les habríamos abierto bendiciones del cielo y de la tierra.»" },
    { ref: "16:97", title: "Una buena vida", text: "«Quien obre con rectitud, sea varón o mujer, siendo creyente, le haremos vivir sin duda una buena vida.»" },
    { ref: "35:29-30", title: "Un comercio que nunca fracasa", text: "«Quienes recitan el Libro de Allah, establecen la oración y gastan de lo que les hemos proveído, esperan un comercio que nunca perecerá.»" },
    { ref: "13:28", title: "Descanso para el corazón", text: "«Ciertamente, con el recuerdo de Allah los corazones encuentran sosiego.»" },
    { ref: "17:82", title: "Curación", text: "«Hacemos descender del Corán lo que es curación y misericordia para los creyentes.»" },
  ],
  wealthNote: "Leer mucho el Corán no hace rico a nadie «automáticamente», pero te hace rico en lo que perdura: calma, gratitud, confianza y una recompensa que nunca termina. Y quien trabaja con honradez, da gracias y pide perdón puede esperar el sustento de Allah.",
  wealthHadith: { text: "«La riqueza no consiste en la abundancia de bienes; la riqueza es la riqueza del alma.»", src: "Sahih al-Bujari 6446, Sahih Muslim 1051" },
  placesTitle: "Lugares donde el corazón encuentra paz",
  placesLead: "La paz con Allah se puede encontrar en cualquier parte: Él está cerca. Pero hay lugares y momentos que Él ha bendecido de manera especial.",
  places: [
    { ar: "المسجد الحرام", title: "Al-Masjid al-Haram, La Meca", body: "La Casa de Allah, la Kaaba, la dirección de toda oración. Una oración allí vale más que cien mil oraciones en otros lugares.", src: "Ibn Maya 1406 (considerado auténtico por los sabios)" },
    { ar: "المسجد النبوي", title: "La Mezquita del Profeta, Medina", body: "Una oración allí es mejor que mil en otros lugares, salvo la Mezquita Sagrada. Y entre su casa y su púlpito hay «un jardín de los jardines del Paraíso».", src: "Sahih al-Bujari 1190, 1196; Sahih Muslim 1394" },
    { ar: "المسجد الأقصى", title: "Al-Masjid al-Aqsa, Jerusalén", body: "La primera qibla, cuyo entorno Allah ha bendecido (17:1); una de las tres mezquitas hacia las que se emprende viaje de manera especial.", src: "Sahih al-Bujari 1189, Sahih Muslim 1397" },
    { ar: "بيوت الله", title: "Cada mezquita", body: "Los lugares más queridos por Allah son las mezquitas. Y donde la gente se reúne allí, lee el Corán y lo estudia junta, desciende sobre ellos la serenidad (sakīnah), la misericordia los cubre y los ángeles los rodean.", src: "Sahih Muslim 671, 2699" },
    { ar: "بيتك", title: "Tu casa", body: "«No hagáis de vuestras casas cementerios. Satanás huye de la casa en la que se recita la sura Al-Baqara.» Un lugar fijo para tu lectura diaria convierte tu casa en un lugar de paz.", src: "Sahih Muslim 780" },
    { ar: "الثلث الأخير", title: "El último tercio de la noche", body: "Un lugar en el tiempo: en el último tercio de cada noche Allah llama: «¿Quién Me invoca para que le responda? ¿Quién Me pide para que le dé?»", src: "Sahih al-Bujari 1145, Sahih Muslim 758" },
    { ar: "آيات الكون", title: "En la creación", body: "«En la creación de los cielos y la tierra y en la alternancia de la noche y el día hay signos para la gente dotada de entendimiento», quienes recuerdan a Allah de pie, sentados y de costado (3:190–191).", src: "Corán 3:190–191" },
    { ar: "جامع الشيخ زايد", title: "En los Emiratos", body: "La Gran Mezquita Sheikh Zayed en Abu Dabi, la Mezquita de Jumeirah en Dubái y las grandes mezquitas de Sharjah dan la bienvenida a los visitantes: lugares de quietud en medio de la vida.", src: "", href: "/islam/mosques" },
  ],
  note: "Los hadices se dan con su colección y número. Las aleyas se ofrecen en cuanto al sentido; toca una referencia para leer el texto árabe y una traducción reconocida. Para cuestiones sobre dictámenes, consulta a un sabio.",
  ctaTitle: "No te quedes en el asombro",
  ctaBody: "Cada letra cuenta por diez. Empieza hoy con una aleya: el Método Shams te guía paso a paso.",
  cta: "Aprende tu primera aleya",
};
export default c;
