import type { SecretsContent } from "../../secrets/content";
const c: SecretsContent = {
  kicker: "Kontrol edildi, tahmin edilmedi",
  title: "Kur’an’ın Sırları",
  lead: "Kur’an hakkında pek çok rakam ve “mucize” dolaşıyor – kimi doğru, kimi değil. Burada kendimiz sayıyoruz, eksiksiz Osmanlı hattı (Uthmani) metninde, ve neyin sabit olduğunu açıkça söylüyoruz. Ayrıca: Kur’an okuyana neler vaat edildiği ve kalbin huzuru en kolay nerede bulduğu.",
  counterTitle: "Kur’an’da kaç kez geçiyor?",
  counterLead: "Bir kelimeye dokun. Kaç kez geçtiğini ve geçtiği her yeri görürsün – doğrudan okumaya hazır.",
  method: "Medine’deki Kral Fahd Mushaf Kompleksi’nin Osmanlı hattı (Uthmani) metninde sayıldı (6.236 ayet, Hafs sayımı). Kelime biçimleri “el-” takısı ve öne gelen edatlarla (ve-, fe-, bi-, li-, ke-) birlikte sayılır; bitişik zamirler sayılmaz; özel isimlerde ayrıca “yâ” nidası da dahildir. Başka sayım yöntemleri biraz farklı rakamlar verebilir – bu yüzden yöntemi belirtiyoruz.",
  times: "kez", spots: "yer", open: "Aç", allahNote: "“Allah” için yalnızca sayıyı gösteriyoruz – yerleri bir liste için fazla çok.",
  words: [
    { key: "fearNot", ar: "@", label: "“Korkma”" },
    { key: "noFear", ar: "@", label: "“Onlara korku yoktur”" },
    { key: "allah", ar: "@", label: "Allah" },
    { key: "rahman", ar: "@", label: "Rahmân (Çok Merhametli)" },
    { key: "yawm", ar: "@", label: "Gün" },
    { key: "shahr", ar: "@", label: "Ay" },
    { key: "dunya", ar: "@", label: "Dünya" },
    { key: "akhira", ar: "@", label: "Âhiret" },
    { key: "musa", ar: "@", label: "Musa" },
    { key: "ibrahim", ar: "@", label: "İbrahim" },
    { key: "nuh", ar: "@", label: "Nuh" },
    { key: "yusuf", ar: "@", label: "Yusuf" },
    { key: "isa", ar: "@", label: "İsa" },
    { key: "adam", ar: "@", label: "Âdem" },
    { key: "maryam", ar: "@", label: "Meryem" },
    { key: "muhammad", ar: "@", label: "Muhammed ﷺ" },
    { key: "ahmad", ar: "@", label: "Ahmed ﷺ" },
  ],
  claimsTitle: "Yaygın iddialar – yeniden sayıldı",
  claimsLead: "Sosyal medyada paylaşılanlar çoğu zaman iyi niyetle yapılır. Ama Kur’an’ın uydurma rakamlara ihtiyacı yoktur. Her iddiayı kendimiz kontrol ettik.",
  verdicts: { true: "Doğru", false: "Tam öyle değil", method: "Doğru – bu sayım yöntemiyle" },
  claims: [
    { q: "“Korkma” Kur’an’da 365 kez geçer – yılın her günü için bir kez.", v: "false", key: "fearNot", a: "Doğrudan bir hitap olarak – “lā takhaf”, “lā takhāfī”, “lā takhāfū”, “lā takhāfā” – 13 kez geçer: İbrahim’e, Musa ile Harun’a, Musa’nın annesine, Lût’a, Dâvûd’a ve müminlere söylenmiştir. Buna ek olarak 13 kez “onlara korku yoktur, onlar üzülmeyeceklerdir” müjdesi gelir. Toplam 26 yer – iddia edilenden az, ama her biri bir teselli." },
    { q: "“Gün” kelimesi Kur’an’da 365 kez geçer.", v: "method", key: "yawm", a: "Tekil “yawm” ve “yawman” biçimlerini – “el-” takısı ve edatlarla birlikte, ancak bitişik zamirler ve “yawma’idhin” (o gün) olmadan – sayarsak tam 365 yer çıkar. Başka sayım yöntemleriyle başka rakamlar çıkar. Yine de dikkat çekicidir." },
    { q: "“Ay” kelimesi Kur’an’da 12 kez geçer.", v: "true", key: "shahr", a: "Tekil biçimde (“shahr”, “ash-shahr”, “shahran”) 12 yer vardır. Kur’an da şöyle der: “Allah katında ayların sayısı on ikidir” (9:36)." },
    { q: "“Dünya” ve “Âhiret” eşit sayıda geçer – her biri 115 kez.", v: "method", key: "dunya", a: "“El-” takısı ve edatlarla sayıldığında: ad-dunyā 115 kez, al-ākhira 115 kez. 3:72 sayılmaz; orada “ākhirahu”, Âhiret değil, (günün) “sonu” anlamına gelir." },
    { q: "“Allah” ismi Kur’an’da 2.699 kez geçer.", v: "true", key: "allah", a: "wallāhi, billāhi, lillāhi gibi tüm ön eklerle sayıldığında 2.699 yer çıkar (“Allāhumma” hariç). Bu, bilinen sayımlarla örtüşür." },
    { q: "Musa, en çok anılan peygamberdir.", v: "true", key: "musa", a: "Musa 136 kez adıyla anılır – diğer tüm peygamberlerden fazla. Onu İbrahim (69), Nuh (43), Yusuf (27), İsa ve Âdem (25’er) izler." },
    { q: "Meryem, Kur’an’da adıyla anılan tek kadındır.", v: "true", key: "maryam", a: "Evet. Adı 34 kez geçer ve koca bir sure onun adını taşır: 19. sure, Meryem." },
    { q: "Peygamber Muhammed ﷺ yalnızca dört kez adıyla anılır.", v: "true", key: "muhammad", a: "Dört kez “Muhammed” olarak (3:144, 33:40, 47:2, 48:29) ve bir kez “Ahmed” olarak (61:6) – başka birçok yerde Allah ona “Ey Peygamber” ve “Ey Resul” diye seslenir." },
  ],
  factsTitle: "Gerçekten şaşırtan şeyler – kaynağıyla",
  facts: [
    { ar: "@", title: "En büyük sure", body: "Peygamber ﷺ, Fâtiha’yı Kur’an’ın en büyük suresi ve “sık tekrarlanan yedi ayet” olarak adlandırdı – namazın her rekâtında okunur.", src: "Sahîh-i Buhârî 4474" },
    { ar: "@", title: "En büyük ayet", body: "Âyetü’l-Kürsî (2:255), Allah’ın Kitabı’ndaki en büyük ayettir – Peygamber ﷺ bunu sahabisi Übey b. Ka‘b’a böyle öğretti.", src: "Sahîh-i Müslim 810" },
    { ar: "@", title: "Kur’an’ın üçte biri", body: "İhlâs suresi (112) Kur’an’ın üçte birine denktir – Allah’ın birliği hakkında dört kısa ayet.", src: "Sahîh-i Buhârî 5013" },
    { ar: "@", title: "İlk kelime", body: "Hira Mağarası’ndaki ilk vahiy “Oku!” ile başlar (96:1–5). Kur’an, iniş yolculuğuna ilimle başlar.", src: "Sahîh-i Buhârî 3" },
    { ar: "@", title: "114 besmele", body: "“Bismillâhirrahmânirrahîm”, Tevbe hariç 113 surenin başında yer alır ve bir kez de bir surenin ortasında: Süleyman’ın Sebe Melikesi’ne yazdığı mektupta (27:30). Toplam 114 – sure sayısı kadar.", src: "Kur’an 27:30" },
    { ar: "@", title: "En uzun ayet", body: "En uzun ayet “borç ayeti”dir (2:282): borçların yazıyla nasıl kaydedileceğini düzenler – Kur’an’ın günlük hayatta adaleti ne kadar ciddiye aldığının bir göstergesi.", src: "Kur’an 2:282" },
    { ar: "@", title: "En kısa sure", body: "Kevser (108) üç ayet ve on kelimeden oluşur. En uzun sure olan Bakara 286 ayettir.", src: "Kur’an 108, 2" },
    { ar: "@", title: "114 sure, 6.236 ayet", body: "Kur’an 114 sure ve 6.236 ayetten oluşur (Hafs sayımı) ve 30 cüze ayrılır. Metnimizde 77.429 kelime vardır – sayım yöntemine göre başkaları biraz farklı rakamlar verir.", src: "Osmanlı hattı (Uthmani) metin, Kral Fahd Kompleksi" },
  ],
  readTitle: "Kur’an okuyana neler vaat edilir",
  readLead: "Kur’an, bir kez okunup bir kenara bırakılacak bir kitap değildir. Peygamber’in ﷺ şu sözleri sahih olarak nakledilmiştir:",
  hadith: [
    { text: "“Kim Allah’ın Kitabı’ndan bir harf okursa, ona bir iyilik yazılır; iyilik de on katıyla karşılık bulur. ‘Elif-Lâm-Mîm bir harftir’ demiyorum; fakat elif bir harftir, lâm bir harftir, mîm de bir harftir.”", src: "Tirmizî 2910" },
    { text: "“Kur’an’ı okuyun; çünkü o, kıyamet günü kendisini okuyanlara şefaatçi olarak gelecektir.”", src: "Sahîh-i Müslim 804" },
    { text: "“Sizin en hayırlınız, Kur’an’ı öğrenen ve öğretendir.”", src: "Sahîh-i Buhârî 5027" },
    { text: "“Kur’an’da mahir olan kimse, şerefli ve itaatkâr kâtiplerle birliktedir. Kur’an’ı okuyup zorlandığı için kekeleyen kimsenin ise iki kat sevabı vardır.”", src: "Sahîh-i Buhârî 4937, Sahîh-i Müslim 798" },
    { text: "“Kur’an sahibine şöyle denilir: Oku ve yüksel, dünyada okuduğun gibi oku – makamın, okuyacağın son ayettedir.”", src: "Ebû Dâvûd 1464, Tirmizî 2914" },
  ],
  wealthTitle: "Bereket, rızık, bolluk",
  wealthLead: "Kur’an, çabuk zengin olmanın bir formülünü vaat etmez. Daha büyük bir şey vaat eder: berekete – azı çok kılan bir bolluğa –, güzel bir hayata ve insanın ummadığı yerden rızka. Bunlar onun kendi sözleridir (anlam olarak):",
  promises: [
    { ref: "71:10-12", title: "Bağışlanma dilemek", text: "“Rabbinizden bağışlanma dileyin – O, çok bağışlayıcıdır. O da üzerinize bol bol yağmur gönderir, size mallar ve oğullarla yardım eder, size bahçeler ve ırmaklar verir.”" },
    { ref: "14:7", title: "Şükür", text: "“Şükrederseniz, size elbette daha fazlasını veririm.”" },
    { ref: "65:2-3", title: "Takva ve tevekkül", text: "“Kim Allah’tan sakınırsa, Allah ona bir çıkış yolu açar ve onu ummadığı yerden rızıklandırır. Kim de Allah’a güvenirse, O ona yeter.”" },
    { ref: "7:96", title: "Bütün şehirlere bereket", text: "“O ülkelerin halkı iman edip sakınmış olsalardı, üzerlerine gökten ve yerden bereketler açardık.”" },
    { ref: "16:97", title: "Güzel bir hayat", text: "“Erkek olsun kadın olsun, mümin olarak kim salih bir amel işlerse, ona mutlaka güzel bir hayat yaşatırız.”" },
    { ref: "35:29-30", title: "Asla zarar etmeyen bir ticaret", text: "“Allah’ın Kitabı’nı okuyanlar, namazı kılanlar ve kendilerine verdiğimiz rızıktan harcayanlar, asla batmayacak bir ticaret umarlar.”" },
    { ref: "13:28", title: "Kalbe huzur", text: "“Bilin ki kalpler ancak Allah’ı anmakla huzur bulur.”" },
    { ref: "17:82", title: "Şifa", text: "“Biz Kur’an’dan, müminler için şifa ve rahmet olan şeyleri indiriyoruz.”" },
  ],
  wealthNote: "Çok Kur’an okuyan kimse “otomatik olarak” zengin olmaz – ama kalıcı olana zengin olur: huzura, şükre, güvene ve hiç bitmeyen bir mükâfata. Dürüstçe çalışan, şükreden ve bağışlanma dileyen de Allah’ın rızkını ümit edebilir.",
  wealthHadith: { text: "“Zenginlik, mal çokluğu değildir; zenginlik, gönül zenginliğidir.”", src: "Sahîh-i Buhârî 6446, Sahîh-i Müslim 1051" },
  placesTitle: "Kalbin huzur bulduğu yerler",
  placesLead: "Allah’la huzur her yerde bulunabilir – O yakındır. Ama O’nun özellikle mübarek kıldığı yerler ve vakitler vardır.",
  places: [
    { ar: "@", title: "Mescid-i Harâm, Mekke", body: "Allah’ın Evi, Kâbe, her namazın yönü. Orada kılınan bir namaz, başka yerlerde kılınan yüz bin namazdan daha fazla sayılır.", src: "İbn Mâce 1406 (âlimlerce sahih kabul edilmiştir)" },
    { ar: "@", title: "Mescid-i Nebevî, Medine", body: "Orada kılınan bir namaz, Mescid-i Harâm hariç, başka yerlerde kılınan bin namazdan daha hayırlıdır. Peygamber’in evi ile minberi arasında ise “cennet bahçelerinden bir bahçe” vardır.", src: "Sahîh-i Buhârî 1190, 1196; Sahîh-i Müslim 1394" },
    { ar: "@", title: "Mescid-i Aksâ, Kudüs", body: "Çevresini Allah’ın mübarek kıldığı (17:1) ilk kıble – özellikle yolculuk yapılan üç mescitten biri.", src: "Sahîh-i Buhârî 1189, Sahîh-i Müslim 1397" },
    { ar: "@", title: "Her mescit", body: "Allah katında en sevgili yerler mescitlerdir. İnsanlar orada toplanıp Kur’an okuduklarında ve onu birlikte öğrendiklerinde üzerlerine huzur (sekîne) iner, rahmet onları kuşatır ve melekler etraflarını sarar.", src: "Sahîh-i Müslim 671, 2699" },
    { ar: "@", title: "Evin", body: "“Evlerinizi mezarlığa çevirmeyin. Şeytan, içinde Bakara suresi okunan evden kaçar.” Günlük okuman için belirli bir yer, evini huzur yeri yapar.", src: "Sahîh-i Müslim 780" },
    { ar: "@", title: "Gecenin son üçte biri", body: "Zamanda bir yer: Allah her gecenin son üçte birinde şöyle seslenir: “Kim bana dua ediyor ki ona karşılık vereyim? Kim benden istiyor ki ona vereyim?”", src: "Sahîh-i Buhârî 1145, Sahîh-i Müslim 758" },
    { ar: "@", title: "Yaratılışta", body: "“Göklerin ve yerin yaratılışında, gece ile gündüzün art arda gelişinde akıl sahipleri için deliller vardır” – ki onlar ayakta, otururken ve yanları üzerine yatarken Allah’ı anarlar (3:190–191).", src: "Kur’an 3:190–191" },
    { ar: "@", title: "Emirliklerde", body: "Abu Dabi’deki Şeyh Zayed Büyük Camii, Dubai’deki Jumeirah Camii ve Şarika’nın büyük camileri ziyaretçileri karşılar – hayatın ortasında sükûnet mekânları.", src: "", href: "/islam/mosques" },
  ],
  note: "Hadisler, kaynak ve numarasıyla verilmiştir. Ayetler anlam olarak aktarılmıştır; Arapça metni ve kabul görmüş bir meali, ayet numarasına dokunarak bulabilirsin. Hükümlere dair sorularda bir âlime danış.",
  ctaTitle: "Hayranlıkla yetinme",
  ctaBody: "Her harf on katıyla sayılır. Bugün bir ayetle başla – Shams Metodu seni adım adım götürür.",
  cta: "İlk ayetini öğren",
};
export default c;
