import type { RawName } from "./index";

// Boys' names that Muslim families really use.
// [id, Arabic, transliterations (first = common form), meaning de, meaning en, meaning ar, origin tags, themes, Quran verse where the name/word appears]
// Origin "quran" only when the name itself (or the very word) occurs in that verse.
export const BOYS: RawName[] = [
  // the Prophet ﷺ
  ["muhammad", "مُحَمَّد", "Muhammad|Mohammed|Mohamed|Mehmet", "der viel Gepriesene", "the much-praised one", "كثير الخصال المحمودة", ["prophet", "quran"], ["faith", "honour"], "48:29"],
  ["ahmad", "أَحْمَد", "Ahmad|Ahmed", "der Preiswürdigste", "the most praiseworthy", "أكثر الناس حمدًا", ["prophet", "quran"], ["faith", "honour"], "61:6"],
  ["mahmud", "مَحْمُود", "Mahmud|Mahmoud", "gepriesen, lobenswert", "praised, praiseworthy", "المحمود المُثنى عليه", ["arabic", "quran"], ["faith", "honour"], "17:79"],
  ["mustafa", "مُصْطَفَى", "Mustafa|Mostafa", "der Auserwählte", "the chosen one", "المختار، من ألقاب النبي ﷺ", ["arabic"], ["faith", "honour"]],
  // servants of Allah
  ["abdullah", "عَبْدُ الله", "Abdullah|Abdallah", "Diener Allahs", "servant of Allah", "العبد لله", ["arabic", "quran"], ["faith"], "19:30"],
  ["abdurrahman", "عَبْدُ الرَّحْمٰن", "Abdurrahman|Abdul Rahman|Abderrahmane", "Diener des Allerbarmers", "servant of the Most Merciful", "العبد للرحمن", ["sahabi", "arabic"], ["faith", "peace"]],
  ["abdurrahim", "عَبْدُ الرَّحِيم", "Abdurrahim|Abdul Rahim", "Diener des Barmherzigen", "servant of the Especially Merciful", "العبد للرحيم", ["arabic"], ["faith", "peace"]],
  ["abdulaziz", "عَبْدُ العَزِيز", "Abdulaziz|Abdul Aziz", "Diener des Allmächtigen", "servant of the Almighty", "العبد للعزيز", ["arabic"], ["faith", "strength"]],
  ["abdulmalik", "عَبْدُ المَلِك", "Abdulmalik|Abdul Malik", "Diener des Königs", "servant of the King", "العبد للملك", ["arabic"], ["faith", "honour"]],
  ["abdulkarim", "عَبْدُ الكَرِيم", "Abdulkarim|Abdul Karim", "Diener des Freigebigen", "servant of the Most Generous", "العبد للكريم", ["arabic"], ["faith", "virtue"]],
  ["abdulhamid", "عَبْدُ الحَمِيد", "Abdulhamid|Abdul Hamid", "Diener des Preiswürdigen", "servant of the Praiseworthy", "العبد للحميد", ["arabic"], ["faith"]],
  ["abdulqadir", "عَبْدُ القَادِر", "Abdulqadir|Abdelkader|Abdulkadir", "Diener des Allvermögenden", "servant of the All-Capable", "العبد للقادر", ["arabic"], ["faith", "strength"]],
  ["abdussalam", "عَبْدُ السَّلَام", "Abdussalam|Abdul Salam|Abdesselam", "Diener des Friedens (as-Salam)", "servant of the Source of Peace", "العبد للسلام", ["arabic"], ["faith", "peace"]],
  ["abdulwahhab", "عَبْدُ الوَهَّاب", "Abdulwahhab|Abdul Wahab", "Diener des Schenkenden", "servant of the Bestower", "العبد للوهاب", ["arabic"], ["faith"]],
  ["abdulghani", "عَبْدُ الغَنِيّ", "Abdulghani|Abdul Ghani", "Diener des Unbedürftigen", "servant of the Self-Sufficient", "العبد للغني", ["arabic"], ["faith"]],
  ["abdullatif", "عَبْدُ اللَّطِيف", "Abdullatif|Abdul Latif", "Diener des Feinfühligen, Gütigen", "servant of the Subtle, the Kind", "العبد للطيف", ["arabic"], ["faith", "virtue"]],
  ["abdulhadi", "عَبْدُ الهَادِي", "Abdulhadi|Abdul Hadi", "Diener des Rechtleitenden", "servant of the Guide", "العبد للهادي", ["arabic"], ["faith", "knowledge"]],
  ["abdulbasit", "عَبْدُ البَاسِط", "Abdulbasit|Abdul Basit", "Diener dessen, der die Versorgung weit macht", "servant of the One who expands provision", "العبد للباسط", ["arabic"], ["faith"]],
  ["abdulwahid", "عَبْدُ الوَاحِد", "Abdulwahid|Abdul Wahid", "Diener des Einen", "servant of the One", "العبد للواحد", ["arabic"], ["faith"]],
  ["abdulfattah", "عَبْدُ الفَتَّاح", "Abdulfattah|Abdel Fattah", "Diener des Öffnenden", "servant of the Opener", "العبد للفتاح", ["arabic"], ["faith"]],
  ["abdulmajid", "عَبْدُ المَجِيد", "Abdulmajid|Abdul Majid", "Diener des Ruhmreichen", "servant of the Glorious", "العبد للمجيد", ["arabic"], ["faith", "honour"]],
  ["abdulhayy", "عَبْدُ الحَيّ", "Abdulhayy|Abdul Hay", "Diener des Lebendigen", "servant of the Ever-Living", "العبد للحي", ["arabic"], ["faith"]],
  ["abdulwadud", "عَبْدُ الوَدُود", "Abdulwadud|Abdul Wadud", "Diener des Liebevollen", "servant of the Loving", "العبد للودود", ["arabic"], ["faith", "peace"]],
  ["abdulghafur", "عَبْدُ الغَفُور", "Abdulghafur|Abdul Ghafoor", "Diener des Vergebenden", "servant of the Forgiving", "العبد للغفور", ["arabic"], ["faith"]],
  // prophets
  ["ibrahim", "إِبْرَاهِيم", "Ibrahim|Ebrahim|İbrahim", "Prophet Abraham, der Freund Allahs", "Prophet Abraham, the close friend of Allah", "خليل الله، أبو الأنبياء", ["prophet", "quran"], ["faith", "honour"], "4:125"],
  ["ismail", "إِسْمَاعِيل", "Ismail|Ismael|Esmail", "Prophet Ismael; „Gott hört“", "Prophet Ishmael; 'God hears'", "نبي الله، ابن إبراهيم", ["prophet", "quran"], ["faith", "virtue"], "19:54"],
  ["ishaq", "إِسْحَاق", "Ishaq|Ishak|Isaac", "Prophet Isaak; „er lacht“", "Prophet Isaac; 'he laughs'", "نبي الله، ابن إبراهيم", ["prophet", "quran"], ["faith", "joy"], "37:112"],
  ["yaqub", "يَعْقُوب", "Yaqub|Yakup|Yacoub", "Prophet Jakob", "Prophet Jacob", "نبي الله إسرائيل", ["prophet", "quran"], ["faith"], "19:49"],
  ["yusuf", "يُوسُف", "Yusuf|Youssef|Yousef|Joseph", "Prophet Josef; „Gott vermehrt“", "Prophet Joseph; 'God increases'", "نبي الله الصدّيق", ["prophet", "quran"], ["faith", "beauty"], "12:4"],
  ["musa", "مُوسَى", "Musa|Moussa|Mousa", "Prophet Mose", "Prophet Moses", "كليم الله", ["prophet", "quran"], ["faith", "strength"], "20:9"],
  ["harun", "هَارُون", "Harun|Haroun|Haroon", "Prophet Aaron, Bruder Moses", "Prophet Aaron, brother of Moses", "نبي الله، أخو موسى", ["prophet", "quran"], ["faith"], "19:53"],
  ["dawud", "دَاوُود", "Dawud|Davud|Daoud|Dawood", "Prophet David; „geliebt“", "Prophet David; 'beloved'", "نبي الله صاحب الزبور", ["prophet", "quran"], ["faith", "strength"], "38:17"],
  ["sulayman", "سُلَيْمَان", "Sulayman|Suleiman|Süleyman|Sulaiman", "Prophet Salomo; „Mann des Friedens“", "Prophet Solomon; 'man of peace'", "نبي الله ابن داود", ["prophet", "quran"], ["faith", "peace", "knowledge"], "27:16"],
  ["yunus", "يُونُس", "Yunus|Younes|Younis", "Prophet Jona", "Prophet Jonah", "نبي الله ذو النون", ["prophet", "quran"], ["faith"], "37:139"],
  ["ayyub", "أَيُّوب", "Ayyub|Ayoub|Eyüp|Ayub", "Prophet Hiob, Vorbild der Geduld", "Prophet Job, example of patience", "نبي الله الصابر", ["prophet", "quran"], ["faith", "virtue"], "38:41"],
  ["yahya", "يَحْيَى", "Yahya|Yehia", "Prophet Johannes; „er lebt“", "Prophet John; 'he lives'", "نبي الله ابن زكريا", ["prophet", "quran"], ["faith", "joy"], "19:7"],
  ["zakariya", "زَكَرِيَّا", "Zakariya|Zakaria|Zekeriya", "Prophet Zacharias", "Prophet Zechariah", "نبي الله، كافل مريم", ["prophet", "quran"], ["faith"], "19:2"],
  ["isa", "عِيسَى", "Isa|Issa|Eesa", "Prophet Jesus", "Prophet Jesus", "نبي الله، ابن مريم", ["prophet", "quran"], ["faith", "peace"], "19:34"],
  ["nuh", "نُوح", "Nuh|Nooh|Nouh", "Prophet Noah; „Ruhe, Trost“", "Prophet Noah; 'rest, comfort'", "نبي الله صاحب السفينة", ["prophet", "quran"], ["faith", "peace"], "71:1"],
  ["idris", "إِدْرِيس", "Idris|Idriss|Edris", "Prophet Idris; oft mit „dars“ (Lernen) verbunden", "Prophet Idris; often linked to 'dars' (study)", "نبي الله، رفعه الله مكانًا عليًّا", ["prophet", "quran"], ["faith", "knowledge"], "19:56"],
  ["hud", "هُود", "Hud|Hood", "Prophet Hud, gesandt zum Volk ʿAd", "Prophet Hud, sent to the people of 'Ad", "نبي الله إلى قوم عاد", ["prophet", "quran"], ["faith"], "11:50"],
  ["salih", "صَالِح", "Salih|Saleh", "rechtschaffen; Prophet Salih", "righteous; Prophet Salih", "الصالح، نبي الله إلى ثمود", ["prophet", "quran"], ["faith", "virtue"], "11:61"],
  ["shuayb", "شُعَيْب", "Shuayb|Shoaib|Shuaib", "Prophet Schuʿaib, gesandt nach Madyan", "Prophet Shu'ayb, sent to Madyan", "نبي الله إلى مدين", ["prophet", "quran"], ["faith"], "11:84"],
  ["ilyas", "إِلْيَاس", "Ilyas|Elias|Ilias", "Prophet Elias", "Prophet Elijah", "نبي الله إلياس", ["prophet", "quran"], ["faith"], "37:123"],
  ["adam", "آدَم", "Adam", "Prophet Adam, der erste Mensch", "Prophet Adam, the first human", "أبو البشر", ["prophet", "quran"], ["faith", "knowledge"], "2:31"],
  ["imran", "عِمْرَان", "Imran|Emran", "die Familie ʿImran im Koran; von ʿumr: Leben, Gedeihen", "the family of 'Imran in the Quran; from 'umr: life, flourishing", "والد مريم، ومنه آل عمران", ["quran"], ["faith", "honour"], "3:33"],
  ["luqman", "لُقْمَان", "Luqman|Lokman|Loqman", "Luqman der Weise, nach ihm ist eine Sure benannt", "Luqman the Wise, after whom a surah is named", "لقمان الحكيم", ["quran"], ["knowledge", "virtue"], "31:12"],
  ["taha", "طٰه", "Taha", "die Anfangsbuchstaben der Sure Ta-Ha", "the opening letters of Surah Ta-Ha", "من الحروف المقطعة، اسم سورة", ["quran"], ["faith"], "20:1"],
  ["yasin", "يَاسِين", "Yasin|Yaseen|Yassine", "die Anfangsbuchstaben der Sure Ya-Sin", "the opening letters of Surah Ya-Sin", "من الحروف المقطعة، اسم سورة", ["quran"], ["faith"], "36:1"],
  // companions and the Prophet's family ﷺ
  ["abubakr", "أَبُو بَكْر", "Abu Bakr|Abubakar|Ebubekir", "Kunya des ersten Kalifen, des engsten Gefährten", "the kunya of the first caliph, the closest companion", "الصدّيق، أول الخلفاء", ["sahabi"], ["faith", "honour"]],
  ["umar", "عُمَر", "Umar|Omar|Ömer", "langes Leben; der zweite Kalif", "long life; the second caliph", "من العُمْر، الفاروق", ["sahabi"], ["strength", "honour"]],
  ["uthman", "عُثْمَان", "Uthman|Osman|Usman", "der dritte Kalif; ursprünglich junge Trappe (Vogel)", "the third caliph; originally a young bustard (bird)", "ذو النورين، ثالث الخلفاء", ["sahabi"], ["honour", "virtue"]],
  ["ali", "عَلِيّ", "Ali", "erhaben, hoch", "exalted, high", "الرفيع العالي", ["ahl-al-bayt", "sahabi"], ["strength", "honour"]],
  ["hasan", "حَسَن", "Hasan|Hassan", "gut, schön", "good, beautiful", "الحسن الجميل", ["ahl-al-bayt"], ["beauty", "virtue"]],
  ["husayn", "حُسَيْن", "Husayn|Hussein|Hüseyin|Hussain", "kleiner Hasan: der Gute, Schöne", "little Hasan: the good, handsome one", "تصغير حسن", ["ahl-al-bayt"], ["beauty", "virtue"]],
  ["qasim", "قَاسِم", "Qasim|Kasim|Kassem", "der Verteilende; ein Sohn des Propheten ﷺ", "one who distributes; a son of the Prophet ﷺ", "الذي يقسم، ابن النبي ﷺ", ["ahl-al-bayt"], ["virtue"]],
  ["jafar", "جَعْفَر", "Jafar|Jaafar|Cafer", "Bach, kleiner Fluss", "stream, small river", "النهر الصغير", ["sahabi", "ahl-al-bayt"], ["nature"]],
  ["hamza", "حَمْزَة", "Hamza|Hamzah", "standhaft, stark; Onkel des Propheten ﷺ", "steadfast, strong; uncle of the Prophet ﷺ", "أسد الله، عم النبي ﷺ", ["sahabi"], ["strength"]],
  ["abbas", "عَبَّاس", "Abbas", "ernst; ein Name des Löwen; Onkel des Propheten ﷺ", "stern; a name for the lion; uncle of the Prophet ﷺ", "من أسماء الأسد، عم النبي ﷺ", ["sahabi"], ["strength"]],
  ["khalid", "خَالِد", "Khalid|Khaled|Halit", "ewig, beständig", "eternal, enduring", "الدائم الباقي", ["sahabi"], ["strength"]],
  ["bilal", "بِلَال", "Bilal", "Frische; der erste Muezzin des Islam", "freshness; the first muezzin of Islam", "مؤذن رسول الله ﷺ", ["sahabi"], ["faith", "peace"]],
  ["zayd", "زَيْد", "Zayd|Zaid|Zeyd", "Wachstum; der einzige Gefährte, der im Koran genannt wird", "growth; the only companion named in the Quran", "الزيادة والنماء", ["sahabi", "quran"], ["honour", "joy"], "33:37"],
  ["saad", "سَعْد", "Saad|Sad", "Glück, Segen", "happiness, good fortune", "اليُمن والسعادة", ["sahabi"], ["joy"]],
  ["said", "سَعِيد", "Said|Saeed|Saïd", "glücklich, gesegnet", "happy, blessed", "السعيد", ["sahabi", "quran"], ["joy"], "11:105"],
  ["talha", "طَلْحَة", "Talha|Talhah", "eine Akazienart", "a kind of acacia tree", "شجرة الطلح", ["sahabi"], ["nature"]],
  ["zubayr", "زُبَيْر", "Zubayr|Zubair|Zübeyr", "stark, fest", "strong, firm", "القوي الشديد", ["sahabi"], ["strength"]],
  ["muadh", "مُعَاذ", "Muadh|Moaz|Muaz", "der bei Allah Zuflucht findet", "one protected by Allah", "المحفوظ بالله", ["sahabi"], ["faith", "peace"]],
  ["anas", "أَنَس", "Anas|Enes", "Freundlichkeit, Vertrautheit", "friendliness, warmth", "الأُنس والألفة", ["sahabi"], ["joy", "peace"]],
  ["usama", "أُسَامَة", "Usama|Osama|Usame", "Löwe", "lion", "الأسد", ["sahabi"], ["strength"]],
  ["ammar", "عَمَّار", "Ammar", "der einen Ort belebt und aufbaut", "one who builds and brings life to a place", "كثير العمران", ["sahabi"], ["strength", "virtue"]],
  ["yasir", "يَاسِر", "Yasir|Yasser|Yaser", "leicht, nachsichtig", "easy-going, lenient", "الميسِّر السهل", ["sahabi"], ["peace"]],
  ["suhayb", "صُهَيْب", "Suhayb|Suhaib|Süheyb", "mit rötlichem Haar", "of reddish hair", "الأصهب الشعر", ["sahabi"], ["faith"]],
  ["salman", "سَلْمَان", "Salman|Selman", "sicher, friedlich", "safe, peaceful", "السالم", ["sahabi"], ["peace"]],
  ["musab", "مُصْعَب", "Musab|Mus'ab", "schwer zu bändigen: willensstark", "hard to tame: strong-willed", "الفحل الصعب", ["sahabi"], ["strength"]],
  ["jabir", "جَابِر", "Jabir|Jaber|Cabir", "der Wunden heilt und tröstet", "one who mends and consoles", "الجابر للكسر", ["sahabi"], ["virtue"]],
  ["tamim", "تَمِيم", "Tamim|Tameem", "vollkommen, stark", "complete, strong", "التام الكامل", ["sahabi"], ["strength"]],
  ["hakim", "حَكِيم", "Hakim|Hakeem", "weise", "wise", "الحكيم", ["sahabi", "arabic"], ["knowledge"]],
  ["hassaan", "حَسَّان", "Hassaan|Hassan|Hessan", "sehr schön; Dichter des Propheten ﷺ", "very handsome; poet of the Prophet ﷺ", "شاعر رسول الله ﷺ", ["sahabi"], ["beauty"]],
  ["asim", "عَاصِم", "Asim|Assem|Asem", "Beschützer, Bewahrer", "protector, guardian", "الحامي المانع", ["sahabi"], ["strength"]],
  ["safwan", "صَفْوَان", "Safwan|Safvan", "reiner, glatter Fels", "clear, smooth rock", "الحجر الأملس الصافي", ["sahabi"], ["nature"]],
  ["sahl", "سَهْل", "Sahl", "leicht, sanft", "easy, gentle", "السهل اللين", ["sahabi"], ["peace"]],
  ["harith", "حَارِث", "Harith|Haris", "der Ackerbauer, der sich Mühende", "cultivator, one who strives", "الزارع الكاسب", ["sahabi", "arabic"], ["virtue"]],
  ["aamir", "عَامِر", "Aamir|Amer", "blühend, voller Leben", "flourishing, full of life", "العامر بالخير", ["sahabi"], ["joy"]],
  ["zahir", "زَاهِر", "Zahir|Zaher", "strahlend, blühend", "radiant, blossoming", "المشرق المزهر", ["sahabi", "arabic"], ["light"]],
  ["zainulabidin", "زَيْنُ العَابِدِين", "Zainulabidin|Zain al-Abidin", "Zierde der Anbetenden", "adornment of the worshippers", "لقب علي بن الحسين", ["ahl-al-bayt"], ["faith", "beauty"]],
  // Quran words
  ["tariq", "طَارِق", "Tariq|Tarik|Tarek", "der nachts Kommende; Morgenstern", "night visitor; morning star", "النجم الثاقب", ["quran"], ["light"], "86:1"],
  ["ayman", "أَيْمَن", "Ayman|Eymen", "gesegnet; die rechte Seite", "blessed; the right side", "المبارك الميمون", ["quran", "sahabi"], ["joy", "faith"], "19:52"],
  ["ridwan", "رِضْوَان", "Ridwan|Rizwan|Rıdvan", "Wohlgefallen (Allahs)", "good pleasure (of Allah)", "رضا الله", ["quran"], ["faith", "joy"], "9:72"],
  ["ihsan", "إِحْسَان", "Ihsan|Ehsan|İhsan", "Vortrefflichkeit, Gutes tun", "excellence, doing good", "الإحسان", ["quran"], ["virtue", "faith"], "16:90"],
  ["naim", "نَعِيم", "Naim|Naeem", "Wonne, Glückseligkeit", "bliss, delight", "النعيم والهناء", ["quran"], ["joy"], "82:13"],
  ["ramadan", "رَمَضَان", "Ramadan|Ramazan|Ramadhan", "der Fastenmonat", "the month of fasting", "شهر الصيام", ["quran"], ["faith"], "2:185"],
  ["tawfiq", "تَوْفِيق", "Tawfiq|Tevfik|Toufik", "Gelingen, das Allah schenkt", "success granted by Allah", "التوفيق من الله", ["quran"], ["faith", "joy"], "11:88"],
  ["burhan", "بُرْهَان", "Burhan", "Beweis", "proof, clear evidence", "الحجة البيّنة", ["quran"], ["knowledge"], "4:174"],
  ["furqan", "فُرْقَان", "Furqan|Furkan", "Unterscheidung zwischen Wahr und Falsch", "the criterion between truth and falsehood", "من أسماء القرآن", ["quran"], ["knowledge", "faith"], "25:1"],
  ["najm", "نَجْم", "Najm|Necm", "Stern", "star", "النجم", ["quran"], ["light"], "53:1"],
  ["waqar", "وَقَار", "Waqar|Vakar", "Würde, Gelassenheit", "dignity, composure", "الرزانة والهيبة", ["quran"], ["honour"], "71:13"],
  ["rayhan", "رَيْحَان", "Rayhan|Raihan|Reyhan", "duftende Pflanze, Basilikum", "fragrant plant, sweet basil", "النبات الطيب الرائحة", ["quran"], ["nature"], "55:12"],
  ["khalifa", "خَلِيفَة", "Khalifa|Halife", "Nachfolger, Statthalter", "successor, steward", "الخليفة", ["quran"], ["honour"], "2:30"],
  ["karim", "كَرِيم", "Karim|Kareem|Kerim", "großzügig, edel", "generous, noble", "الكريم", ["arabic", "quran"], ["virtue", "honour"], "17:23"],
  ["rashid", "رَاشِد", "Rashid|Rashed|Raşit", "rechtgeleitet", "rightly guided", "المهتدي", ["arabic", "quran"], ["faith", "knowledge"], "49:7"],
  ["hadi", "هَادِي", "Hadi", "einer, der zum Guten führt", "guide", "المرشد إلى الخير", ["arabic", "quran"], ["faith", "knowledge"], "13:7"],
  ["fuad", "فُؤَاد", "Fuad|Fouad", "Herz", "heart", "القلب", ["arabic", "quran"], ["peace"], "28:10"],
  ["jamil", "جَمِيل", "Jamil|Jameel|Cemil", "schön", "beautiful, handsome", "الحسن الوسيم", ["arabic", "quran"], ["beauty"], "12:18"],
  ["khalil", "خَلِيل", "Khalil|Halil", "enger Freund", "close friend", "الصديق الوفي", ["arabic", "quran"], ["faith", "peace"], "4:125"],
  ["mubarak", "مُبَارَك", "Mubarak", "gesegnet", "blessed", "المبارك", ["arabic", "quran"], ["faith", "joy"], "19:31"],
  ["muhsin", "مُحْسِن", "Muhsin|Mohsen", "der Gutes mit Hingabe tut", "one who does good with excellence", "صاحب الإحسان", ["arabic", "quran"], ["virtue"], "2:112"],
  ["munir", "مُنِير", "Munir|Mounir", "leuchtend", "radiant, shining", "المضيء", ["arabic", "quran"], ["light"], "25:61"],
  ["siraj", "سِرَاج", "Siraj", "Lampe", "lamp", "المصباح", ["arabic", "quran"], ["light"], "33:46"],
  ["sabir", "صَابِر", "Sabir|Saber", "geduldig", "patient", "الصبور", ["arabic", "quran"], ["virtue"], "38:44"],
  ["sadiq", "صَادِق", "Sadiq|Sadek|Sadık", "wahrhaftig", "truthful", "الصادق", ["arabic", "quran"], ["virtue"], "19:54"],
  ["siddiq", "صِدِّيق", "Siddiq|Siddique", "durch und durch wahrhaftig", "utterly truthful", "كثير الصدق", ["arabic", "quran"], ["virtue", "faith"], "12:46"],
  ["shakir", "شَاكِر", "Shakir|Şakir", "dankbar", "grateful", "الشاكر", ["arabic", "quran"], ["faith", "virtue"], "16:121"],
  ["akram", "أَكْرَم", "Akram|Ekrem", "der Edelste, Großzügigste", "most generous, most noble", "الأكثر كرمًا", ["arabic", "quran"], ["honour", "virtue"], "49:13"],
  ["amin", "أَمِين", "Amin|Ameen|Emin", "vertrauenswürdig", "trustworthy", "الأمين", ["arabic", "quran"], ["virtue"], "26:107"],
  ["badr", "بَدْر", "Badr|Bedir", "Vollmond", "full moon", "القمر ليلة تمامه", ["arabic", "quran"], ["light", "beauty"], "3:123"],
  ["bashir", "بَشِير", "Bashir|Beşir|Bachir", "Überbringer froher Botschaft", "bearer of good news", "المبشِّر", ["arabic", "quran"], ["joy"], "2:119"],
  ["munib", "مُنِيب", "Munib", "der sich Allah reuevoll zuwendet", "one who turns to Allah in repentance", "الراجع إلى الله", ["arabic", "quran"], ["faith"], "50:33"],
  ["salim", "سَلِيم", "Salim|Selim", "heil, unversehrt", "sound, safe, whole", "السالم من العيوب", ["arabic", "quran"], ["peace"], "26:89"],
  ["halim", "حَلِيم", "Halim|Haleem", "nachsichtig, sanftmütig", "forbearing, gentle", "الحليم", ["arabic", "quran"], ["virtue", "peace"], "37:101"],
  ["taqi", "تَقِيّ", "Taqi|Taki", "gottesfürchtig", "pious, God-conscious", "التقي", ["arabic", "quran"], ["faith"], "19:13"],
  ["zaki", "زَكِيّ", "Zaki|Zeki", "rein", "pure", "الطاهر النامي", ["arabic", "quran"], ["virtue"], "19:19"],
  ["sajid", "سَاجِد", "Sajid", "der sich (im Gebet) niederwirft", "one who prostrates (in prayer)", "الساجد لله", ["arabic", "quran"], ["faith"], "39:9"],
  ["shahid", "شَاهِد", "Shahid", "Zeuge", "witness", "الشاهد", ["arabic", "quran"], ["faith"], "33:45"],
  ["mubashshir", "مُبَشِّر", "Mubashshir|Mubashir", "Überbringer froher Botschaft", "bringer of glad tidings", "المبشِّر", ["arabic", "quran"], ["joy"], "33:45"],
  ["kazim", "كَاظِم", "Kazim|Kadhim|Kâzım", "der seinen Zorn beherrscht", "one who restrains his anger", "كاظم الغيظ", ["arabic", "quran"], ["virtue"], "3:134"],
  // Arabic words and virtues
  ["amir", "أَمِير", "Amir|Emir", "Prinz, Anführer", "prince, leader", "الأمير", ["arabic"], ["honour"]],
  ["nabil", "نَبِيل", "Nabil|Nabeel", "edel", "noble", "النبيل الفاضل", ["arabic"], ["honour"]],
  ["nuruddin", "نُورُ الدِّين", "Nuruddin|Nureddin|Noureddine", "Licht des Glaubens", "light of the faith", "نور الدين", ["arabic"], ["light", "faith"]],
  ["salahuddin", "صَلَاحُ الدِّين", "Salahuddin|Salaheddine|Selahattin", "Rechtschaffenheit des Glaubens", "righteousness of the faith", "صلاح الدين", ["arabic"], ["faith", "honour"]],
  ["shamsuddin", "شَمْسُ الدِّين", "Shamsuddin|Şemseddin|Chamseddine", "Sonne des Glaubens", "sun of the faith", "شمس الدين", ["arabic"], ["light", "faith"]],
  ["saif", "سَيْف", "Saif|Sayf|Seif", "Schwert", "sword", "السيف", ["arabic"], ["strength"]],
  ["faisal", "فَيْصَل", "Faisal|Faysal|Feysal", "der klar entscheidet", "one who judges decisively", "الحاكم الفاصل", ["arabic"], ["strength", "knowledge"]],
  ["fahd", "فَهْد", "Fahd|Fahad", "Gepard", "cheetah", "الفهد", ["arabic"], ["strength", "nature"]],
  ["faris", "فَارِس", "Faris|Fares", "Reiter, Ritter", "knight, horseman", "الفارس", ["arabic"], ["strength", "honour"]],
  ["habib", "حَبِيب", "Habib|Habeeb", "geliebt", "beloved", "المحبوب", ["arabic"], ["joy"]],
  ["haytham", "هَيْثَم", "Haytham|Haitham", "junger Adler", "young eagle", "فرخ العقاب", ["arabic"], ["strength", "nature"]],
  ["hisham", "هِشَام", "Hisham|Hicham", "Großzügigkeit", "generosity", "الجود والكرم", ["arabic"], ["virtue"]],
  ["jalal", "جَلَال", "Jalal|Celal", "Erhabenheit", "majesty", "العظمة", ["arabic"], ["honour"]],
  ["jamal", "جَمَال", "Jamal|Cemal", "Schönheit", "beauty", "الحُسن", ["arabic"], ["beauty"]],
  ["kamal", "كَمَال", "Kamal|Kemal", "Vollkommenheit", "perfection", "التمام", ["arabic"], ["virtue"]],
  ["majid", "مَاجِد", "Majid|Majed|Macit", "ruhmreich, edel", "glorious, noble", "الشريف الكريم", ["arabic"], ["honour"]],
  ["mansur", "مَنْصُور", "Mansur|Mansour", "siegreich, unterstützt", "victorious, aided", "المؤيَّد بالنصر", ["arabic"], ["strength"]],
  ["marwan", "مَرْوَان", "Marwan|Mervan", "Feuerstein: fest", "flint: firm", "الحجر الصلب", ["arabic"], ["strength"]],
  ["mazin", "مَازِن", "Mazin|Mazen", "Regenwolke", "rain cloud", "السحاب الممطر", ["arabic"], ["nature"]],
  ["murad", "مُرَاد", "Murad|Murat|Mourad", "Wunsch, Ziel", "wish, aim", "المقصود المطلوب", ["arabic"], ["joy"]],
  ["nadir", "نَادِر", "Nadir|Nader", "selten, kostbar", "rare, precious", "النادر النفيس", ["arabic"], ["honour"]],
  ["nasir", "نَاصِر", "Nasir|Nasser", "Helfer, Unterstützer", "helper, supporter", "المعين", ["arabic"], ["strength", "virtue"]],
  ["rayyan", "رَيَّان", "Rayyan|Rayan", "reich getränkt; ein Tor des Paradieses für die Fastenden", "well-watered; a gate of Paradise for those who fast", "باب في الجنة للصائمين", ["arabic"], ["faith", "nature", "joy"]],
  ["riyad", "رِيَاض", "Riyad|Riad", "Gärten", "gardens", "الحدائق", ["arabic"], ["nature"]],
  ["sami", "سَامِي", "Sami|Samy", "erhaben", "elevated, sublime", "الرفيع", ["arabic"], ["honour"]],
  ["samir", "سَمِير", "Samir|Sameer", "Gefährte beim Abendgespräch", "companion in evening conversation", "رفيق السَّمَر", ["arabic"], ["joy"]],
  ["sharif", "شَرِيف", "Sharif|Sherif|Şerif", "edel, ehrenhaft", "noble, honourable", "الشريف", ["arabic"], ["honour"]],
  ["tahir", "طَاهِر", "Tahir|Taher", "rein", "pure", "النقي", ["arabic"], ["virtue"]],
  ["talal", "طَلَال", "Talal", "feiner Regen, Tau", "fine rain, dew", "المطر الخفيف", ["arabic"], ["nature"]],
  ["wasim", "وَسِيم", "Wasim|Waseem", "anmutig, gutaussehend", "handsome, graceful", "الحسن الوجه", ["arabic"], ["beauty"]],
  ["walid", "وَلِيد", "Walid|Waleed|Velid", "Neugeborenes", "newborn", "المولود", ["arabic"], ["joy"]],
  ["ziyad", "زِيَاد", "Ziyad|Ziad", "Zunahme, Wachstum", "growth, increase", "الزيادة", ["arabic"], ["joy"]],
  ["zain", "زَيْن", "Zain|Zayn|Zein", "Schönheit, Zierde", "beauty, grace", "الحُسن والزينة", ["arabic"], ["beauty"]],
  ["adil", "عَادِل", "Adil|Adel", "gerecht", "just, fair", "العادل", ["arabic"], ["virtue"]],
  ["adnan", "عَدْنَان", "Adnan", "der Sesshafte; Stammvater der Araber", "settler; ancestor of the Arabs", "جدّ العرب", ["arabic"], ["honour"]],
  ["anwar", "أَنْوَر", "Anwar|Enver", "strahlender", "more radiant", "الأكثر نورًا", ["arabic"], ["light"]],
  ["arif", "عَارِف", "Arif|Aref", "wissend, kundig", "knowing, wise", "العالم الخبير", ["arabic"], ["knowledge"]],
  ["asad", "أَسَد", "Asad|Esad", "Löwe", "lion", "الأسد", ["arabic"], ["strength"]],
  ["basil", "بَاسِل", "Basil|Basel", "tapfer", "brave", "الشجاع", ["arabic"], ["strength"]],
  ["hamid", "حَامِد", "Hamid|Hamed", "der Allah lobt", "one who praises Allah", "الحامد لله", ["arabic"], ["faith"]],
  ["hashim", "هَاشِم", "Hashim|Hachem|Haşim", "Urgroßvater des Propheten ﷺ; „der Brot bricht“ (für Gäste)", "great-grandfather of the Prophet ﷺ; 'one who breaks bread' (for guests)", "جد النبي ﷺ", ["arabic"], ["honour", "virtue"]],
  ["imad", "عِمَاد", "Imad|Emad", "Pfeiler, Stütze", "pillar, support", "العمود والسند", ["arabic"], ["strength"]],
  ["isam", "عِصَام", "Isam|Essam", "Schutz, Halt", "safeguard", "ما يُعتصم به", ["arabic"], ["strength"]],
  ["junayd", "جُنَيْد", "Junayd|Junaid|Cüneyt", "kleiner Soldat", "little soldier", "تصغير جند", ["arabic"], ["strength"]],
  ["labib", "لَبِيب", "Labib|Labeeb", "klug, verständig", "intelligent, wise", "العاقل الفطن", ["arabic"], ["knowledge"]],
  ["malik", "مَالِك", "Malik|Malek", "Besitzer; König", "owner; king", "المالك", ["arabic"], ["honour"]],
  ["mahdi", "مَهْدِي", "Mahdi|Mehdi", "rechtgeleitet", "rightly guided", "المهتدي", ["arabic"], ["faith"]],
  ["mahir", "مَاهِر", "Mahir|Maher", "geschickt, kundig", "skilful", "الحاذق", ["arabic"], ["knowledge"]],
  ["mujahid", "مُجَاهِد", "Mujahid", "der sich für das Gute anstrengt", "one who strives for good", "المجتهد الباذل", ["arabic"], ["strength", "faith"]],
  ["najib", "نَجِيب", "Najib|Necip|Najeeb", "edel, von edler Herkunft", "noble, of noble birth", "الكريم الحسب", ["arabic"], ["honour"]],
  ["nasim", "نَسِيم", "Nasim|Naseem", "sanfte Brise", "gentle breeze", "الريح اللينة", ["arabic"], ["nature", "peace"]],
  ["rafiq", "رَفِيق", "Rafiq|Rafik", "gütiger Gefährte", "kind companion", "الصاحب اللطيف", ["arabic"], ["peace", "virtue"]],
  ["raid", "رَائِد", "Raed|Raid", "Vorreiter", "pioneer, leader", "الرائد", ["arabic"], ["honour"]],
  ["rami", "رَامِي", "Rami|Ramy", "Bogenschütze", "archer", "الرامي بالسهم", ["arabic"], ["strength"]],
  ["wail", "وَائِل", "Wael|Wail", "der Zuflucht sucht", "one who seeks refuge", "اللاجئ إلى مأمن", ["arabic"], ["peace"]],
  ["yamin", "يَمِين", "Yamin|Yameen", "rechte Hand; Segen", "right hand; blessing", "اليُمن والبركة", ["arabic"], ["joy"]],
  ["zahid", "زَاهِد", "Zahid|Zahed", "genügsam, der Welt entsagend", "content with little, ascetic", "الزاهد", ["arabic"], ["faith", "virtue"]],
  ["faruq", "فَارُوق", "Faruq|Farouk|Faruk", "der Wahr und Falsch unterscheidet; Beiname Umars", "one who tells truth from falsehood; title of Umar", "لقب عمر بن الخطاب", ["arabic"], ["knowledge", "strength"]],
  ["husam", "حُسَام", "Husam|Hossam", "scharfes Schwert", "sharp sword", "السيف القاطع", ["arabic"], ["strength"]],
  ["jawad", "جَوَاد", "Jawad|Javad|Cevat", "großzügig", "generous", "الكريم المعطاء", ["arabic"], ["virtue"]],
  ["muin", "مُعِين", "Muin|Mueen", "Helfer", "helper", "المساعد", ["arabic"], ["virtue"]],
  ["samih", "سَمِيح", "Samih|Sameh", "großzügig, nachsichtig", "generous, forgiving", "السَّمح الكريم", ["arabic"], ["virtue"]],
  ["shafiq", "شَفِيق", "Shafiq|Şefik|Chafik", "mitfühlend, liebevoll", "compassionate, kind", "العطوف", ["arabic"], ["virtue", "peace"]],
  ["hamdan", "حَمْدَان", "Hamdan", "der viel lobt", "one who praises much", "كثير الحمد", ["arabic"], ["faith"]],
  ["zayed", "زَايِد", "Zayed|Zaid", "wachsend, reich an Gutem", "growing, abundant", "الكثير الزائد", ["arabic"], ["joy", "honour"]],
  ["humaid", "حُمَيْد", "Humaid|Humayd", "kleiner Gepriesener", "little praised one", "تصغير حمد", ["arabic"], ["faith"]],
  ["obaid", "عُبَيْد", "Obaid|Ubayd", "kleiner Diener (Allahs)", "little servant (of Allah)", "تصغير عبد", ["arabic"], ["faith"]],
  ["sultan", "سُلْطَان", "Sultan", "Herrschaft, Autorität", "authority, ruler", "السلطة والحجة", ["arabic"], ["honour", "strength"]],
  ["kerem", "كَرَم", "Kerem|Karam", "Großzügigkeit, Edelmut", "generosity, nobility", "الجود", ["arabic"], ["virtue", "honour"]],
  // commonly used Persian and Turkish names
  ["shahin", "شَاهِين", "Shahin|Shaheen|Şahin", "Falke", "falcon", "الصقر", ["other"], ["strength", "nature"]],
  ["arslan", "أَرْسَلَان", "Arslan|Aslan", "Löwe (türkisch)", "lion (Turkish)", "الأسد بالتركية", ["other"], ["strength"]],
  ["arman", "آرْمَان", "Arman", "Wunsch, Ideal (persisch)", "wish, ideal (Persian)", "الأمنية بالفارسية", ["other"], ["joy"]],
  ["kamran", "كَامْرَان", "Kamran", "erfolgreich, glücklich (persisch)", "successful, fortunate (Persian)", "الناجح بالفارسية", ["other"], ["joy"]],
];
