import type { RawName } from "./index";

// Girls' names that Muslim families really use.
// [id, Arabic, transliterations (first = common form), meaning de, meaning en, meaning ar, origin tags, themes, Quran verse]
// The verse is where the name/word appears; for women of the Quran who are not named there (Asiya, Sara, Khawla)
// it is the verse that speaks of them, and the origin tag is then not "quran".
export const GIRLS: RawName[] = [
  // women of the Quran and the prophets' families
  ["maryam", "مَرْيَم", "Maryam|Mariam|Meryem", "Mutter des Propheten ʿIsa; die einzige Frau, die im Koran mit Namen genannt wird", "mother of Prophet Isa; the only woman named in the Quran", "أم عيسى عليه السلام، وسُمّيت باسمها سورة", ["quran"], ["faith", "honour"], "19:16"],
  ["asiya", "آسِيَة", "Asiya|Asiye|Assia", "Frau des Pharao, im Koran als Vorbild gepriesen", "wife of Pharaoh, praised in the Quran as an example", "امرأة فرعون المؤمنة", ["arabic"], ["faith", "strength"], "66:11"],
  ["hajar", "هَاجَر", "Hajar|Hagar|Hacer", "Mutter Ismaels; ihr Lauf zwischen Safa und Marwa lebt in der Pilgerfahrt fort", "mother of Ismail; her search between Safa and Marwa lives on in the Hajj", "أم إسماعيل عليه السلام", ["other"], ["faith", "strength"]],
  ["sara", "سَارَة", "Sara|Sarah", "Frau Ibrahims; „Fürstin“", "wife of Ibrahim; 'princess'", "زوجة إبراهيم عليه السلام", ["other"], ["honour", "joy"], "11:71"],
  ["hawwa", "حَوَّاء", "Hawwa|Hawa|Havva", "Eva, Mutter der Menschheit", "Eve, mother of humankind", "أم البشر", ["other"], ["faith"]],
  ["khadija", "خَدِيجَة", "Khadija|Khadijah|Hatice", "erste Frau des Propheten ﷺ und die Erste, die an ihn glaubte", "first wife of the Prophet ﷺ and the first to believe in him", "أم المؤمنين، أول من آمن", ["sahabiyya"], ["faith", "honour"]],
  ["aisha", "عَائِشَة", "Aisha|Aysha|Ayşe|Aisyah", "lebendig, voller Leben", "living, full of life", "الحيّة، أم المؤمنين", ["sahabiyya"], ["joy", "knowledge"]],
  ["fatima", "فَاطِمَة", "Fatima|Fatma|Fatemeh", "Tochter des Propheten ﷺ; „die Entwöhnende“", "daughter of the Prophet ﷺ; 'one who weans'", "بنت النبي ﷺ", ["ahl-al-bayt"], ["faith", "honour"]],
  ["zahra", "زَهْرَاء", "Zahra|Zehra|Zahraa", "die Strahlende; Beiname Fatimas", "the radiant one; title of Fatima", "المشرقة، لقب فاطمة", ["ahl-al-bayt"], ["light", "beauty"]],
  ["zaynab", "زَيْنَب", "Zaynab|Zainab|Zeynep", "Tochter des Propheten ﷺ; oft als duftende Pflanze erklärt", "daughter of the Prophet ﷺ; often explained as a fragrant plant", "بنت النبي ﷺ، ونبات طيب الرائحة", ["ahl-al-bayt"], ["beauty", "nature"]],
  ["ruqayya", "رُقَيَّة", "Ruqayya|Ruqaiya|Rukiye", "Aufstieg; Tochter des Propheten ﷺ", "ascent; daughter of the Prophet ﷺ", "من الرُّقي، بنت النبي ﷺ", ["ahl-al-bayt"], ["honour"]],
  ["batul", "بَتُول", "Batul|Batool", "ganz Allah ergeben; Beiname Maryams und Fatimas", "devoted to Allah; title of Maryam and Fatima", "المنقطعة للعبادة، لقب مريم وفاطمة", ["ahl-al-bayt"], ["faith", "virtue"]],
  // companions
  ["hafsa", "حَفْصَة", "Hafsa|Hafsah", "junge Löwin; Mutter der Gläubigen", "young lioness; a mother of the believers", "الأسدة الصغيرة، أم المؤمنين", ["sahabiyya"], ["strength"]],
  ["safiyya", "صَفِيَّة", "Safiyya|Safia|Safiye", "rein; auserwählte Freundin", "pure; chosen friend", "الخالصة الصافية", ["sahabiyya"], ["virtue"]],
  ["maymuna", "مَيْمُونَة", "Maymuna|Maimuna|Meymune", "gesegnet, glückverheißend", "blessed, auspicious", "المباركة", ["sahabiyya"], ["joy"]],
  ["salma", "سَلْمَى", "Salma|Selma", "friedlich, unversehrt", "peaceful, safe", "السالمة", ["sahabiyya", "arabic"], ["peace"]],
  ["sumayya", "سُمَيَّة", "Sumayya|Sumaya|Sümeyye", "erhaben; die erste Märtyrerin des Islam", "lofty; the first martyr of Islam", "أول شهيدة في الإسلام", ["sahabiyya"], ["faith", "strength"]],
  ["asma", "أَسْمَاء", "Asma|Esma|Asmaa", "erhaben; auch: Namen", "lofty; also 'names'", "العالية الرفيعة", ["sahabiyya"], ["honour"]],
  ["nusayba", "نُسَيْبَة", "Nusayba|Nusaybah|Nüseybe", "von edler Abstammung; verteidigte den Propheten ﷺ bei Uhud", "of noble lineage; defended the Prophet ﷺ at Uhud", "أم عمارة، المدافعة عن النبي ﷺ يوم أحد", ["sahabiyya"], ["strength", "honour"]],
  ["rufayda", "رُفَيْدَة", "Rufayda|Rufaida", "Hilfe, Stütze; die erste Krankenpflegerin im Islam", "help, support; the first nurse in Islam", "أول ممرضة في الإسلام", ["sahabiyya"], ["virtue"]],
  ["baraka", "بَرَكَة", "Baraka|Barakah|Bereket", "Segen; der Name von Umm Ayman", "blessing; the name of Umm Ayman", "اسم أم أيمن حاضنة النبي ﷺ", ["sahabiyya"], ["faith", "joy"]],
  ["halima", "حَلِيمَة", "Halima|Halimah|Halime", "sanftmütig, nachsichtig; Amme des Propheten ﷺ", "gentle, forbearing; wet nurse of the Prophet ﷺ", "الحليمة، مرضعة النبي ﷺ", ["sahabiyya", "arabic"], ["virtue", "peace"]],
  ["shayma", "شَيْمَاء", "Shayma|Shaimaa|Şeyma", "mit Schönheitsmal; Milchschwester des Propheten ﷺ", "with a beauty mark; foster sister of the Prophet ﷺ", "أخت النبي ﷺ من الرضاعة", ["sahabiyya"], ["beauty"]],
  ["arwa", "أَرْوَى", "Arwa", "Bergziege (Steinbock); Tante des Propheten ﷺ", "mountain ibex; aunt of the Prophet ﷺ", "أنثى الوعل، وعمة النبي ﷺ", ["sahabiyya"], ["nature"]],
  ["hala", "هَالَة", "Hala|Hale", "Lichtkranz um den Mond", "halo around the moon", "دائرة الضوء حول القمر", ["arabic", "sahabiyya"], ["light"]],
  ["hind", "هِنْد", "Hind", "Name von Umm Salama, Mutter der Gläubigen", "name of Umm Salama, a mother of the believers", "اسم أم سلمة أم المؤمنين", ["sahabiyya"], ["honour"]],
  ["khawla", "خَوْلَة", "Khawla|Havle|Khaoula", "Gazelle; die Gefährtin, deren Klage Allah erhörte", "gazelle; the companion whose plea Allah heard", "التي سمع الله قولها", ["sahabiyya"], ["faith", "strength"], "58:1"],
  ["mariya", "مَارِيَة", "Mariya|Maria", "Mariya die Koptin, Mutter von Ibrahim, dem Sohn des Propheten ﷺ", "Mariya the Copt, mother of the Prophet's ﷺ son Ibrahim", "مارية القبطية، أم إبراهيم ابن النبي ﷺ", ["sahabiyya"], ["honour"]],
  ["jamila", "جَمِيلَة", "Jamila|Jamilah|Cemile", "schön", "beautiful", "الحسناء", ["arabic", "sahabiyya"], ["beauty"]],
  ["amina", "آمِنَة", "Amina|Aminah|Emine", "sicher, geborgen; Mutter des Propheten ﷺ", "safe, secure; mother of the Prophet ﷺ", "الآمنة، أم النبي ﷺ", ["arabic"], ["peace"]],
  // Quran words
  ["sakina", "سَكِينَة", "Sakina|Sakinah|Sekine", "Ruhe, innerer Frieden", "tranquillity, inner peace", "الطمأنينة", ["quran", "ahl-al-bayt"], ["peace", "faith"], "48:4"],
  ["huda", "هُدَى", "Huda|Hoda|Hüda", "Rechtleitung", "guidance", "الهداية", ["quran"], ["faith", "knowledge"], "2:2"],
  ["nur", "نُور", "Nur|Noor|Nour", "Licht", "light", "الضياء", ["quran"], ["light"], "24:35"],
  ["rahma", "رَحْمَة", "Rahma|Rahmah", "Barmherzigkeit", "mercy", "الرحمة", ["quran"], ["virtue", "peace"], "21:107"],
  ["iman", "إِيمَان", "Iman|Eman|Imane", "Glaube", "faith", "الإيمان", ["quran"], ["faith"], "49:7"],
  ["amal", "أَمَل", "Amal", "Hoffnung", "hope", "الرجاء", ["quran"], ["joy"], "18:46"],
  ["jannah", "جَنَّة", "Jannah|Jannat|Cennet", "Garten, Paradies", "garden, Paradise", "الجنة", ["quran"], ["faith", "nature"], "89:30"],
  ["firdaws", "فِرْدَوْس", "Firdaws|Firdaus|Firdevs", "der höchste Garten des Paradieses", "the highest garden of Paradise", "أعلى الجنة", ["quran"], ["faith", "nature"], "18:107"],
  ["kawthar", "كَوْثَر", "Kawthar|Kauthar|Kevser", "Fülle; ein Fluss im Paradies", "abundance; a river in Paradise", "الخير الكثير، نهر في الجنة", ["quran"], ["joy", "nature"], "108:1"],
  ["salsabil", "سَلْسَبِيل", "Salsabil|Salsabeel|Selsebil", "eine Quelle im Paradies", "a spring in Paradise", "عين في الجنة", ["quran"], ["nature", "joy"], "76:18"],
  ["tasnim", "تَسْنِيم", "Tasnim|Tasneem|Tesnim", "eine Quelle im Paradies", "a spring in Paradise", "عين في الجنة", ["quran"], ["nature", "joy"], "83:27"],
  ["bushra", "بُشْرَى", "Bushra|Büşra|Boushra", "frohe Botschaft", "good news", "الخبر السار", ["quran"], ["joy"], "10:64"],
  ["isra", "إِسْرَاء", "Isra|Israa|Esra", "die nächtliche Reise; Name der 17. Sure", "the night journey; name of Surah 17", "الرحلة الليلية، اسم سورة", ["quran"], ["faith"], "17:1"],
  ["jana", "جَنَى", "Jana|Janna", "reife Früchte, bereit zum Pflücken", "ripe fruit ready to be picked", "الثمر المجتنى", ["quran"], ["nature", "joy"], "55:54"],
  ["lina", "لِينَة", "Lina|Leena", "zarte Dattelpalme", "tender palm tree", "النخلة اللينة", ["quran"], ["nature"], "59:5"],
  ["marwa", "مَرْوَة", "Marwa|Merve|Marwah", "weißer Stein; der Hügel Marwa bei der Kaaba", "white stone; the hill of Marwa by the Kaaba", "جبل المروة", ["quran"], ["faith", "nature"], "2:158"],
  ["rawda", "رَوْضَة", "Rawda|Rauda|Ravza", "Garten, blühende Wiese", "garden, meadow", "البستان", ["quran"], ["nature"], "30:15"],
  ["rayhana", "رَيْحَانَة", "Rayhana|Reyhane|Raihana", "Basilikum, duftende Pflanze", "sweet basil, fragrant plant", "نبتة طيبة الرائحة", ["quran"], ["nature"], "55:12"],
  ["sadiqa", "صَادِقَة", "Sadiqa|Sadiqah", "wahrhaftig", "truthful", "الصادقة", ["arabic", "quran"], ["virtue"], "33:35"],
  ["sabira", "صَابِرَة", "Sabira|Sabirah", "geduldig", "patient", "الصابرة", ["arabic", "quran"], ["virtue"], "33:35"],
  ["sana", "سَنَاء", "Sana|Sanaa", "Glanz, Helligkeit", "radiance, brilliance", "الضياء والرفعة", ["quran"], ["light"], "24:43"],
  ["yusra", "يُسْرَى", "Yusra|Yüsra|Yosra", "Leichtigkeit", "ease", "اليسر", ["quran"], ["peace", "joy"], "87:8"],
  ["aliya", "عَالِيَة", "Aliya|Aaliyah|Aliye", "erhaben, hoch", "exalted, high", "الرفيعة", ["quran"], ["honour"], "69:22"],
  ["aya", "آيَة", "Aya|Ayah", "Zeichen; Koranvers", "sign; verse of the Quran", "العلامة، وآية القرآن", ["quran"], ["faith"], "19:10"],
  ["bayan", "بَيَان", "Bayan", "Klarheit, Beredsamkeit", "clarity, eloquence", "الفصاحة والوضوح", ["quran"], ["knowledge"], "55:4"],
  ["duaa", "دُعَاء", "Duaa|Doaa|Dua", "Bittgebet", "supplication", "الدعاء", ["quran"], ["faith"], "14:40"],
  ["hanan", "حَنَان", "Hanan", "Zärtlichkeit, Mitgefühl", "tenderness, compassion", "العطف والرحمة", ["quran"], ["virtue", "peace"], "19:13"],
  ["lulua", "لُؤْلُؤَة", "Lulua|Lulwa|Lulu", "Perle", "pearl", "اللؤلؤة", ["quran"], ["beauty"], "55:22"],
  ["nuha", "نُهَى", "Nuha|Nouha", "Verstand, Einsicht", "intellect, understanding", "العقول", ["quran"], ["knowledge"], "20:54"],
  ["radiya", "رَاضِيَة", "Radiya|Radhia|Raziye", "zufrieden", "content, well-pleased", "الراضية بقضاء الله", ["quran"], ["peace", "faith"], "89:28"],
  ["mardiyya", "مَرْضِيَّة", "Mardiyya|Marziya|Merziye", "die Allah wohlgefällt", "one who is pleasing to Allah", "المرضيّ عنها", ["quran"], ["faith"], "89:28"],
  ["sahar", "سَحَر", "Sahar|Seher", "die Zeit vor der Morgendämmerung", "the hour before dawn", "آخر الليل قبيل الفجر", ["quran"], ["light", "faith"], "51:18"],
  ["salwa", "سَلْوَى", "Salwa", "Trost; die Wachteln, die Allah den Kindern Israels sandte", "solace; the quails Allah sent to the Children of Israel", "الطمأنينة، والطير الذي أنزله الله", ["quran"], ["peace"], "2:57"],
  ["shifa", "شِفَاء", "Shifa|Shifaa|Şifa|Syifa", "Heilung", "healing", "الشفاء", ["quran", "sahabiyya"], ["faith", "peace"], "10:57"],
  ["sidra", "سِدْرَة", "Sidra|Sidrah", "Lotusbaum (Sidrat al-Muntaha)", "lote tree (Sidrat al-Muntaha)", "سدرة المنتهى", ["quran"], ["nature", "faith"], "53:14"],
  ["taqwa", "تَقْوَى", "Taqwa|Takva", "Gottesbewusstsein", "God-consciousness", "التقوى", ["quran"], ["faith"], "2:197"],
  ["duha", "ضُحَى", "Duha|Doha", "Licht des Vormittags", "morning light", "وقت الضحى", ["quran"], ["light"], "93:1"],
  ["fajr", "فَجْر", "Fajr|Fecr", "Morgengrauen", "dawn", "الفجر", ["quran"], ["light", "faith"], "89:1"],
  ["ghufran", "غُفْرَان", "Ghufran|Gufran", "Vergebung", "forgiveness", "المغفرة", ["quran"], ["faith"], "2:285"],
  ["husna", "حُسْنَى", "Husna|Hüsna|Housna", "das Schönste, Beste", "the most beautiful, the best", "الحسنى", ["quran"], ["beauty", "faith"], "7:180"],
  ["qamar", "قَمَر", "Qamar|Kamar|Kamer", "Mond", "moon", "القمر", ["quran"], ["light", "beauty"], "54:1"],
  ["raghad", "رَغَد", "Raghad|Rağad", "ein unbeschwertes, reiches Leben", "a carefree, plentiful life", "سعة العيش", ["quran"], ["joy"], "2:35"],
  ["sundus", "سُنْدُس", "Sundus|Sondos", "feine Seide (des Paradieses)", "fine silk (of Paradise)", "الحرير الرقيق", ["quran"], ["beauty"], "18:31"],
  ["qurratulayn", "قُرَّةُ العَيْن", "Qurratulain|Qurrat al-Ayn", "Freude und Trost des Auges", "comfort and joy of the eye", "ما تقرّ به العين", ["quran"], ["joy"], "28:9"],
  ["qanita", "قَانِتَة", "Qanita|Qanitah", "demütig ergeben", "devoutly obedient", "المطيعة الخاشعة", ["quran"], ["faith"], "66:12"],
  ["abida", "عَابِدَة", "Abida|Abidah", "Anbetende", "worshipper", "العابدة", ["quran"], ["faith"], "66:5"],
  // Arabic words and virtues
  ["hana", "هَنَاء", "Hana|Hanaa", "Glück, Wohlbehagen", "happiness, bliss", "السعادة والراحة", ["arabic"], ["joy"]],
  ["hiba", "هِبَة", "Hiba|Heba|Hibe", "Geschenk", "gift", "العطية", ["arabic"], ["joy"]],
  ["ilham", "إِلْهَام", "Ilham|Ilhame", "Eingebung, Inspiration", "inspiration", "الإلهام", ["arabic"], ["knowledge"]],
  ["inaya", "عِنَايَة", "Inaya|Inayah", "Fürsorge", "care, concern", "الرعاية والاهتمام", ["arabic"], ["virtue"]],
  ["inas", "إِينَاس", "Inas|Enas", "Freundlichkeit, Geselligkeit", "friendliness, warmth", "المؤانسة", ["arabic"], ["joy"]],
  ["jumana", "جُمَانَة", "Jumana|Joumana", "Perle aus Silber", "silver pearl", "اللؤلؤة الفضية", ["arabic"], ["beauty"]],
  ["layla", "لَيْلَى", "Layla|Leila|Leyla", "Nacht", "night", "الليل", ["arabic"], ["beauty"]],
  ["lubna", "لُبْنَى", "Lubna|Lubnah", "Styraxbaum (duftendes Harz)", "storax tree (fragrant resin)", "شجرة طيبة الرائحة", ["arabic"], ["nature"]],
  ["lujayn", "لُجَيْن", "Lujayn|Lujain|Loujain", "Silber", "silver", "الفضة", ["arabic"], ["beauty"]],
  ["manal", "مَنَال", "Manal", "das Erreichte, Erfolg", "attainment, achievement", "ما يُنال", ["arabic"], ["joy"]],
  ["safa", "صَفَاء", "Safa|Safaa", "Reinheit, Klarheit", "purity, clarity", "الخلوص والنقاء", ["arabic"], ["virtue", "peace"]],
  ["maysa", "مَيْسَاء", "Maysa|Mayssa", "anmutig im Gang", "graceful in her walk", "الرشيقة في مشيتها", ["arabic"], ["beauty"]],
  ["muna", "مُنَى", "Muna|Mona", "Wünsche, Hoffnungen", "wishes, hopes", "الأماني", ["arabic"], ["joy"]],
  ["nada", "نَدَى", "Nada", "Tau; Großzügigkeit", "dew; generosity", "الندى والكرم", ["arabic"], ["nature", "virtue"]],
  ["najla", "نَجْلَاء", "Najla|Najlaa", "mit großen, schönen Augen", "with wide, beautiful eyes", "واسعة العينين", ["arabic"], ["beauty"]],
  ["nawal", "نَوَال", "Nawal", "Gabe, Geschenk", "gift, favour", "العطاء", ["arabic"], ["joy"]],
  ["rania", "رَانِيَة", "Rania|Raniya", "die (voll Freude) Blickende", "one who gazes (with joy)", "المُديمة النظر", ["arabic"], ["beauty"]],
  ["reem", "رِيم", "Reem|Rim", "weiße Gazelle", "white gazelle", "الظبي الأبيض", ["arabic"], ["beauty", "nature"]],
  ["samira", "سَمِيرَة", "Samira|Samirah", "Gefährtin beim Abendgespräch", "companion in evening conversation", "رفيقة السمر", ["arabic"], ["joy"]],
  ["wafa", "وَفَاء", "Wafa|Wafaa|Vefa", "Treue", "loyalty, faithfulness", "الوفاء بالعهد", ["arabic"], ["virtue"]],
  ["afaf", "عَفَاف", "Afaf", "Sittsamkeit, Keuschheit", "modesty, chastity", "العفة", ["arabic"], ["virtue"]],
  ["abir", "عَبِير", "Abir|Abeer", "Duft", "fragrance", "الرائحة الطيبة", ["arabic"], ["nature", "beauty"]],
  ["amira", "أَمِيرَة", "Amira|Amirah", "Prinzessin", "princess", "الأميرة", ["arabic"], ["honour"]],
  ["anisa", "أَنِيسَة", "Anisa|Anisah|Enise", "vertraute Gefährtin", "friendly companion", "المؤنسة", ["arabic"], ["joy", "peace"]],
  ["basma", "بَسْمَة", "Basma|Besma", "Lächeln", "smile", "الابتسامة", ["arabic"], ["joy"]],
  ["daliya", "دَالِيَة", "Dalia|Daliya", "Weinrebe", "grapevine", "الكرمة", ["arabic"], ["nature"]],
  ["dana", "دَانَة", "Dana", "große Perle", "large pearl", "اللؤلؤة الكبيرة", ["arabic"], ["beauty"]],
  ["farah", "فَرَح", "Farah", "Freude", "joy", "السرور", ["arabic"], ["joy"]],
  ["ghada", "غَادَة", "Ghada", "anmutige junge Frau", "graceful young woman", "الفتاة الناعمة", ["arabic"], ["beauty"]],
  ["habiba", "حَبِيبَة", "Habiba|Habibah", "geliebt", "beloved", "المحبوبة", ["arabic"], ["joy"]],
  ["hadil", "هَدِيل", "Hadil|Hadeel", "Gurren der Tauben", "cooing of doves", "صوت الحمام", ["arabic"], ["nature", "peace"]],
  ["hayat", "حَيَاة", "Hayat", "Leben", "life", "الحياة", ["arabic"], ["joy"]],
  ["ibtisam", "ابْتِسَام", "Ibtisam|Ibtissam", "Lächeln", "smiling", "الابتسام", ["arabic"], ["joy"]],
  ["joud", "جُود", "Joud|Jud", "Großzügigkeit", "generosity", "الكرم", ["arabic"], ["virtue"]],
  ["kamila", "كَامِلَة", "Kamila|Kamilah", "vollkommen", "complete, perfect", "التامة", ["arabic"], ["virtue"]],
  ["karima", "كَرِيمَة", "Karima|Kerime", "großzügig, edel", "generous, noble", "الكريمة", ["arabic"], ["virtue", "honour"]],
  ["lamis", "لَمِيس", "Lamis|Lamees", "zart (bei Berührung)", "soft to the touch", "الناعمة الملمس", ["arabic"], ["beauty"]],
  ["latifa", "لَطِيفَة", "Latifa|Latifah|Letife", "sanft, gütig, feinfühlig", "gentle, kind, subtle", "الرقيقة اللطيفة", ["arabic"], ["virtue", "peace"]],
  ["layan", "لَيَان", "Layan|Lian", "Sanftheit", "gentleness, softness", "اللين", ["arabic"], ["peace"]],
  ["maha", "مَهَا", "Maha", "Arabische Oryx, bekannt für ihre schönen Augen", "Arabian oryx, known for its beautiful eyes", "بقر الوحش، يُشبَّه بها في جمال العينين", ["arabic"], ["beauty", "nature"]],
  ["malika", "مَلِيكَة", "Malika|Malikah|Melike", "Königin", "queen", "الملكة", ["arabic"], ["honour"]],
  ["maram", "مَرَام", "Maram", "Wunsch, Ziel", "aspiration, wish", "المطلب", ["arabic"], ["joy"]],
  ["munira", "مُنِيرَة", "Munira|Munirah", "leuchtend", "radiant", "المضيئة", ["arabic"], ["light"]],
  ["nabila", "نَبِيلَة", "Nabila|Nabilah", "edel", "noble", "النبيلة", ["arabic"], ["honour"]],
  ["nafisa", "نَفِيسَة", "Nafisa|Nafeesa|Nefise", "kostbar", "precious", "الغالية الثمينة", ["arabic"], ["honour"]],
  ["naima", "نَعِيمَة", "Naima|Naeema", "Wohlergehen, sanftes Glück", "comfort, gentle bliss", "المتنعّمة", ["arabic"], ["joy"]],
  ["najwa", "نَجْوَى", "Najwa", "vertrautes Gespräch", "intimate conversation", "الحديث الخافت", ["arabic"], ["peace"]],
  ["rabia", "رَابِعَة", "Rabia|Rabiah", "die Vierte; Rabiʿa al-ʿAdawiyya", "the fourth; Rabi'a al-'Adawiyya", "الرابعة، ومنها رابعة العدوية", ["arabic"], ["faith"]],
  ["rahima", "رَحِيمَة", "Rahima|Rahimah", "barmherzig", "merciful", "الرحيمة", ["arabic"], ["virtue"]],
  ["raja", "رَجَاء", "Raja|Rajaa", "Hoffnung", "hope", "الأمل", ["arabic"], ["faith", "joy"]],
  ["rasha", "رَشَا", "Rasha", "junge Gazelle", "young gazelle", "ولد الظبية", ["arabic"], ["nature", "beauty"]],
  ["ruba", "رُبَى", "Ruba", "Hügel", "hills", "المرتفعات", ["arabic"], ["nature"]],
  ["ruwayda", "رُوَيْدَة", "Ruwayda|Rouaida", "sanft, behutsam", "gentle, walking softly", "المتمهّلة", ["arabic"], ["peace"]],
  ["sabah", "صَبَاح", "Sabah", "Morgen", "morning", "أول النهار", ["arabic"], ["light"]],
  ["samar", "سَمَر", "Samar", "Gespräch am Abend", "evening conversation", "الحديث ليلًا", ["arabic"], ["joy"]],
  ["thurayya", "ثُرَيَّا", "Thurayya|Soraya|Süreyya", "die Plejaden (Sternhaufen)", "the Pleiades (star cluster)", "نجم الثريا", ["arabic"], ["light"]],
  ["widad", "وِدَاد", "Widad|Wedad", "Liebe, Zuneigung", "love, affection", "المودة", ["arabic"], ["peace", "joy"]],
  ["wijdan", "وِجْدَان", "Wijdan|Vicdan", "Gefühl, Gewissen", "feeling, conscience", "الشعور الباطن", ["arabic"], ["virtue"]],
  ["yumna", "يُمْنَى", "Yumna", "gesegnet; rechte Hand", "blessed; right hand", "اليمين والبركة", ["arabic"], ["joy"]],
  ["zakiyya", "زَكِيَّة", "Zakiyya|Zakia|Zekiye", "rein", "pure", "الطاهرة", ["arabic"], ["virtue"]],
  ["zubayda", "زُبَيْدَة", "Zubayda|Zubaida|Zübeyde", "das Beste (wörtl. Sahne); ließ Wasserwege für Pilger bauen", "the best part (lit. cream); built waterworks for pilgrims", "صاحبة عين زبيدة", ["arabic"], ["virtue"]],
  ["hamida", "حَمِيدَة", "Hamida|Hamidah", "lobenswert", "praiseworthy", "المحمودة", ["arabic"], ["honour"]],
  ["hasna", "حَسْنَاء", "Hasna|Hasnaa", "schön", "beautiful", "الجميلة", ["arabic"], ["beauty"]],
  ["kenza", "كَنْزَة", "Kenza|Kanza", "Schatz", "treasure", "الكنز", ["arabic"], ["honour"]],
  ["naila", "نَائِلَة", "Naila|Nailah", "die das Gute erlangt", "one who attains good", "المدركة لما تريد", ["arabic"], ["joy"]],
  ["rahaf", "رَهَف", "Rahaf", "Zartheit, Feinsinn", "delicacy, sensitivity", "الرقة", ["arabic"], ["beauty"]],
  ["samiha", "سَمِيحَة", "Samiha|Samihah", "großzügig, nachsichtig", "generous, forgiving", "السَّمحة", ["arabic"], ["virtue"]],
  ["tahira", "طَاهِرَة", "Tahira|Tahirah", "rein", "pure", "النقية", ["arabic"], ["virtue"]],
  ["nurulayn", "نُورُ العَيْن", "Nurulain|Noor ul Ain", "Licht des Auges", "light of the eye", "نور العين", ["arabic"], ["light"]],
  ["sajida", "سَاجِدَة", "Sajida|Sajidah", "die sich (im Gebet) niederwirft", "one who prostrates (in prayer)", "الساجدة", ["arabic"], ["faith"]],
  ["hira", "حِرَاء", "Hira|Hiraa", "die Höhle Hira, wo die Offenbarung begann", "the cave of Hira, where revelation began", "غار حراء", ["arabic"], ["faith", "light"]],
  ["areej", "أَرِيج", "Areej|Arij", "Duft", "fragrance", "الرائحة الزكية", ["arabic"], ["nature"]],
  ["dima", "دِيمَة", "Dima|Deema", "sanfter, anhaltender Regen", "gentle, lasting rain", "المطر الدائم في سكون", ["arabic"], ["nature"]],
  ["ghaliya", "غَالِيَة", "Ghaliya|Ghalia", "kostbar, teuer", "precious, dear", "الثمينة", ["arabic"], ["honour"]],
  ["hayfa", "هَيْفَاء", "Hayfa|Haifa", "schlank, anmutig", "slender, graceful", "الرشيقة", ["arabic"], ["beauty"]],
  ["leen", "لِين", "Leen|Lin", "Sanftheit", "gentleness", "اللين والرفق", ["arabic"], ["peace"]],
  ["tuqa", "تُقَى", "Tuqa|Tuka", "Frömmigkeit", "piety", "التقوى", ["arabic"], ["faith"]],
  ["waad", "وَعْد", "Waad|Wa'd", "Versprechen", "promise", "العهد", ["arabic"], ["virtue"]],
  ["shahd", "شَهْد", "Shahd", "Honig in der Wabe", "honey in the comb", "العسل في شمعه", ["arabic"], ["joy", "nature"]],
  ["hidaya", "هِدَايَة", "Hidaya|Hidayah|Hidayet", "Rechtleitung", "guidance", "الهداية", ["arabic"], ["faith"]],
  ["salima", "سَلِيمَة", "Salima|Selime", "heil, unversehrt", "sound, safe", "السالمة", ["arabic"], ["peace"]],
  ["alya", "عَلْيَاء", "Alya|Alyaa", "Höhe, Erhabenheit", "heights, loftiness", "الرفعة", ["arabic"], ["honour"]],
  ["warda", "وَرْدَة", "Warda|Wardah", "Rose", "rose", "الوردة", ["arabic"], ["nature", "beauty"]],
  ["zaina", "زَيْنَة", "Zaina|Zeina|Zayna", "Schmuck, Zierde", "adornment, beauty", "الزينة", ["arabic"], ["beauty"]],
  ["inshirah", "انْشِرَاح", "Inshirah|Inşirah", "Weite und Erleichterung des Herzens", "relief and openness of the heart", "انبساط الصدر وسروره", ["arabic"], ["peace", "joy"]],
  // commonly used Persian and Turkish names
  ["yasmin", "يَاسَمِين", "Yasmin|Yasmine|Yasemin", "Jasmin", "jasmine", "زهر الياسمين", ["other"], ["nature", "beauty"]],
  ["nasrin", "نَسْرِين", "Nasrin|Nesrin|Nisrine", "Wildrose (persisch)", "wild rose (Persian)", "ورد بري", ["other"], ["nature", "beauty"]],
  ["fayruz", "فَيْرُوز", "Fairuz|Fayrouz|Firuze", "Türkis (Edelstein, persisch)", "turquoise (gemstone, Persian)", "حجر كريم", ["other"], ["beauty"]],
  ["sawsan", "سَوْسَن", "Sawsan|Sevsen|Sausan", "Lilie", "lily", "زهرة السوسن", ["other"], ["nature", "beauty"]],
  ["narjis", "نَرْجِس", "Narjis|Nergis|Narges", "Narzisse", "narcissus (flower)", "زهرة النرجس", ["other"], ["nature", "beauty"]],
  ["shirin", "شِيرِين", "Shirin|Şirin", "süß, lieblich (persisch)", "sweet, lovely (Persian)", "الحلوة بالفارسية", ["other"], ["joy", "beauty"]],
  ["laleh", "لَالَه", "Laleh|Lale", "Tulpe (persisch)", "tulip (Persian)", "زهرة التوليب بالفارسية", ["other"], ["nature", "beauty"]],
  ["mahnoor", "مَاه‌نُور", "Mahnoor|Mahnur", "Mondlicht (persisch-arabisch)", "moonlight (Persian-Arabic)", "نور القمر", ["other"], ["light", "beauty"]],
  ["elif", "أَلِف", "Elif|Alif", "Alif, der erste Buchstabe des Alphabets", "Alif, the first letter of the alphabet", "الحرف الأول من الأبجدية", ["other"], ["knowledge"]],
];
